import { LanguageCode } from '../types';

export interface CraftLabelSet {
  craftDetailsHeading: string;
  photoGuidance: string;
  category: string;
  craftName: string;
  productType: string;
  material: string;
  technique: string;
  motif: string;
  colors: string;
  region: string;
  description: string;
  culturalContext: string;
  visualFeatures: string;
  confidence: string;
  highConfidence: string;
  needsConfirmation: string;
  voiceReadBtn: string;
  correctWithVoiceBtn: string;
  editManuallyBtn: string;
  confirmDetailsBtn: string;
  retakePhotoBtn: string;
  analyzingCraftMsg: string;
  demoBadge: string;
  geminiBadge: string;
  aiDetectedLabel: string;
  yourCorrectionLabel: string;
  useCorrectionBtn: string;
  askConfirmationSpeech: string;
  askWhichFieldSpeech: string;
  confirmedSpeech: string;
  manualEditTitle: string;
  saveFieldBtn: string;
  cancelBtn: string;
  uncertainAlert: string;
}

export const CRAFT_ATTRIBUTE_LABELS: Record<LanguageCode, CraftLabelSet> = {
  en: {
    craftDetailsHeading: 'AI Detected Craft Details',
    photoGuidance: 'Make sure your craft is clearly visible with good lighting.',
    category: 'Craft Category',
    craftName: 'Craft Name',
    productType: 'Product Type',
    material: 'Material',
    technique: 'Technique',
    motif: 'Motif',
    colors: 'Colors',
    region: 'Region',
    description: 'Description',
    culturalContext: 'Cultural Context',
    visualFeatures: 'Visual Features',
    confidence: 'Confidence',
    highConfidence: 'High Confidence',
    needsConfirmation: 'Needs Confirmation',
    voiceReadBtn: 'Listen to Details 🔊',
    correctWithVoiceBtn: 'Correct with Voice 🎙️',
    editManuallyBtn: 'Edit Manually ✏️',
    confirmDetailsBtn: '✓ Confirm & Continue',
    retakePhotoBtn: 'Retake Photo',
    analyzingCraftMsg: 'AI is analyzing craft weave, technique, and materials...',
    demoBadge: 'Demo AI / Heuristic Result',
    geminiBadge: 'Gemini Vision AI ✨',
    aiDetectedLabel: 'AI Detected:',
    yourCorrectionLabel: 'Your Correction:',
    useCorrectionBtn: 'Use Correction',
    askConfirmationSpeech: 'I detected these details. Please check them. Are these details correct?',
    askWhichFieldSpeech: 'Which detail would you like to correct? You can say the craft name, material, or technique.',
    confirmedSpeech: 'Details confirmed! Proceeding to catalog setup.',
    manualEditTitle: 'Edit Craft Attribute',
    saveFieldBtn: 'Save Change',
    cancelBtn: 'Cancel',
    uncertainAlert: 'Note: AI image analysis identifies visual features, but does not certify GI provenance without official documents.',
  },
  hi: {
    craftDetailsHeading: 'AI द्वारा पहचाने गए शिल्प विवरण',
    photoGuidance: 'सुनिश्चित करें कि आपका हस्तशिल्प अच्छी रोशनी में साफ दिखाई दे रहा है।',
    category: 'शिल्प श्रेणी',
    craftName: 'शिल्प का नाम',
    productType: 'उत्पाद प्रकार',
    material: 'सामग्री / कपड़ा',
    technique: 'बनाने की तकनीक',
    motif: 'पारंपरिक रूपांकन',
    colors: 'रंग',
    region: 'संभावित क्षेत्र',
    description: 'विवरण',
    culturalContext: 'सांस्कृतिक परंपरा',
    visualFeatures: 'हस्तनिर्मित विशेषताएं',
    confidence: 'सटीकता',
    highConfidence: 'उच्च सटीकता',
    needsConfirmation: 'पुष्टि की आवश्यकता',
    voiceReadBtn: 'विवरण सुनें 🔊',
    correctWithVoiceBtn: 'आवाज़ से सुधारें 🎙️',
    editManuallyBtn: 'हाथ से बदलें ✏️',
    confirmDetailsBtn: '✓ विवरण सही हैं, आगे बढ़ें',
    retakePhotoBtn: 'फ़ोटो दोबारा लें',
    analyzingCraftMsg: 'AI आपके शिल्प की बुनाई, सामग्री और तकनीक का विश्लेषण कर रहा है...',
    demoBadge: 'डेमो AI / नियम-आधारित परिणाम',
    geminiBadge: 'जेमिनी विज़न AI ✨',
    aiDetectedLabel: 'AI द्वारा पहचाना गया:',
    yourCorrectionLabel: 'आपका सुधार:',
    useCorrectionBtn: 'सुधार लागू करें',
    askConfirmationSpeech: 'मैंने ये शिल्प विवरण पहचाने हैं। कृपया जांच लें। क्या ये विवरण सही हैं?',
    askWhichFieldSpeech: 'आप कौन सा विवरण सुधारना चाहते हैं? आप सामग्री, शिल्प का नाम या तकनीक बोल सकते हैं।',
    confirmedSpeech: 'विवरण की पुष्टि हो गई है! उत्पाद सूची में आगे बढ़ रहे हैं।',
    manualEditTitle: 'शिल्प विवरण बदलें',
    saveFieldBtn: 'सहेजें',
    cancelBtn: 'रद्द करें',
    uncertainAlert: 'सूचना: AI विश्लेषण केवल दृश्य विशेषताओं की पहचान करता है, यह आधिकारिक GI प्रमाणीकरण नहीं है।',
  },
  te: {
    craftDetailsHeading: 'AI గుర్తించిన హస్తకళ వివరాలు',
    photoGuidance: 'మీ హస్తకళ మంచి వెలుతురులో స్పష్టంగా కనిపించేలా చూడండి.',
    category: 'క్రాఫ్ట్ కేటగిరీ',
    craftName: 'క్రాఫ్ట్ పేరు',
    productType: 'వస్తువు రకం',
    material: 'పదార్థం / మెటీరియల్',
    technique: 'తయారీ విధానం / సాంకేతికత',
    motif: 'సాంప్రదాయ ఆకృతి (మోటిఫ్)',
    colors: 'రంగులు',
    region: 'ప్రాంతం',
    description: 'వివరణ',
    culturalContext: 'సాంస్కృతిక నేపథ్యం',
    visualFeatures: 'చేతిపని గుర్తులు',
    confidence: 'ఖచ్చితత్వం',
    highConfidence: 'అధిక ఖచ్చితత్వం',
    needsConfirmation: 'ధృవీకరణ అవసరం',
    voiceReadBtn: 'వివరాలు వినండి 🔊',
    correctWithVoiceBtn: 'వాయిస్‌తో సరిచేయండి 🎙️',
    editManuallyBtn: 'సవరించండి ✏️',
    confirmDetailsBtn: '✓ వివరాలు సరైనవే, ముందుకు సాగండి',
    retakePhotoBtn: 'మళ్లీ ఫోటో తీయండి',
    analyzingCraftMsg: 'AI మీ హస్తకళ నేత, మెటీరియల్ మరియు శైలిని విశ్లేషిస్తోంది...',
    demoBadge: 'డెమో AI / నమూనా ఫలితం',
    geminiBadge: 'జెమిని విజన్ AI ✨',
    aiDetectedLabel: 'AI గుర్తించిన వివరాలు:',
    yourCorrectionLabel: 'మీ సవరణ:',
    useCorrectionBtn: 'సవరణను వర్తింపజేయండి',
    askConfirmationSpeech: 'నేను ఈ హస్తకళ వివరాలను గుర్తించాను. దయచేసి తనిఖీ చేయండి. ఈ వివరాలు సరైనవేనా?',
    askWhichFieldSpeech: 'మీరు ఏ వివరాలు మార్చాలనుకుంటున్నారు? మెటీరియల్, క్రాఫ్ట్ పేరు లేదా తయారీ విధానం చెప్పండి.',
    confirmedSpeech: 'వివరాలు ఖరారయ్యాయి! కాటలాగ్ పూర్తి చేయడానికి ముందుకు వెళ్తున్నాం.',
    manualEditTitle: 'వివరాలు సవరించండి',
    saveFieldBtn: 'సేవ్ చేయండి',
    cancelBtn: 'రద్దు చేయండి',
    uncertainAlert: 'గమనిక: AI ఫోటో ఆధారంగా మాత్రమే గుర్తిస్తుంది; ఇది ప్రభుత్వ GI సర్టిఫికేషన్ కాదు.',
  },
  ta: {
    craftDetailsHeading: 'AI கண்டறிந்த கைவினை விவரங்கள்',
    photoGuidance: 'உங்கள் கைவினைப் பொருள் நல்ல வெளிச்சத்தில் தெளிவாக இருப்பதை உறுதி செய்யவும்.',
    category: 'கைவினைப் பிரிவு',
    craftName: 'கைவினைப் பெயர்',
    productType: 'பொருள் வகை',
    material: 'பயன்படுத்தப்பட்ட பொருள்',
    technique: 'உருவாக்க முறை',
    motif: 'பாரம்பரிய வடிவமைப்பு',
    colors: 'வண்ணங்கள்',
    region: 'பிராந்தியம்',
    description: 'விளக்கம்',
    culturalContext: 'கலாச்சார பின்னணி',
    visualFeatures: 'கைவினை அம்சங்கள்',
    confidence: 'துல்லியம்',
    highConfidence: 'உயர் துல்லியம்',
    needsConfirmation: 'உறுதிப்படுத்தல் தேவை',
    voiceReadBtn: 'விவரங்களைக் கேளுங்கள் 🔊',
    correctWithVoiceBtn: 'குரல் மூலம் திருத்தவும் 🎙️',
    editManuallyBtn: 'கைமுறையாக மாற்றவும் ✏️',
    confirmDetailsBtn: '✓ விவரங்கள் சரி, தொடரவும்',
    retakePhotoBtn: 'மீண்டும் படம் எடுக்கவும்',
    analyzingCraftMsg: 'AI உங்கள் கைவினை நெசவு மற்றும் பொருளை ஆராய்கிறது...',
    demoBadge: 'டெமோ AI முடிவு',
    geminiBadge: 'ஜெமினி விஷன் AI ✨',
    aiDetectedLabel: 'AI கண்டறிந்தது:',
    yourCorrectionLabel: 'உங்கள் திருத்தம்:',
    useCorrectionBtn: 'திருத்தத்தைப் பயன்படுத்து',
    askConfirmationSpeech: 'நான் இந்த விவரங்களைக் கண்டறிந்துள்ளேன். தயவுசெய்து சரிபார்க்கவும். இவை சரியானவையா?',
    askWhichFieldSpeech: 'எந்த விவரத்தை மாற்ற விரும்புகிறீர்கள்? பொருள், பெயர் அல்லது நுட்பத்தைச் சொல்லுங்கள்.',
    confirmedSpeech: 'விவரங்கள் உறுதி செய்யப்பட்டன! பட்டியல் உருவாக்க தொடர்கிறது.',
    manualEditTitle: 'கைவினை விவரத்தை மாற்றவும்',
    saveFieldBtn: 'சேமிக்கவும்',
    cancelBtn: 'ரத்து செய்',
    uncertainAlert: 'குறிப்பு: AI பார்வை விவரங்களை மட்டுமே அடையாளம் காண்கிறது, இது GI சான்றிதழ் அல்ல.',
  },
  kn: {
    craftDetailsHeading: 'AI ಪತ್ತೆ ಮಾಡಿದ ಕರಕುಶಲ ವಿವರಗಳು',
    photoGuidance: 'ನಿಮ್ಮ ಕರಕುಶಲ ವಸ್ತುವು ಉತ್ತಮ ಬೆಳಕಿನಲ್ಲಿ ಸ್ಪಷ್ಟವಾಗಿ ಕಾಣಿಸುತ್ತಿದೆಯೇ ಎಂದು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ.',
    category: 'ಕರಕುಶಲ ವರ್ಗ',
    craftName: 'ಕರಕುಶಲ ಹೆಸರು',
    productType: 'ಉತ್ಪನ್ನ ಪ್ರಕಾರ',
    material: 'ಸಾಮಗ್ರಿ',
    technique: 'ತಯಾರಿಕಾ ವಿಧಾನ',
    motif: 'ಸಾಂಪ್ರದಾಯಿಕ ವಿನ್ಯಾಸ',
    colors: 'ಬಣ್ಣಗಳು',
    region: 'ಪ್ರದೇಶ',
    description: 'ವಿವರಣೆ',
    culturalContext: 'ಸಾಂಸ್ಕೃತಿಕ ಹಿನ್ನೆಲೆ',
    visualFeatures: 'ಕರಕುಶಲ ಲಕ್ಷಣಗಳು',
    confidence: 'ನಿಖರತೆ',
    highConfidence: 'ಹೆಚ್ಚಿನ ನಿಖರತೆ',
    needsConfirmation: 'ದೃಢೀಕರಣ ಅಗತ್ಯವಿದೆ',
    voiceReadBtn: 'ವಿವರಗಳನ್ನು ಕೇಳಿ 🔊',
    correctWithVoiceBtn: 'ಧ್ವನಿಯಿಂದ ಸರಿಪಡಿಸಿ 🎙️',
    editManuallyBtn: 'ಬದಲಾಯಿಸಿ ✏️',
    confirmDetailsBtn: '✓ ವಿವರಗಳು ಸರಿಯಾಗಿವೆ, ಮುಂದುವರಿಯಿರಿ',
    retakePhotoBtn: 'ಮತ್ತೆ ಫೋಟೋ ತೆಗೆಯಿರಿ',
    analyzingCraftMsg: 'AI ನಿಮ್ಮ ಕರಕುಶಲ ವಿನ್ಯಾಸ ಮತ್ತು ಸಾಮಗ್ರಿಯನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...',
    demoBadge: 'ಡೆಮೊ AI ಫಲಿತಾಂಶ',
    geminiBadge: 'ಜೆಮಿನಿ ವಿಷನ್ AI ✨',
    aiDetectedLabel: 'AI ಪತ್ತೆ ಮಾಡಿದ್ದು:',
    yourCorrectionLabel: 'ನಿಮ್ಮ ತಿದ್ದುಪಡಿ:',
    useCorrectionBtn: 'ತಿದ್ದುಪಡಿ ಬಳಸಿ',
    askConfirmationSpeech: 'ನಾನು ಈ ವಿವರಗಳನ್ನು ಗುರುತಿಸಿದ್ದೇನೆ. ದಯವಿಟ್ಟು ಪರಿಶೀಲಿಸಿ. ಈ ವಿವರಗಳು ಸರಿಯಾಗಿವೆಯೇ?',
    askWhichFieldSpeech: 'ನೀವು ಯಾವ ವಿವರವನ್ನು ಬದಲಾಯಿಸಲು ಬಯಸುತ್ತೀರಿ? ಸಾಮಗ್ರಿ ಅಥವಾ ಹೆಸರನ್ನು ಹೇಳಿ.',
    confirmedSpeech: 'ವಿವರಗಳು ದೃಢೀಕರಿಸಲ್ಪಟ್ಟಿವೆ! ಮುಂದಿನ ಹಂತಕ್ಕೆ ಸಾಗುತ್ತಿದ್ದೇವೆ.',
    manualEditTitle: 'ವಿವರಗಳನ್ನು ಬದಲಾಯಿಸಿ',
    saveFieldBtn: 'ಉಳಿಸಿ',
    cancelBtn: 'ರದ್ದುಮಾಡಿ',
    uncertainAlert: 'ಗಮನಿಸಿ: AI ದೃಶ್ಯ ಲಕ್ಷಣಗಳನ್ನು ಮಾತ್ರ ಗುರುತಿಸುತ್ತದೆ, ಇದು GI ಪ್ರಮಾಣಪತ್ರವಲ್ಲ.',
  },
  ml: {
    craftDetailsHeading: 'AI കണ്ടെത്തിയ കരകൗശല വിവരങ്ങൾ',
    photoGuidance: 'നിങ്ങളുടെ കരകൗശല ഉൽപ്പന്നം നല്ല വെളിച്ചത്തിൽ വ്യക്തമായി കാണുന്നുണ്ടെന്ന് ഉറപ്പാക്കുക.',
    category: 'വിഭാഗം',
    craftName: 'കരകൗശല പേര്',
    productType: 'ഉൽപ്പന്ന തരം',
    material: 'ഉപയോഗിച്ച വസ്തു',
    technique: 'നിർമ്മാണ രീതി',
    motif: 'രൂപകൽപ്പന',
    colors: 'നിറങ്ങൾ',
    region: 'പ്രദേശം',
    description: 'വിവരണം',
    culturalContext: 'സാംസ്കാരിക പാരമ്പര്യം',
    visualFeatures: 'കരകൗശല സവിശേഷതകൾ',
    confidence: 'കൃത്യത',
    highConfidence: 'ഉയർന്ന കൃത്യത',
    needsConfirmation: 'സ്ഥിരീകരണം ആവശ്യമാണ്',
    voiceReadBtn: 'വിവരങ്ങൾ കേൾക്കുക 🔊',
    correctWithVoiceBtn: 'ശബ്ദം വഴി തിരുത്തുക 🎙️',
    editManuallyBtn: 'മാറ്റം വരുത്തുക ✏️',
    confirmDetailsBtn: '✓ വിവരങ്ങൾ ശരിയാണ്, തുടരുക',
    retakePhotoBtn: 'വീണ്ടും ഫോട്ടോ എടുക്കുക',
    analyzingCraftMsg: 'AI നിങ്ങളുടെ കരകൗശലത്തിന്റെ പ്രത്യേകതകൾ വിശകലനം ചെയ്യുന്നു...',
    demoBadge: 'ഡെമോ AI ഫലം',
    geminiBadge: 'ജെമിനി വിഷൻ AI ✨',
    aiDetectedLabel: 'AI കണ്ടെത്തിയത്:',
    yourCorrectionLabel: 'നിങ്ങളുടെ തിരുത്തൽ:',
    useCorrectionBtn: 'തിരുത്തൽ സ്വീകരിക്കുക',
    askConfirmationSpeech: 'ഞാൻ ഈ വിവരങ്ങൾ കണ്ടെത്തി. ദയവായി പരിശോധിക്കുക. ഈ വിവരങ്ങൾ ശരിയാണോ?',
    askWhichFieldSpeech: 'ഏത് വിവരമാണ് മാറ്റേണ്ടത്? വസ്തു അല്ലെങ്കിൽ പേര് പറയുക.',
    confirmedSpeech: 'വിവരങ്ങൾ സ്ഥിരീകരിച്ചു! കാറ്റലോഗിലേക്ക് തുടരുന്നു.',
    manualEditTitle: 'വിവരങ്ങൾ മാറ്റുക',
    saveFieldBtn: 'സംരക്ഷിക്കുക',
    cancelBtn: 'റദ്ദാക്കുക',
    uncertainAlert: 'ശ്രദ്ധിക്കുക: AI കാഴ്ചാ സവിശേഷതകൾ മാത്രമാണ് കണ്ടെത്തുന്നത്, ഇത് GI സർട്ടിഫിക്കറ്റ് അല്ല.',
  },
  mr: {
    craftDetailsHeading: 'AI द्वारे ओळखलेले हस्तकला तपशील',
    photoGuidance: 'आपली हस्तकला चांगल्या प्रकाशात स्पष्ट दिसत असल्याची खात्री करा.',
    category: 'हस्तकला श्रेणी',
    craftName: 'हस्तकला नाव',
    productType: 'उत्पादन प्रकार',
    material: 'साहित्य',
    technique: 'निर्मिती तंत्र',
    motif: 'पारंपरिक नक्षी',
    colors: 'रंग',
    region: 'प्रदेश',
    description: 'वर्णन',
    culturalContext: 'सांस्कृतिक वारसा',
    visualFeatures: 'हस्तनिर्मित वैशिष्ट्ये',
    confidence: 'अचूकता',
    highConfidence: 'उच्च अचूकता',
    needsConfirmation: 'पुष्टी आवश्यक',
    voiceReadBtn: 'तपशील ऐका 🔊',
    correctWithVoiceBtn: 'आवाजाने सुधारा 🎙️',
    editManuallyBtn: 'बदला ✏️',
    confirmDetailsBtn: '✓ तपशील बरोबर आहेत, पुढे जा',
    retakePhotoBtn: 'पुन्हा फोटो काढा',
    analyzingCraftMsg: 'AI आपल्या हस्तकलेचे विश्लेषण करत आहे...',
    demoBadge: 'डेमो AI निकाल',
    geminiBadge: 'जेमिनी व्हिजन AI ✨',
    aiDetectedLabel: 'AI द्वारे ओळखलेले:',
    yourCorrectionLabel: 'तुमची दुरुस्ती:',
    useCorrectionBtn: 'दुरुस्ती वापरा',
    askConfirmationSpeech: 'मी हे हस्तकला तपशील ओळखले आहेत. कृपया तपासा. हे तपशील बरोबर आहेत का?',
    askWhichFieldSpeech: 'तुम्हाला कोणता तपशील बदलायचा आहे? साहित्य किंवा नाव सांगा.',
    confirmedSpeech: 'तपशील निश्चित झाले! उत्पादन नोंदणीकडे जात आहोत.',
    manualEditTitle: 'तपशील बदला',
    saveFieldBtn: 'जतन करा',
    cancelBtn: 'रद्द करा',
    uncertainAlert: 'टीप: AI फक्त दृश्य वैशिष्ट्ये ओळखते, हे GI प्रमाणपत्र नाही.',
  },
  gu: {
    craftDetailsHeading: 'AI દ્વારા શોધાયેલ હસ્તકલા વિગતો',
    photoGuidance: 'ખાતરી કરો કે તમારો હસ્તકલા નમૂનો સારા પ્રકાશમાં સ્પષ્ટ દેખાય છે.',
    category: 'શ્રેણી',
    craftName: 'હસ્તકલા નામ',
    productType: 'ઉત્પાદન પ્રકાર',
    material: 'સામગ્રી',
    technique: 'બનાવવાની પદ્ધતિ',
    motif: 'પરંપરાગત ભાત',
    colors: 'રંગો',
    region: 'પ્રદેશ',
    description: 'વર્ણન',
    culturalContext: 'સાંસ્કૃતિક વારસો',
    visualFeatures: 'હસ્તકલા લક્ષણો',
    confidence: 'ચોકસાઈ',
    highConfidence: 'ઉચ્ચ ચોકસાઈ',
    needsConfirmation: 'પુષ્ટિ જરૂરી છે',
    voiceReadBtn: 'વિગતો સાંભળો 🔊',
    correctWithVoiceBtn: 'અવાજથી સુધારો 🎙️',
    editManuallyBtn: 'સુધારો કરો ✏️',
    confirmDetailsBtn: '✓ વિગતો સાચી છે, આગળ વધો',
    retakePhotoBtn: 'ફરીથી ફોટો લો',
    analyzingCraftMsg: 'AI તમારી હસ્તકલાનું વિશ્લેષણ કરી રહ્યું છે...',
    demoBadge: 'ડેમો AI પરિણામ',
    geminiBadge: 'જેમિની વિઝન AI ✨',
    aiDetectedLabel: 'AI શોધ્યું:',
    yourCorrectionLabel: 'તમારો સુધારો:',
    useCorrectionBtn: 'સુધારો સ્વીકારો',
    askConfirmationSpeech: 'મેં આ હસ્તકલા વિગતો શોધી છે. કૃપા કરીને તપાસો. શું આ વિગતો સાચી છે?',
    askWhichFieldSpeech: 'તમે કઈ વિગત સુધારવા માંગો છો? સામગ્રી અથવા કળાનું નામ બોલો.',
    confirmedSpeech: 'વિગતોની પુષ્ટિ થઈ ગઈ! કેટલોગ તરફ આગળ વધી રહ્યા છીએ.',
    manualEditTitle: 'વિગત સુધારો',
    saveFieldBtn: 'સાચવો',
    cancelBtn: 'રદ કરો',
    uncertainAlert: 'નોંધ: AI માત્ર દ્રશ્ય ગુણો ઓળખે છે, તે સત્તાવાર GI પ્રમાણપત્ર નથી.',
  },
  bn: {
    craftDetailsHeading: 'AI দ্বারা চিহ্নিত হস্তশিল্পের বিবরণ',
    photoGuidance: 'নিশ্চিত করুন আপনার হস্তশিল্পটি ভালো আলোতে স্পষ্টভাবে দেখা যাচ্ছে।',
    category: 'শিল্প বিভাগ',
    craftName: 'শিল্পের নাম',
    productType: 'পণ্যের ধরণ',
    material: 'ব্যবহৃত উপাদান',
    technique: 'তৈরির কৌশল',
    motif: 'ঐতিহ্যবাহী নকশা',
    colors: 'রং',
    region: 'অঞ্চল',
    description: 'বিবরণ',
    culturalContext: 'সাংস্কৃতিক ঐতিহ্য',
    visualFeatures: 'হস্তশিল্পের বৈশিষ্ট্য',
    confidence: 'নির্ভুলতা',
    highConfidence: 'উচ্চ নির্ভুলতা',
    needsConfirmation: 'নিশ্চিতকরণ প্রয়োজন',
    voiceReadBtn: 'বিবরণ শুনুন 🔊',
    correctWithVoiceBtn: 'কণ্ঠে সংশোধন করুন 🎙️',
    editManuallyBtn: 'পরিবর্তন করুন ✏️',
    confirmDetailsBtn: '✓ বিবরণ সঠিক, এগিয়ে যান',
    retakePhotoBtn: 'আবার ছবি তুলুন',
    analyzingCraftMsg: 'AI আপনার হস্তশিল্পের কৌশল ও উপাদান বিশ্লেষণ করছে...',
    demoBadge: 'ডেমো AI ফলাফল',
    geminiBadge: 'জেমিনি ভিশন AI ✨',
    aiDetectedLabel: 'AI চিহ্নিত করেছে:',
    yourCorrectionLabel: 'আপনার সংশোধন:',
    useCorrectionBtn: 'সংশোধন প্রয়োগ করুন',
    askConfirmationSpeech: 'আমি এই হস্তশিল্পের বিবরণ চিহ্নিত করেছি। দয়া করে যাচাই করুন। এই বিবরণ কি সঠিক?',
    askWhichFieldSpeech: 'আপনি কোন বিবরণটি সংশোধন করতে চান? উপাদান বা নাম বলুন।',
    confirmedSpeech: 'বিবরণ নিশ্চিত হয়েছে! ক্যাটালগে এগিয়ে যাচ্ছি।',
    manualEditTitle: 'বিবরণ পরিবর্তন করুন',
    saveFieldBtn: 'সংরক্ষণ করুন',
    cancelBtn: 'বাতিল করুন',
    uncertainAlert: 'নোট: AI বিশ্লেষণ শুধুমাত্র দৃশ্যমান বৈশিষ্ট্য নির্দেশ করে, এটি GI শংসাপত্র নয়।',
  },
  or: {
    craftDetailsHeading: 'AI ଚିହ୍ନଟ କରିଥିବା ହସ୍ତଶିଳ୍ପ ବିବରଣୀ',
    photoGuidance: 'ନିଶ୍ଚିତ କରନ୍ତୁ ଯେ ଆପଣଙ୍କ ହସ୍ତକଳା ଭଲ ଆଲୋକରେ ସ୍ପଷ୍ଟ ଦେଖାଯାଉଛି।',
    category: 'ଶିଳ୍ପ ବିଭାଗ',
    craftName: 'ହସ୍ତଶିଳ୍ପ ନାମ',
    productType: 'ସାମଗ୍ରୀ ପ୍ରକାର',
    material: 'ଉପାଦାନ',
    technique: 'ନିର୍ମାଣ ଶୈଳୀ',
    motif: 'ପାରମ୍ପରିକ ନକ୍ସା',
    colors: 'ରଙ୍ଗ',
    region: 'ଅଞ୍ଚଳ',
    description: 'ବିବରଣୀ',
    culturalContext: 'ସାଂସ୍କୃତିକ ଐତିହ୍ୟ',
    visualFeatures: 'ହସ୍ତତନ୍ତ ବୈଶିଷ୍ଟ୍ୟ',
    confidence: 'ସଠିକତା',
    highConfidence: 'ଉଚ୍ଚ ସଠିକତା',
    needsConfirmation: 'ପୁଷ୍ଟିକରଣ ଆବଶ୍ୟକ',
    voiceReadBtn: 'ବିବରଣୀ ଶୁଣନ୍ତୁ 🔊',
    correctWithVoiceBtn: 'ଭଏସରେ ସଂଶୋଧନ କରନ୍ତୁ 🎙️',
    editManuallyBtn: 'ବଦଳାନ୍ତୁ ✏️',
    confirmDetailsBtn: '✓ ବିବରଣୀ ଠିକ୍ ଅଛି, ଆଗକୁ ବଢ଼ନ୍ତୁ',
    retakePhotoBtn: 'ପୁଣି ଫଟୋ ନିଅନ୍ତୁ',
    analyzingCraftMsg: 'AI ଆପଣଙ୍କ ହସ୍ତଶିଳ୍ପର ବିଶ୍ଳେଷଣ କରୁଛି...',
    demoBadge: 'ଡେମୋ AI ଫଳାଫଳ',
    geminiBadge: 'ଜେମିନି ଭିଜନ AI ✨',
    aiDetectedLabel: 'AI ଚିହ୍ନଟ କରିଛି:',
    yourCorrectionLabel: 'ଆପଣଙ୍କ ସଂଶୋଧନ:',
    useCorrectionBtn: 'ସଂଶୋଧନ ଗ୍ରହଣ କରନ୍ତୁ',
    askConfirmationSpeech: 'ମୁଁ ଏହି ହସ୍ତଶିଳ୍ପ ବିବରଣୀ ଚିହ୍ନଟ କରିଛି। ଦୟାକରି ଯାଞ୍ଚ କରନ୍ତୁ। ଏହି ବିବରଣୀ ଠିକ୍ ଅଛି କି?',
    askWhichFieldSpeech: 'ଆପଣ କେଉଁ ବିବରଣୀ ବଦଳାଇବାକୁ ଚାହାଁନ୍ତି? ଉପାଦାନ ବା ନାମ କୁହନ୍ତୁ।',
    confirmedSpeech: 'ବିବରଣୀ ନିଶ୍ଚିତ ହେଲା! କାଟାଲଗ୍ ଆଗକୁ ବଢ଼ୁଛି।',
    manualEditTitle: 'ବିବରଣୀ ବଦଳାନ୍ତୁ',
    saveFieldBtn: 'ସାଇତନ୍ତୁ',
    cancelBtn: 'ବାତିଲ୍ କରନ୍ତୁ',
    uncertainAlert: 'ସୂଚନା: AI କେବଳ ଦୃଶ୍ୟମାନ ଲକ୍ଷଣ ଚିହ୍ନଟ କରେ, ଏହା GI ପ୍ରମାଣପତ୍ର ନୁହେଁ।',
  },
  pa: {
    craftDetailsHeading: 'AI ਦੁਆਰਾ ਪਛਾਣੇ ਗਏ ਦਸਤਕਾਰੀ ਵੇਰਵੇ',
    photoGuidance: 'ਯਕੀਨੀ ਬਣਾਓ ਕਿ ਤੁਹਾਡਾ ਦਸਤਕਾਰੀ ਨਮੂਨਾ ਚੰਗੀ ਰੋਸ਼ਨੀ ਵਿੱਚ ਸਾਫ਼ ਦਿਸਦਾ ਹੈ।',
    category: 'ਸ਼੍ਰੇਣੀ',
    craftName: 'ਦਸਤਕਾਰੀ ਦਾ ਨਾਮ',
    productType: 'ਉਤਪਾਦ ਦੀ ਕਿਸਮ',
    material: 'ਸਮੱਗਰੀ',
    technique: 'ਬਣਾਉਣ ਦੀ ਤਕਨੀਕ',
    motif: 'ਰਵਾਇਤੀ ਨਮੂਨਾ',
    colors: 'ਰੰਗ',
    region: 'ਖੇਤਰ',
    description: 'ਵੇਰਵਾ',
    culturalContext: 'ਸੱਭਿਆਚਾਰਕ ਵਿਰਾਸਤ',
    visualFeatures: 'ਦਸਤਕਾਰੀ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ',
    confidence: 'ਸ਼ੁੱਧਤਾ',
    highConfidence: 'ਉੱਚ ਸ਼ੁੱਧਤਾ',
    needsConfirmation: 'ਪੁਸ਼ਟੀ ਲੋੜੀਂਦੀ ਹੈ',
    voiceReadBtn: 'ਵੇਰਵੇ ਸੁਣੋ 🔊',
    correctWithVoiceBtn: 'ਆਵਾਜ਼ ਨਾਲ ਠੀਕ ਕਰੋ 🎙️',
    editManuallyBtn: 'ਬਦਲੋ ✏️',
    confirmDetailsBtn: '✓ ਵੇਰਵੇ ਸਹੀ ਹਨ, ਅੱਗੇ ਵਧੋ',
    retakePhotoBtn: 'ਦੁਬਾਰਾ ਫੋਟੋ ਲਵੋ',
    analyzingCraftMsg: 'AI ਤੁਹਾਡੇ ਦਸਤਕਾਰੀ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰ ਰਿਹਾ ਹੈ...',
    demoBadge: 'ਡੈਮੋ AI ਨਤੀਜਾ',
    geminiBadge: 'ਜੈਮਿਨੀ ਵਿਜ਼ਨ AI ✨',
    aiDetectedLabel: 'AI ਨੇ ਪਛਾਣਿਆ:',
    yourCorrectionLabel: 'ਤੁਹਾਡਾ ਸੁਧਾਰ:',
    useCorrectionBtn: 'ਸੁਧਾਰ ਲਾਗੂ ਕਰੋ',
    askConfirmationSpeech: 'ਮੈਂ ਇਹ ਦਸਤਕਾਰੀ ਵੇਰਵੇ ਪਛਾਣੇ ਹਨ। ਕਿਰਪਾ ਕਰਕੇ ਜਾਂਚ ਕਰੋ। ਕੀ ਇਹ ਵੇਰਵੇ ਸਹੀ ਹਨ?',
    askWhichFieldSpeech: 'ਤੁਸੀਂ ਕਿਹੜਾ ਵੇਰਵਾ ਬਦਲਣਾ ਚਾਹੁੰਦੇ ਹੋ? ਸਮੱਗਰੀ ਜਾਂ ਨਾਮ ਬੋਲੋ।',
    confirmedSpeech: 'ਵੇਰਵਿਆਂ ਦੀ ਪੁਸ਼ਟੀ ਹੋ ਗਈ! ਉਤਪਾਦ ਸੂਚੀ ਵੱਲ ਵਧ ਰਹੇ ਹਾਂ।',
    manualEditTitle: 'ਵੇਰਵੇ ਬਦਲੋ',
    saveFieldBtn: 'ਸੰਭਾਲੋ',
    cancelBtn: 'ਰੱਦ ਕਰੋ',
    uncertainAlert: 'ਨੋਟ: AI ਸਿਰਫ ਦਿਖਾਈ ਦੇਣ ਵਾਲੀਆਂ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ ਪਛਾਣਦਾ ਹੈ, ਇਹ GI ਪ੍ਰਮਾਣੀਕਰਣ ਨਹੀਂ ਹੈ।',
  },
  as: {
    craftDetailsHeading: 'AI দ্বাৰা চিনাক্ত কৰা হস্তশিল্পৰ বিৱৰণ',
    photoGuidance: 'নিশ্চিত কৰক আপোনাৰ হস্তশিল্পটো পোহৰত স্পষ্টকৈ দেখা গৈছে।',
    category: 'শিল্প বিভাগ',
    craftName: 'হস্তশিল্পৰ নাম',
    productType: 'সামগ্ৰীৰ প্ৰকাৰ',
    material: 'ব্যৱহৃত সামগ্ৰী',
    technique: 'নিৰ্মাণ পদ্ধতি',
    motif: 'পৰম্পৰাগত নক্সা',
    colors: 'ৰং',
    region: 'অঞ্চল',
    description: 'বিৱৰণ',
    culturalContext: 'সাংস্কৃতিক ঐতিহ্য',
    visualFeatures: 'হস্তশিল্পৰ বৈশিষ্ট্য',
    confidence: 'শুদ্ধতা',
    highConfidence: 'উচ্চ শুদ্ধতা',
    needsConfirmation: 'নিশ্চিতকৰণ প্ৰয়োজন',
    voiceReadBtn: 'বিৱৰণ শুনক 🔊',
    correctWithVoiceBtn: 'কণ্ঠৰে সংশোধন কৰক 🎙️',
    editManuallyBtn: 'সলনি কৰক ✏️',
    confirmDetailsBtn: '✓ বিৱৰণ শুদ্ধ, আগবাঢ়ক',
    retakePhotoBtn: 'পুনৰ ফটো তোলক',
    analyzingCraftMsg: 'AI আপোনাৰ হস্তশিল্পৰ বিশেষত্ব বিশ্লেষণ কৰি আছে...',
    demoBadge: 'ডেমো AI ফলাফল',
    geminiBadge: 'জেমিনি ভিজন AI ✨',
    aiDetectedLabel: 'AI চিনাক্ত কৰিছে:',
    yourCorrectionLabel: 'আপোনাৰ সংশোধন:',
    useCorrectionBtn: 'সংশোধন ব্যৱহাৰ কৰক',
    askConfirmationSpeech: 'মই এই হস্তশিল্পৰ বিৱৰণ চিনাক্ত কৰিছোঁ। অনুগ্ৰহ কৰি পৰীক্ষা কৰক। এই বিৱৰণ শুদ্ধনে?',
    askWhichFieldSpeech: 'আপুনি কোনটো বিৱৰণ সলনি কৰিব বিচাৰে? সামগ্ৰী বা নাম কওক।',
    confirmedSpeech: 'বিৱৰণ নিশ্চিত হ’ল! তালিকাৰ দিশে আগবাঢ়িছোঁ।',
    manualEditTitle: 'বিৱৰণ সলনি কৰক',
    saveFieldBtn: 'সংৰক্ষণ কৰক',
    cancelBtn: 'বাতিল কৰক',
    uncertainAlert: 'টোকা: AI কেৱল দৃশ্যমান বৈশিষ্ট্যহে চিনাক্ত কৰে, এইটো GI প্ৰমাণপত্ৰ নহয়।',
  },
};

export function getCraftAttributeLabels(lang: LanguageCode): CraftLabelSet {
  return CRAFT_ATTRIBUTE_LABELS[lang] || CRAFT_ATTRIBUTE_LABELS.en;
}
