import { LanguageCode } from "../../src/types.js";
import { CraftAttributes, CraftTaxonomyEntry } from "./craftInspection.service.js";

/**
 * Curated authentic Indian handicraft taxonomy with comprehensive translations
 * for all 10 required craft types across all 12 supported Indian languages.
 */
export const CRAFT_KNOWLEDGE_BASE: CraftTaxonomyEntry[] = [
  // 1. Handloom Saree (Banarasi / Kanjeevaram Silk Handloom)
  {
    keywords: ["handloom saree", "banarasi", "kanjeevaram", "chanderi", "silk saree", "zari saree", "patola saree"],
    canonical: {
      craftCategory: "Handloom",
      craftName: "Handloom Silk Saree",
      productType: "Saree",
      material: "Pure Mulberry Silk & Zari Thread",
      technique: "Traditional Jacquard & Pit Loom Hand Weaving",
      motif: "Floral Jaal & Temple Borders",
      colors: ["Royal Crimson", "Gold Zari", "Emerald Green"],
      region: "Likely Varanasi (Uttar Pradesh) / Kanchipuram (Tamil Nadu)",
      description: "Loom-woven pure silk saree embellished with intricate gold zari work and traditional heritage motifs.",
      culturalContext: "Centuries-old royal handloom tradition representing the pinnacle of Indian ceremonial textile artistry.",
      visualFeatures: ["Dense zari brocade border", "Lustrous pure handloom drape", "Woven pallu pattern relief"],
      confidence: 0.92,
      uncertainAttributes: ["exact weaver cluster", "zari metal percentage"]
    },
    translations: {
      en: {
        craftCategory: "Handloom",
        craftName: "Handloom Silk Saree",
        productType: "Saree",
        material: "Pure Mulberry Silk & Zari Thread",
        technique: "Traditional Jacquard & Pit Loom Hand Weaving",
        motif: "Floral Jaal & Temple Borders",
        colors: ["Royal Crimson", "Gold Zari", "Emerald Green"],
        region: "Likely Varanasi / Kanchipuram",
        description: "Loom-woven pure silk saree embellished with intricate gold zari work and traditional heritage motifs.",
        culturalContext: "Centuries-old royal handloom tradition representing the pinnacle of Indian ceremonial textile artistry.",
        visualFeatures: ["Dense zari brocade border", "Lustrous pure handloom drape", "Woven pallu pattern relief"]
      },
      te: {
        craftCategory: "చేనేత",
        craftName: "చేనేత పట్టు చీర",
        productType: "చీర",
        material: "స్వచ్ఛమైన మల్బరీ పట్టు మరియు జరీ దారాలు",
        technique: "సాంప్రదాయ మగ్గం నేత మరియు జరీ అల్లిక",
        motif: "పువ్వుల తీగలు మరియు ఆలయ సరిహద్దులు",
        colors: ["ఎరుపు", "బంగారు జరీ", "ఆకుపచ్చ"],
        region: "దక్షిణ / ఉత్తర భారత చేనేత కేంద్రం",
        description: "మగ్గంపై స్వచ్ఛమైన పట్టు దారాలతో అత్యంత నైపుణ్యంతో నేసిన ప్రామాణిక కళాత్మక చీర.",
        culturalContext: "తరతరాలుగా వస్తున్న భారతీయ చేనేత కళా సాంప్రదాయం.",
        visualFeatures: ["సహజ పట్టు మెరుపు", "అందమైన జరీ అంచు", "చేతి నేత నాణ్యత"]
      },
      hi: {
        craftCategory: "हथकरघा",
        craftName: "हथकरघा रेशमी साड़ी",
        productType: "साड़ी",
        material: "शुद्ध शहतूत रेशम और ज़री",
        technique: "पारंपरिक गड्ढा करघा बुनाई",
        motif: "पारंपरिक लताएं और मंदिर सीमा",
        colors: ["शाही लाल", "सुनहरी ज़री", "हरा"],
        region: "संभावित वाराणसी / कांचीपुरम",
        description: "करघे पर हाथ से बुनी गई शुद्ध रेशमी साड़ी, जिसमें महीन ज़री और पारंपरिक नक्काशी दिखाई देती है।",
        culturalContext: "भारतीय परिधान संस्कृति की सदियों पुरानी गौरवशाली हथकरघा परंपरा।",
        visualFeatures: ["बारीक ज़री की किनारी", "शुद्ध रेशमी चमक", "हाथ की बुनाई की पहचान"]
      },
      ta: {
        craftCategory: "கைத்தறி",
        craftName: "கைத்தறி பட்டுப் புடவை",
        productType: "புடவை",
        material: "தூய மல்பெரி பட்டு மற்றும் ஜரிகை",
        technique: "பாரம்பரிய தறி நெசவு",
        motif: "கோயில் கோபுர பார்டர் மற்றும் பூ வேலைப்பாடு",
        colors: ["சிவப்பு", "தங்க ஜரிகை", "பச்சை"],
        region: "காஞ்சிபுரம் / வாரணாசி பகுதி",
        description: "பாரம்பரிய கைத்தறியில் தூய பட்டு நூல்களால் நுணுக்கமாக நெய்யப்பட்ட மங்களகரமான பட்டுப் புடவை.",
        culturalContext: "தலைமுறை தலைமுறையாக போற்றப்படும் இந்திய கைத்தறி நெசவுக் கலை.",
        visualFeatures: ["அடர்ந்த ஜரிகை கரை", "தூய பட்டு பளபளப்பு", "கைத்தறி நெசவு நேர்த்தி"]
      },
      kn: {
        craftCategory: "ಕೈಮಗ್ಗ",
        craftName: "ಕೈಮಗ್ಗದ ರೇಷ್ಮೆ ಸೀರೆ",
        productType: "ಸೀರೆ",
        material: "ಶುದ್ಧ ಮಲ್ಬರಿ ರೇಷ್ಮೆ ಮತ್ತು ಜರಿ",
        technique: "ಸಾಂಪ್ರದಾಯಿಕ ಕೈಮಗ್ಗ ನೇಯ್ಗೆ",
        motif: "ದೇವಾಲಯ ಬಾರ್ಡರ್ ಮತ್ತು ಹೂವಿನ ವಿನ್ಯಾಸ",
        colors: ["ಕೆಂಪು", "ಚಿನ್ನದ ಜರಿ", "ಹಸಿರು"],
        region: "ದಕ್ಷಿಣ / ಉತ್ತರ ಭಾರತೀಯ ಕೈಮಗ್ಗ ಕ್ಲಸ್ಟರ್",
        description: "ಕೈಮಗ್ಗದಲ್ಲಿ ನುರಿತ ನೇಕಾರರಿಂದ ಪ್ರೀತಿಯಿಂದ ನೇಯ್ದ ಅಪ್ಪಟ ರೇಷ್ಮೆ ಸೀರೆ.",
        culturalContext: "ಶತಮಾನಗಳ ಶ್ರೀಮಂತ ಭಾರತೀಯ ಜವಳಿ ಪರಂಪರೆ.",
        visualFeatures: ["ಸ್ಪಷ್ಟ ಜರಿ ಅಂಚು", "ನೈಸರ್ಗಿಕ ರೇಷ್ಮೆ ಹೊಳಪು", "ಕೈನೇಯ್ಗೆಯ ಸಾಂದ್ರತೆ"]
      },
      ml: {
        craftCategory: "കൈത്തറി",
        craftName: "കൈത്തറി പട്ടുസാരി",
        productType: "സാരി",
        material: "ശുദ്ധമായ പട്ടും സരിയും",
        technique: "പരമ്പരാഗത തറി നെയ്ത്ത്",
        motif: "ക്ഷേത്ര മാതൃകയും പൂക്കളും",
        colors: ["ചുവപ്പ്", "സ്വർണ്ണ സരി", "പച്ച"],
        region: "ദക്ഷിണേന്ത്യൻ നെയ്ത്ത് കേന്ദ്രം",
        description: "തഴക്കമുള്ള നെയ്ത്തുകാർ കൈത്തറിയിൽ നെയ്തെടുത്ത പരിശുദ്ധ പട്ടുസാരി.",
        culturalContext: "ഇന്ത്യൻ വസ്ത്ര പാരമ്പര്യത്തിന്റെ മകുടോദാഹരണം.",
        visualFeatures: ["കസവ് അരികുകൾ", "പട്ടിന്റെ തിളക്കം", "നെയ്ത്തിന്റെ സൂക്ഷ്മത"]
      },
      mr: {
        craftCategory: "हातमाग",
        craftName: "हातमाग रेशमी साडी",
        productType: "साडी",
        material: "शुद्ध रेशीम आणि जरी",
        technique: "पारंपरिक हातमाग विणकाम",
        motif: "मंदिराची नक्षी आणि फुलांची वेल",
        colors: ["लाल", "सोनेरी जरी", "हिरवा"],
        region: "पारंपरिक हातमाग केंद्र",
        description: "हातमागावर कुशल कारागिरांनी विणलेली अस्सल शुद्ध रेशमी साडी.",
        culturalContext: "अनेक पिढ्या चालत आलेली भारतीय विणकाम संस्कृती.",
        visualFeatures: ["बारीक जरी काठ", "रेशमी पोਤ", "हाताने विणलेली कलाकुसर"]
      },
      gu: {
        craftCategory: "હાથશાળ",
        craftName: "હાથશાળ રેશમી સાડી",
        productType: "સાડી",
        material: "શુદ્ધ રેશમ અને જરી",
        technique: "પરંપરાગત હાથશાળ વણાટકામ",
        motif: "મંદિર બોર્ડર અને વેલબુટ્ટા",
        colors: ["લાલ", "સોનેરી જરી", "લીલો"],
        region: "પરંપરાગત વણાટ કેન્દ્ર",
        description: "હાથશાળ પર કુશળ વણકરો દ્વારા વણાયેલી અસલ રેશમી સાડી.",
        culturalContext: "ભારતની પ્રાચીન સમૃદ્ધ વસ્ત્ર પરંપરા.",
        visualFeatures: ["સુંદર જરી બોર્ડર", "રેશમની ચમક", "હાથ વણાટની ઓળખ"]
      },
      bn: {
        craftCategory: "হস্তচালিত তাঁত",
        craftName: "হ্যান্ডলুম সিল্ক শাড়ি",
        productType: "শাড়ি",
        material: "খাঁটি তুঁত রেশম ও জরি",
        technique: "ঐতিহ্যবাহী তাঁত বয়ন",
        motif: "মন্দির নকশা ও কলকা",
        colors: ["লাল", "সোনালী জরি", "সবুজ"],
        region: "ঐতিহ্যবাহী বয়ন কেন্দ্র",
        description: "তাঁতের নিখুঁত বুননে তৈরি ঐতিহ্যবাহী খাঁটি সিল্ক শাড়ি।",
        culturalContext: "ভারতের সমৃদ্ধ বস্ত্রশিল্পের এক অনুপম নিদর্শন।",
        visualFeatures: ["ঘন জরির পাড়", "রেশমি দীপ্তি", "হাতের বুনন"]
      },
      or: {
        craftCategory: "ଲୁଗାବୁଣା",
        craftName: "ହସ୍ତତନ୍ତ ପାଟ ଶାଢ଼ୀ",
        productType: "ଶାଢ଼ୀ",
        material: "ବିଶୁଦ୍ଧ ପାଟ ଓ ଜରି",
        technique: "ପାରମ୍ପରିକ ହସ୍ତତନ୍ତ ବୁଣା",
        motif: "ମନ୍ଦିର ତାରକା ଓ ଲତା",
        colors: ["ନାଲି", "ସୁନେଲି ଜରି", "ସବୁଜ"],
        region: "ହସ୍ତତନ୍ତ ବୟନ କ୍ଲଷ୍ଟର",
        description: "ତନ୍ତରେ ହାତରେ ବୁଣା ଯାଇଥିବା ସୁନ୍ଦର ବିଶୁଦ୍ଧ ପାଟ ଶାଢ଼ୀ।",
        culturalContext: "ଭାରତୀୟ ସମୃଦ୍ଧ ବୟନ କଳାର ଅମୂଲ୍ୟ ପରମ୍ପରା।",
        visualFeatures: ["ଚମତ୍କାର ଜରି କୂଳ", "ପାଟର ଉଜ୍ଜ୍ୱଳତା", "ହସ୍ତତନ୍ତ କାରିଗରୀ"]
      },
      pa: {
        craftCategory: "ਖੱਡੀ ਬੁਣਾਈ",
        craftName: "ਹੱਥ-ਖੱਡੀ ਰੇਸ਼ਮੀ ਸਾੜ੍ਹੀ",
        productType: "ਸਾੜ੍ਹੀ",
        material: "ਸ਼ੁੱਧ ਰੇਸ਼ਮ ਅਤੇ ਜ਼ਰੀ",
        technique: "ਰਵਾਇਤੀ ਖੱਡੀ ਬੁਣਾਈ",
        motif: "ਮੰਦਰ ਬਾਰਡਰ ਅਤੇ ਫੁੱਲ ਵੇਲ",
        colors: ["ਲਾਲ", "ਸੁਨਹਿਰੀ ਜ਼ਰੀ", "ਹਰਾ"],
        region: "ਰਵਾਇਤੀ ਬੁਣਾਈ ਕੇਂਦਰ",
        description: "ਹੱਥ-ਖੱਡੀ 'ਤੇ ਮਾਹਿਰ ਬੁਣਕਰਾਂ ਦੁਆਰਾ ਤਿਆਰ ਕੀਤੀ ਗਈ ਸ਼ੁੱਧ ਰੇਸ਼ਮੀ ਸਾੜ੍ਹੀ।",
        culturalContext: "ਸਦੀਆਂ ਪੁਰਾਣੀ ਭਾਰਤੀ ਦਸਤਕਾਰੀ ਵਿਰਾਸਤ।",
        visualFeatures: ["ਸੋਹਣਾ ਜ਼ਰੀ ਬਾਰਡਰ", "ਰੇਸ਼ਮੀ ਚਮਕ", "ਹੱਥੀਂ ਬੁਣਾਈ"]
      },
      as: {
        craftCategory: "তাঁতশাল",
        craftName: "হস্ততাঁত ৰেচম শাড়ী",
        productType: "শাড়ী",
        material: "বিশুদ্ধ পাট ৰেচম আৰু জৰী",
        technique: "পৰম্পৰাগত তাঁত বয়ন",
        motif: "মন্দিৰৰ আৰ্হি আৰু ফুলৰ লতা",
        colors: ["ৰঙা", "সোণালী জৰী", "সেউজীয়া"],
        region: "পৰম্পৰাগত বয়ন অঞ্চল",
        description: "তাঁতশালত নিপুণ শিপিনীয়ে বোৱা বিশুদ্ধ ৰেচমৰ সুন্দৰ শাড়ী।",
        culturalContext: "ভাৰতীয় চহকী বয়ন ঐতিহ্যৰ নিদৰ্শন।",
        visualFeatures: ["ঘন জৰীৰ পাৰি", "ৰেচমৰ উজ্জ্বলতা", "হাতে বোৱা গাঁথনি"]
      }
    }
  },

  // 2. Pochampally Ikat
  {
    keywords: ["pochampally", "ikat", "patola", "double ikat", "bhoodan", "tie dye weaving"],
    canonical: {
      craftCategory: "Weaving",
      craftName: "Pochampally Ikat",
      productType: "Saree",
      material: "Pure Mulberry Silk",
      technique: "Double Ikat Resist Dyeing & Pit Loom Weaving",
      motif: "Geometric Chowkada Diamond",
      colors: ["Crimson Red", "Mustard Ochre", "Natural Ecru"],
      region: "Likely Telangana (Yadadri Bhuvanagiri)",
      description: "Handcrafted pure silk saree featuring precision resist-dyed geometric patterns woven on traditional wooden pit looms.",
      culturalContext: "Hereditary pit-loom weaving tradition from Telangana celebrated for mathematical dye-resist alignment.",
      visualFeatures: ["Sharp geometric rhombus patterns", "Subtle feathered ikat edge characteristic of resist-dyeing", "High-density handloom silk luster"],
      confidence: 0.88,
      uncertainAttributes: ["exact village", "specific weaver family"]
    },
    translations: {
      en: {
        craftCategory: "Weaving",
        craftName: "Pochampally Ikat",
        productType: "Saree",
        material: "Pure Mulberry Silk",
        technique: "Double Ikat Resist Dyeing & Pit Loom Weaving",
        motif: "Geometric Chowkada Diamond",
        colors: ["Crimson Red", "Mustard Ochre", "Natural Ecru"],
        region: "Likely Telangana (Yadadri Bhuvanagiri)",
        description: "Handcrafted pure silk saree featuring precision resist-dyed geometric patterns woven on traditional wooden pit looms.",
        culturalContext: "Hereditary pit-loom weaving tradition from Telangana celebrated for mathematical dye-resist alignment.",
        visualFeatures: ["Sharp geometric rhombus patterns", "Subtle feathered ikat edge characteristic of resist-dyeing", "High-density handloom silk luster"]
      },
      te: {
        craftCategory: "చేనేత",
        craftName: "పోచంపల్లి ఇక్కత్",
        productType: "చీర",
        material: "స్వచ్ఛమైన మల్బరీ పట్టు",
        technique: "డబుల్ ఇక్కత్ టై-డై & మగ్గం నేత",
        motif: "జ్యామితీయ చౌకడా డైమండ్",
        colors: ["ఎరుపు", "పసుపు", "సహజ పట్టు తెలుపు"],
        region: "తెలంగాణ (యాదాద్రి భువనగిరి)",
        description: "సాంప్రదాయ పిట్ మగ్గాలపై పట్టు దారాలతో అత్యంత ఖచ్చితత్వంతో నేసిన ప్రామాణిక పోచంపల్లి డబుల్ ఇక్కత్ పట్టు చీర.",
        culturalContext: "శతాబ్దాల వారసత్వంగా వస్తున్న తెలంగాణ చేనేత కళారూపం.",
        visualFeatures: ["స్పష్టమైన జ్యామితీయ నమూనాలు", "ఇక్కత్ ప్రత్యేక అంచు", "సహజ పట్టు మెరుపు"]
      },
      hi: {
        craftCategory: "हथकरघा बुनाई",
        craftName: "पोचमपल्ली इकत",
        productType: "साड़ी",
        material: "शुद्ध शहतूत रेशम",
        technique: "डबल इकत टाई-डाई एवं गड्ढा करघा बुनाई",
        motif: "ज्यामितीय चौकाड़ा हीरा",
        colors: ["लाल", "हल्दी पीला", "प्राकृतिक रेशम श्वेत"],
        region: "संभावित तेलंगाना",
        description: "पारंपरिक गड्ढा करघे पर हाथ से बुनी गई शुद्ध रेशम पोचमपल्ली इकत साड़ी, जिसमें जटिल ज्यामितीय पैटर्न दिखाई देते हैं।",
        culturalContext: "तेलंगाना की सदियों पुरानी विरासत बुनाई परंपरा।",
        visualFeatures: ["सटीक ज्यामितीय आकृतियां", "इकत की विशिष्ट रेशमी बनावट", "हाथ की बुनाई की चमक"]
      },
      ta: {
        craftCategory: "கைத்தறி நெசவு",
        craftName: "போச்சம்பள்ளி இக்கத்",
        productType: "புடவை",
        material: "தூய மல்பெரி பட்டு",
        technique: "இரட்டை இக்கத் டை-டை மற்றும் குழித்தறி நெசவு",
        motif: "வடிவியல் வைரம்",
        colors: ["சிவப்பு", "மஞ்சள்", "இயற்கை பட்டு வெள்ளை"],
        region: "தெலுங்கானா பகுதி",
        description: "பாரம்பரிய மரக் குழித்தறிகளில் கைவினைக் கலைஞர்களால் தூய பட்டு நூலில் நெய்யப்பட்ட உண்மையான போச்சம்பள்ளி இக்கத் புடவை.",
        culturalContext: "தலைமுறை தலைமுறையாக தொடரும் புகழ்பெற்ற தெலுங்கானா கைத்தறி பாரம்பரியம்.",
        visualFeatures: ["துல்லியமான வடிவவியல் கோடுகள்", "இக்கத் நெசவு முறை", "தூய பட்டு பளபளப்பு"]
      },
      kn: {
        craftCategory: "ನೇಯ್ಗೆ",
        craftName: "ಪೋಚಂಪಲ್ಲಿ ಇಕ್ಕತ್",
        productType: "ಸೀರೆ",
        material: "ಶುದ್ಧ ರೇಷ್ಮೆ",
        technique: "ಡಬಲ್ ಇಕ್ಕತ್ ನೇಕಾರಿಕೆ",
        motif: "ಜ್ಯಾಮಿತೀಯ ವಜ್ರಾಕಾರ",
        colors: ["ಕೆಂಪು", "ಅರಿಶಿನ ಹಳದಿ", "ರೇಷ್ಮೆ ಬಿಳಿ"],
        region: "ತೆಲಂಗಾಣ (ಯಾದಾದ್ರಿ ಭುವನಗಿರಿ)",
        description: "ಪಾರಂಪರಿಕ ಮಗ್ಗದಲ್ಲಿ ರೇಷ್ಮೆ ದಾರಗಳಿಂದ ನೇಯ್ದ ಪ್ರಸಿದ್ಧ ಪೋಚಂಪಲ್ಲಿ ಇಕ್ಕತ್ ಸೀರೆ.",
        culturalContext: "ತೆಲಂಗಾಣದ ಐತಿಹಾಸಿಕ ಜವಳಿ ನೇಕಾರಿಕೆ ಕಲೆ.",
        visualFeatures: ["ಜ್ಯಾಮಿತೀಯ ಚಿತ್ರಗಳು", "ಇಕ್ಕತ್ ನೇಯ್ಗೆಯ ವಿನ್ಯಾಸ", "ರೇಷ್ಮೆಯ ನೈಸರ್ಗಿಕ ಕಾಂತಿ"]
      },
      ml: {
        craftCategory: "നെയ്ത്ത്",
        craftName: "പോച്ചമ്പള്ളി ഇക്കത്ത്",
        productType: "സാരി",
        material: "ശുദ്ധമായ പട്ട്",
        technique: "ഡബിൾ ഇക്കത്ത് നെയ്ത്ത്",
        motif: "ജ്യാമിതീയ പാറ്റേണുകൾ",
        colors: ["ചുവപ്പ്", "മഞ്ഞ", "വെള്ള"],
        region: "തെലങ്കാന",
        description: "പരമ്പരാഗത തറിയിൽ അതിമനോഹരമായി നെയ്തെടുത്ത പോച്ചമ്പള്ളി ഇക്കത്ത് പട്ടുസാരി.",
        culturalContext: "തെലങ്കാനയുടെ പാരമ്പര്യ നെയ്ത്തുരീതി.",
        visualFeatures: ["ജ്യാമിതീയ രൂപങ്ങൾ", "ഇക്കത്ത് അതിരുകൾ", "പട്ടിന്റെ തിളക്കം"]
      },
      mr: {
        craftCategory: "विणकाम",
        craftName: "पोचमपल्ली इकत",
        productType: "साडी",
        material: "शुद्ध रेशीम",
        technique: "डबल इकत बांधणी विणकाम",
        motif: "भूमितीय नक्षी",
        colors: ["लाल", "पिवळा", "पांढरा"],
        region: "तेलंगणा",
        description: "पारंपरिक हातमागावर विणलेली प्रसिद्ध पोचमपल्ली इकत रेशमी साडी.",
        culturalContext: "तेलंगणाची जगप्रसिद्ध विणकाम कला.",
        visualFeatures: ["भूमितीय आकृत्या", "इकत पोत", "रेशमी तेज"]
      },
      gu: {
        craftCategory: "વણાટકામ",
        craftName: "પોચમપલ્લી ઇકત",
        productType: "સાડી",
        material: "શુદ્ધ રેશમ",
        technique: "ડબલ ઇકત બાંધણી વણાટ",
        motif: "ભૌમિતિક ભાત",
        colors: ["લાલ", "પીળો", "સફેદ"],
        region: "તેલંગાણા",
        description: "પરંપરાગત સાળ પર હાથેથી વણાયેલી ઉત્કૃષ્ટ પોચમપલ્લી ઇકત રેશમી સાડી.",
        culturalContext: "તેલંગાણાની પ્રાચીન વણાટ વિરાસત.",
        visualFeatures: ["સ્પષ્ટ ભૌમિતિક ડિઝાઇન", "ઇકતની વિશેષતા", "રેશમી ચમક"]
      },
      bn: {
        craftCategory: "বয়ন শিল্প",
        craftName: "পোচমপল্লী ইকত",
        productType: "শাড়ি",
        material: "খাঁটি রেশম",
        technique: "ডাবল ইকত বয়ন",
        motif: "জ্যামিতিক নকশা",
        colors: ["লাল", "হলুদ", "সাদা"],
        region: "তেলেঙ্গানা",
        description: "ঐতিহ্যবাহী তাঁতে বোনা বিখ্যাত পোচমপল্লী ইকত খাঁটি সিল্ক শাড়ি।",
        culturalContext: "তেলেঙ্গানার প্রাচীন লোকশিল্প বয়ন ঐতিহ্য।",
        visualFeatures: ["জ্যামিতিক প্যাটার্ন", "ইকতের বিশেষ নকশা", "রেশমি আভা"]
      },
      or: {
        craftCategory: "ବୁଣାକାର୍ଯ୍ୟ",
        craftName: "ପୋଚମପଲ୍ଲୀ ଇକତ",
        productType: "ଶାଢ଼ୀ",
        material: "ବିଶୁଦ୍ଧ ରେଶମ",
        technique: "ଡବଲ ଇକତ ବୁଣା",
        motif: "ଜ୍ୟାମିତିକ ଚିତ୍ର",
        colors: ["ନାଲି", "ହଳଦିଆ", "ଧଳା"],
        region: "ତେଲେଙ୍ଗାନା",
        description: "ପାରମ୍ପରିକ ତନ୍ତରେ ହାତରେ ବୁଣା ଯାଇଥିବା ପ୍ରସିଦ୍ଧ ପୋଚମପଲ୍ଲୀ ଇକତ ପାଟ ଶାଢ଼ୀ।",
        culturalContext: "ତେଲେଙ୍ଗାନାର ପ୍ରାଚୀନ ହସ୍ତତନ୍ତ ବୁଣାକଳା।",
        visualFeatures: ["ଜ୍ୟାମିତିକ ଆକୃତି", "ଇକତ ବୁଣା ଶୈଳୀ", "ରେଶମ ଚମକ"]
      },
      pa: {
        craftCategory: "ਬੁਣਾਈ",
        craftName: "ਪੋਚਮਪੱਲੀ ਇਕਤ",
        productType: "ਸਾੜ੍ਹੀ",
        material: "ਸ਼ੁੱਧ ਰੇਸ਼ਮ",
        technique: "ਡਬਲ ਇਕਤ ਬੁਣਾਈ",
        motif: "ਜਿਓਮੈਟ੍ਰਿਕ ਡਿਜ਼ਾਈਨ",
        colors: ["ਲਾਲ", "ਪੀਲਾ", "ਚਿੱਟਾ"],
        region: "ਤੇਲੰਗਾਨਾ",
        description: "ਹੱਥ-ਖੱਡੀ 'ਤੇ ਬਣਾਈ ਗਈ ਰਵਾਇਤੀ ਪੋਚਮਪੱਲੀ ਇਕਤ ਰੇਸ਼ਮੀ ਸਾੜ੍ਹੀ।",
        culturalContext: "ਤੇਲੰਗਾਨਾ ਦੀ ਮਸ਼ਹੂਰ ਬੁਣਾਈ ਕਲਾ।",
        visualFeatures: ["ਜਿਓਮੈਟ੍ਰਿਕ ਪੈਟਰਨ", "ਇਕਤ ਬਾਰਡਰ", "ਰੇਸ਼ਮੀ ਕੱਪੜਾ"]
      },
      as: {
        craftCategory: "বয়ন",
        craftName: "পোচমপল্লী ইকৎ",
        productType: "শাড়ী",
        material: "বিশুদ্ধ ৰেচম",
        technique: "ডাবল ইকৎ বয়ন শৈলী",
        motif: "জ্যামিতিক আৰ্হি",
        colors: ["ৰঙা", "হালধীয়া", "বগা"],
        region: "তেলেংগানা",
        description: "তাঁতশালত হাতেৰে বোৱা বিখ্যাত পোচমপল্লী ইকৎ পাটৰ শাড়ী।",
        culturalContext: "তেলেংগানাৰ ঐতিহ্যমণ্ডিত বয়ন শিল্প।",
        visualFeatures: ["জ্যামিতিক ৰূপৰেখা", "ইকৎ শৈলীৰ পাৰি", "ৰেচমী আভা"]
      }
    }
  },

  // 3. Kalamkari
  {
    keywords: ["kalamkari", "machilipatnam", "srikalahasti", "block print", "pen art", "hand painted cotton"],
    canonical: {
      craftCategory: "Textile Art",
      craftName: "Kalamkari",
      productType: "Fabric / Saree",
      material: "Handspun Cotton",
      technique: "Hand-Block Printing & Natural Vegetable Dyeing",
      motif: "Floral Vines & Traditional Tree of Life",
      colors: ["Terracotta Rust", "Indigo Blue", "Mustard Yellow", "Lampblack"],
      region: "Likely Andhra Pradesh",
      description: "Organic cotton textile hand-printed using carved teak wood blocks and washed in flowing river waters with natural plant dyes.",
      culturalContext: "Ancient Indian craft tradition dating back to the Coromandel coast, utilizing exclusively non-toxic organic botanical dyes.",
      visualFeatures: ["Hand-carved block alignment marks", "Natural earthy vegetable dye gradients", "Intricate floral jaal motif"],
      confidence: 0.86,
      uncertainAttributes: ["exact workshop cluster", "block generation era"]
    },
    translations: {
      en: {
        craftCategory: "Textile Art",
        craftName: "Kalamkari",
        productType: "Fabric / Saree",
        material: "Handspun Cotton",
        technique: "Hand-Block Printing & Natural Vegetable Dyeing",
        motif: "Floral Vines & Traditional Tree of Life",
        colors: ["Terracotta Rust", "Indigo Blue", "Mustard Yellow", "Lampblack"],
        region: "Likely Andhra Pradesh",
        description: "Organic cotton textile hand-printed using carved teak wood blocks and washed in flowing river waters with natural plant dyes.",
        culturalContext: "Ancient Indian craft tradition dating back to the Coromandel coast, utilizing exclusively non-toxic organic botanical dyes.",
        visualFeatures: ["Hand-carved block alignment marks", "Natural earthy vegetable dye gradients", "Intricate floral jaal motif"]
      },
      te: {
        craftCategory: "వస్త్ర కళ",
        craftName: "కలంకారి",
        productType: "వస్త్రం / చీర",
        material: "చేనేత పత్తి",
        technique: "చేతి బ్లాక్ ప్రింటింగ్ & సహజ వృక్ష రంగులు",
        motif: "పువ్వుల లతలు & జీవన వృక్షం",
        colors: ["ఇటుక ఎరుపు", "నీలి రంగు", "ఆవాలు పసుపు", "నలుపు"],
        region: "ఆంధ్రప్రదేశ్",
        description: "సహజ సిద్ధమైన రంగులు, టేకు చెక్క అచ్చులతో నది నీటిలో ఉతికి తయారు చేసిన సాంప్రదాయ కలంకారి కాటన్ కళారూపం.",
        culturalContext: "కోస్తా ఆంధ్ర సంస్కృతిలో పుట్టిన ప్రాచీన సహజ రంగుల కళ.",
        visualFeatures: ["చేతి అచ్చు ముద్రల సొగసు", "సహజ రంగుల స్వచ్ఛత", "విశిష్ట పూల లతలు"]
      },
      hi: {
        craftCategory: "वस्त्र कला",
        craftName: "कलमकारी",
        productType: "कपड़ा / साड़ी",
        material: "हाथ से काता हुआ सूती वस्त्र",
        technique: "हस्त-ब्लॉक छपाई एवं प्राकृतिक वानस्पतिक रंग",
        motif: "पारंपरिक लताएं और कल्पवृक्ष",
        colors: ["गेरुआ लाल", "इंडिगो नीला", "पीला", "काला"],
        region: "संभावित आंध्र प्रदेश",
        description: "सागौन की लकड़ी के ठप्पों और प्राकृतिक वनस्पति रंगों से हाथ से तैयार किया गया शुद्ध सूती कलमकारी कपड़ा।",
        culturalContext: "प्राकृतिक रंगों से समृद्ध प्राचीन भारतीय वस्त्र मुद्रण कला।",
        visualFeatures: ["हस्तनिर्मित ब्लॉक की प्राकृतिक छाप", "प्राकृतिक रंगों की गहराई", "पारंपरिक रूपांकन"]
      },
      ta: {
        craftCategory: "துணி ஓவியக் கலை",
        craftName: "கலம்காரி",
        productType: "ஆடை / புடவை",
        material: "கைத்தறி பருத்தி",
        technique: "மர அச்சுப் பதித்தல் மற்றும் இயற்கை வண்ணங்கள்",
        motif: "கொடி மலர்கள் மற்றும் வாழ்வின் மரம்",
        colors: ["மண் சிவப்பு", "நீலம்", "மஞ்சள்", "கருப்பு"],
        region: "ஆந்திரப் பிரதேசம்",
        description: "மரக் கட்டைகளால் இயற்கை தாவர சாயங்களைக் கொண்டு அச்சிடப்பட்ட பாரம்பரிய கலம்காரி பருத்தி ஆடை.",
        culturalContext: "சோழமண்டல கடற்கரையில் தோன்றிய பழமையான இயற்கை வண்ணக் கலை.",
        visualFeatures: ["கைவண்ண அச்சு முத்திரைகள்", "இயற்கை வண்ணப் பொலிவு", "பாரம்பரிய கொடி வடிவங்கள்"]
      },
      kn: {
        craftCategory: "ವಸ್ತ್ರ ಕಲೆ",
        craftName: "ಕಲಂಕಾರಿ",
        productType: "ಬಟ್ಟೆ / ಸೀರೆ",
        material: "ಕೈನೇಯ್ದ ಹತ್ತಿ",
        technique: "ಕೈ ಬ್ಲಾಕ್ ಪ್ರಿಂಟಿಂಗ್ ಮತ್ತು ನೈಸರ್ಗಿಕ ಬಣ್ಣ",
        motif: "ಹೂವಿನ ಬಳ್ಳಿ ಮತ್ತು ಜೀವ ವೃಕ್ಷ",
        colors: ["ಮಣ್ಣಿನ ಕೆಂಪು", "ನೀಲಿ", "ಹಳದಿ", "ಕಪ್ಪು"],
        region: "ಆಂಧ್ರಪ್ರದೇಶ",
        description: "ನೈಸರ್ಗಿಕ ಸಸ್ಯಜನ್ಯ ಬಣ್ಣಗಳು ಮತ್ತು ಮರದ ಅಚ್ಚುಗಳಿಂದ ಮುದ್ರಿಸಲಾದ ಪ್ರಸಿದ್ಧ ಕಲಂಕಾರಿ ಹತ್ತಿ ಬಟ್ಟೆ.",
        culturalContext: "ದಕ್ಷಿಣ ಭಾರತದ ಪ್ರಾಚೀನ ನೈಸರ್ಗಿಕ ಬಣ್ಣದ ವಸ್ತ್ರಕಲೆ.",
        visualFeatures: ["ಕೈ ಅಚ್ಚಿನ ನೈಸರ್ಗಿಕ ಗುರುತುಗಳು", "ಸಾವಯವ ಬಣ್ಣಗಳ ಆಕರ್ಷಣೆ"]
      },
      ml: {
        craftCategory: "ടെക്സ്റ്റൈൽ കല",
        craftName: "കലങ്കാരി",
        productType: "തുണിത്തരങ്ങൾ / സാരി",
        material: "കൈത്തറി കോട്ടൺ",
        technique: "ബ്ലോക്ക് പ്രിന്റിംഗ് & പ്രകൃതിദത്ത ചായങ്ങൾ",
        motif: "പൂവള്ളികളും ജീവവൃക്ഷവും",
        colors: ["ചുവപ്പ്", "നീല", "മഞ്ഞ", "കറുപ്പ്"],
        region: "ആന്ധ്രാപ്രദേശ്",
        description: "തേക്ക് തടികൊണ്ടുണ്ടാക്കിയ അച്ചുകളും പ്രകൃതിദത്ത ചായങ്ങളും ഉപയോഗിച്ച് നിർമ്മിച്ച കലങ്കാരി തുണി.",
        culturalContext: "ഭാരതീയ പ്രകൃതിദത്ത ചായക്കൂട്ടുകളുടെ പൈതൃകം.",
        visualFeatures: ["തനതായ ബ്ലോക്ക് പ്രിന്റ്", "പ്രകൃതിദത്ത വർണ്ണങ്ങൾ"]
      },
      mr: {
        craftCategory: "वस्त्रकला",
        craftName: "कलमकारी",
        productType: "कापड / साडी",
        material: "हातकाती सुती कापड",
        technique: "लाकडी ठसा छपाई आणि नैसर्गिक रंग",
        motif: "फुलांची वेल आणि जीवनवृक्ष",
        colors: ["गेरू लाल", "निळा", "पिवळा", "काळा"],
        region: "आंध्र प्रदेश",
        description: "सागवानी लाकडी ठशांनी आणि नैसर्गिक वनस्पती रंगांनी सजवलेले कलमकारी कापड.",
        culturalContext: "भारतातील प्राचीन नैसर्गिक वस्त्र छपाई परंपरा.",
        visualFeatures: ["हाताने उमटवलेले ठसे", "नैसर्गिक रंगछटा"]
      },
      gu: {
        craftCategory: "વસ્ત્રકળા",
        craftName: "કલમકારી",
        productType: "કાપડ / સાડી",
        material: "હાથકંતેલ સુતરાઉ કાપડ",
        technique: "બ્લોક પ્રિન્ટિંગ અને કુદરતી રંગકામ",
        motif: "વેલબુટ્ટા અને વૃક્ષની ભાત",
        colors: ["લાલ", "વાદળી", "પીળો", "કાળો"],
        region: "આંધ્રપ્રદેશ",
        description: "લાકડાના બીબાં અને વનસ્પતિ રંગો વડે તૈયાર કરાયેલ પરંપરાગત કલમકારી કાપડ.",
        culturalContext: "કુદરતી રંગોથી સમૃદ્ધ ભારતીય કાપડ કળા.",
        visualFeatures: ["હાથથી છાપેલ બીબાંની ભાત", "ઓર્ગેનિક રંગોની શોભા"]
      },
      bn: {
        craftCategory: "বস্ত্রশিল্প",
        craftName: "কলমকারী",
        productType: "পোশাক / শাড়ি",
        material: "হাতে বোনা সুতি",
        technique: "কাঠের ব্লক প্রিন্ট ও প্রাকৃতিক রং",
        motif: "ফুল-লতা ও কল্পবৃক্ষ",
        colors: ["মেটে লাল", "নীল", "হলুদ", "কালো"],
        region: "অন্ধ্রপ্রদেশ",
        description: "গাছের প্রাকৃতিক রঙে এবং কাঠের ব্লকের সাহায্যে তৈরি ঐতিহ্যবাহী কলমকারী বস্ত্র।",
        culturalContext: "ভারতের সুপ্রাচীন প্রাকৃতিক ছাপা বস্ত্রশিল্পের ঐতিহ্য।",
        visualFeatures: ["হাতে ছাপার নিখুঁত কাজ", "প্রাকৃতিক মাটির রং"]
      },
      or: {
        craftCategory: "ବସ୍ତ୍ରକଳା",
        craftName: "କଲମକାରୀ",
        productType: "ବସ୍ତ୍ର / ଶାଢ଼ୀ",
        material: "ହସ୍ତବୁଣା ସୂତା",
        technique: "କାଠ ବ୍ଲକ ଛାପା ଓ ପ୍ରାକୃତିକ ରଙ୍ଗ",
        motif: "ଲତା ଓ ଜୀବନ ବୃକ୍ଷ",
        colors: ["ଗେରୁଆ ନାଲି", "ନୀଳ", "ହଳଦିଆ", "କଳା"],
        region: "ଆନ୍ଧ୍ରପ୍ରଦେଶ",
        description: "କାଠର ଛାଞ୍ଚ ଓ ଗଛଲତାର ପ୍ରାକୃତିକ ରଙ୍ଗରେ ତିଆରି ହୋଇଥିବା କଲମକାରୀ କପଡ଼ା।",
        culturalContext: "ପ୍ରାଚୀନ ଭାରତୀୟ ପ୍ରାକୃତିକ ରଙ୍ଗର ବସ୍ତ୍ରକଳା।",
        visualFeatures: ["ହସ୍ତନିର୍ମିତ ଛାପା କଳା", "ପ୍ରାକୃତିକ ରଙ୍ଗର ମନୋରମ ଛଟା"]
      },
      pa: {
        craftCategory: "ਕੱਪੜਾ ਕਲਾ",
        craftName: "ਕਲਮਕਾਰੀ",
        productType: "ਕੱਪੜਾ / ਸਾੜ੍ਹੀ",
        material: "ਸੂਤੀ ਕੱਪੜਾ",
        technique: "ਬਲਾਕ ਛਪਾਈ ਅਤੇ ਕੁਦਰਤੀ ਰੰਗ",
        motif: "ਵੇਲਾਂ ਅਤੇ ਜੀਵਨ ਰੁੱਖ",
        colors: ["ਗੇਰੂਆ ਲਾਲ", "ਨੀਲਾ", "ਪੀਲਾ", "ਕਾਲਾ"],
        region: "ਆਂਧਰਾ ਪ੍ਰਦੇਸ਼",
        description: "ਲੱਕੜ ਦੇ ਠੱਪਿਆਂ ਅਤੇ ਕੁਦਰਤੀ ਬਨਸਪਤੀ ਰੰਗਾਂ ਨਾਲ ਤਿਆਰ ਕੀਤਾ ਕਲਮਕਾਰੀ ਕੱਪੜਾ।",
        culturalContext: "ਭਾਰਤ ਦੀ ਪ੍ਰਾਚੀਨ ਕੁਦਰਤੀ ਰੰਗਾਂ ਵਾਲੀ ਛਪਾਈ ਕਲਾ।",
        visualFeatures: ["ਹੱਥੀਂ ਛਪਾਈ ਦੇ ਨਿਸ਼ਾਨ", "ਕੁਦਰਤੀ ਰੰਗਾਂ ਦਾ ਸੁਹੱਪਣ"]
      },
      as: {
        craftCategory: "বস্ত্রশিল্প",
        craftName: "কলমকাৰী",
        productType: "পোছাক / শাড়ী",
        material: "হাতে বোৱা কপাহী সূতা",
        technique: "কাঠৰ ব্লকত প্ৰাকৃতিক ৰং ছপা",
        motif: "ফুলৰ লতা আৰু জীৱন বৃক্ষ",
        colors: ["গেৰুৱা ৰঙা", "নীলা", "হালধীয়া", "কলা"],
        region: "অন্ধ্ৰপ্ৰদেশ",
        description: "কাঠৰ ব্লকত প্ৰাকৃতিক গছ-লতাৰ ৰঙেৰে ছপা কৰা ঐতিহ্যমণ্ডিত কলমকাৰী কাপোৰ।",
        culturalContext: "প্ৰাচীন ভাৰতীয় প্ৰাকৃতিক ৰং ব্যৱহাৰৰ এক অনুপম শিল্প।",
        visualFeatures: ["হাতেৰে কটা ব্লকৰ ছাঁপ", "প্ৰাকৃতিক ৰঙৰ গাঢ়তা"]
      }
    }
  },

  // 4. Wooden toy (Channapatna)
  {
    keywords: ["channapatna", "wooden toy", "lacquerware", "stacker", "ivory wood", "ramanagara", "wooden craft"],
    canonical: {
      craftCategory: "Woodcraft",
      craftName: "Channapatna Turned Lacquerware",
      productType: "Lacquered Wooden Toy",
      material: "Ivory Wood (Wrightia Tinctoria)",
      technique: "Lathe Turning & Friction-Burnished Natural Lacquer",
      motif: "Concentric Circles & Harmonic Cylinders",
      colors: ["Turmeric Yellow", "Sindoor Red", "Leaf Green"],
      region: "Likely Karnataka (Channapatna)",
      description: "Lathe-turned smooth wooden toy crafted from sustainably harvested ivory wood and hand-burnished with non-toxic natural vegetable lacquers.",
      culturalContext: "Celebrated craft legacy of Karnataka's 'Gombegala Ooru' (Toy Town), completely baby-safe with rounded edges.",
      visualFeatures: ["Glossy natural lacquer sheen from palm friction", "Turned wood radial symmetry", "Zero synthetic paints"],
      confidence: 0.91,
      uncertainAttributes: ["artisan cooperative"]
    },
    translations: {
      en: {
        craftCategory: "Woodcraft",
        craftName: "Channapatna Turned Lacquerware",
        productType: "Lacquered Wooden Toy",
        material: "Ivory Wood (Wrightia Tinctoria)",
        technique: "Lathe Turning & Friction-Burnished Natural Lacquer",
        motif: "Concentric Circles & Harmonic Cylinders",
        colors: ["Turmeric Yellow", "Sindoor Red", "Leaf Green"],
        region: "Likely Karnataka (Channapatna)",
        description: "Lathe-turned smooth wooden toy crafted from sustainably harvested ivory wood and hand-burnished with non-toxic natural vegetable lacquers.",
        culturalContext: "Celebrated craft legacy of Karnataka's 'Gombegala Ooru' (Toy Town), completely baby-safe with rounded edges.",
        visualFeatures: ["Glossy natural lacquer sheen from palm friction", "Turned wood radial symmetry", "Zero synthetic paints"]
      },
      kn: {
        craftCategory: "ಮರದ ಕೆತ್ತನೆ",
        craftName: "ಚನ್ನಪಟ್ಟಣ ಆಟಿಕೆ",
        productType: "ಮರದ ಆಟಿಕೆ",
        material: "ಹಾಲೆ ಮರ (ಐವರಿ ವುಡ್)",
        technique: "ಲೇತ್ ತಿರುಗಣೆ ಮತ್ತು ನೈಸರ್ಗಿಕ ಅರಗು ಹೊಳಪು",
        motif: "ವರ್ತುಲಾಕಾರದ ಬಳೆಗಳು",
        colors: ["ಅರಿಶಿನ ಹಳದಿ", "ಸಿಂಧೂರ ಕೆಂಪು", "ಹಸಿರು"],
        region: "ಕರ್ನಾಟಕ (ಚನ್ನಪಟ್ಟಣ)",
        description: "ವಿಷಕಾರಿಯಲ್ಲದ ನೈಸರ್ಗಿಕ ಸಸ್ಯಜನ್ಯ ಬಣ್ಣಗಳು ಮತ್ತು ಮೃದುವಾದ ಹಾಲೆ ಮರದಿಂದ ಮಾಡಿದ ಸಾಂಪ್ರದಾಯಿಕ ಚನ್ನಪಟ್ಟಣ ಆಟಿಕೆ.",
        culturalContext: "ಕರ್ನಾಟಕದ ಹೆಮ್ಮೆಯ ಗೊಂಬೆಗಳ ಊರಿನ ಐತಿಹಾಸಿಕ ಕಲೆ.",
        visualFeatures: ["ನೈಸರ್ಗಿಕ ಅರಗಿನ ಹೊಳಪು", "ಮಕ್ಕಳಿಗೆ ಸುರಕ್ಷಿತ ನಯವಾದ ಅಂಚುಗಳು", "ಶೂನ್ಯ ರಾಸಾಯನಿಕ"]
      },
      te: {
        craftCategory: "చెక్క కళ",
        craftName: "చన్నపట్న చెక్క బొమ్మలు",
        productType: "చెక్క బొమ్మ",
        material: "మృదువైన అంకుడు చెక్క (ఐవరీ వుడ్)",
        technique: "లేత్ టర్నింగ్ & సహజ లాకర్ పాలిష్",
        motif: "గుండ్రని వలయాలు",
        colors: ["పసుపు", "సిందూర ఎరుపు", "ఆకుపచ్చ"],
        region: "కర్ణాటక (చన్నపట్న)",
        description: "సహజమైన కూరగాయల రంగులతో లేత్ యంత్రంపై చేతితో తిప్పి తయారు చేసిన సురక్షితమైన చన్నపట్న చెక్క బొమ్మ.",
        culturalContext: "దక్షిణ భారతదేశ ప్రసిద్ధ సాంప్రదాయ చెక్క బొమ్మల వారసత్వం.",
        visualFeatures: ["సహజ లాకర్ నిగారింపు", "పిల్లలకు సురక్షితమైన గుండ్రని అంచులు"]
      },
      hi: {
        craftCategory: "काष्ठ शिल्प",
        craftName: "चन्नापटना खिलौना",
        productType: "लकड़ी का खिलौना",
        material: "आइवरी वुड (आले मारा)",
        technique: "खराद पर नक्काशी एवं प्राकृतिक लाख वार्निश",
        motif: "गोलाकार रिंग्स",
        colors: ["हल्दी पीला", "सिंदूर लाल", "पत्ता हरा"],
        region: "कर्नाटक (चन्नापटना)",
        description: "प्राकृतिक वनस्पति रंगों से पॉलिश किया गया गैर-विषाक्त सुरक्षित लकड़ी का खिलौना।",
        culturalContext: "कर्नाटक के खिलौना शहर की विश्व प्रसिद्ध पारंपरिक शिल्पकला।",
        visualFeatures: ["प्राकृतिक लाख की चमकदार सतह", "बच्चों के लिए पूर्णतः सुरक्षित गोल किनारे"]
      },
      ta: {
        craftCategory: "மரக் கைவினை",
        craftName: "சன்னபட்னா மரப் பொம்மைகள்",
        productType: "மரப் பொம்மை",
        material: "ஐவரி மரம்",
        technique: "லேத் கடைசல் மற்றும் இயற்கை அரக்கு பாலிஷ்",
        motif: "வட்ட வடிவ வளையங்கள்",
        colors: ["மஞ்சள்", "சிவப்பு", "பச்சை"],
        region: "கர்நாடகா (சன்னபட்னா)",
        description: "குழந்தைகளுக்கு பாதுகாப்பான இயற்கை தாவர வண்ணங்களால் வர்ணம் பூசப்பட்ட பாரம்பரிய சன்னபட்னா மரப் பொம்மை.",
        culturalContext: "தென்னிந்தியாவின் பாரம்பரிய மர பொம்மை நகரம்.",
        visualFeatures: ["இயற்கை அரக்கு பளபளப்பு", "மென்மையான உருளை விளிம்புகள்"]
      },
      ml: {
        craftCategory: "തടിപ്പണി",
        craftName: "ചന്നപട്ടണ തടി കളിപ്പാട്ടങ്ങൾ",
        productType: "തടി കളിപ്പാട്ടം",
        material: "ഐവറി വുഡ്",
        technique: "ലേത്ത് ടേണിംഗും പ്രകൃതിദത്ത ലാക്കറും",
        motif: "വൃത്താകൃതിയിലുള്ള വളയങ്ങൾ",
        colors: ["മഞ്ഞ", "ചുവപ്പ്", "പച്ച"],
        region: "കർണാടക (ചന്നപട്ടണ)",
        description: "കുട്ടികൾക്ക് സുരക്ഷിതമായ പ്രകൃതിദത്ത നിറങ്ങൾ നൽകിയ മനോഹരമായ ചന്നപട്ടണ തടി കളിപ്പാട്ടം.",
        culturalContext: "കളിപ്പാട്ടങ്ങളുടെ നാടായ കർണാടകയിലെ ചന്നപട്ടണത്തിന്റെ പാരമ്പര്യം.",
        visualFeatures: ["ലാക്കർ തിളക്കം", "സുരക്ഷിതമായ ഉരുണ്ട അരികുകൾ"]
      },
      mr: {
        craftCategory: "लाकूडकाम",
        craftName: "चन्नापटना लाकडी खेळणी",
        productType: "लाकडी खेळणे",
        material: "आइव्हरी वूड",
        technique: "खराद काम आणि नैसर्गिक लाख पॉलिश",
        motif: "गोलाकार कडे",
        colors: ["पिवळा", "लाल", "हिरवा"],
        region: "कर्नाटक (चन्नापटना)",
        description: "लहान मुलांसाठी सुरक्षित, विषमुक्त वनस्पती रंगांनी पॉलिश केलेले चन्नापटना लाकडी खेळणे.",
        culturalContext: "कर्नाटकातील ऐतिहासिक खेळण्यांचे शहर.",
        visualFeatures: ["चमकदार लाख मुलामा", "गुळगुळीत कडा"]
      },
      gu: {
        craftCategory: "લાકડાકામ",
        craftName: "ચન્નાપટણા લાકડાના રમકડાં",
        productType: "લાકડાનું રમકડું",
        material: "આઇવરી વુડ",
        technique: "ખરાદી કામ અને કુદરતી લાખનું પોલિશ",
        motif: "ગોળાકાર વલયો",
        colors: ["પીળો", "લાલ", "લીલો"],
        region: "કર્ણાટક (ચન્નાપટણા)",
        description: "બાળકો માટે સંપૂર્ણ સુરક્ષિત, કુદરતી વનસ્પતિ રંગોથી મઢેલું ચન્નાપટણા રમકડું.",
        culturalContext: "રમકડાંના નગર તરીકે જાણીતા કર્ણાટકનું વિશિષ્ટ શિલ્પ.",
        visualFeatures: ["કુદરતી લાખની ચમક", "ગોળ સુંવાળી કિનારીઓ"]
      },
      bn: {
        craftCategory: "কাষ্ঠশিল্প",
        craftName: "চন্নাপাটনা কাঠের খেলনা",
        productType: "কাঠের খেলনা",
        material: "আইভরি কাঠ",
        technique: "লেদ টার্নিং ও প্রাকৃতিক লাক্ষার প্রলেপ",
        motif: "গোলাকার বলয়",
        colors: ["হলুদ", "লাল", "সবুজ"],
        region: "কর্ণাটক (চন্নাপাটনা)",
        description: "শিশুদের জন্য নিরাপদ ভেষজ রঙে চকচকে প্রলেপ দেওয়া চন্নাপাটনার বিখ্যাত কাঠের খেলনা।",
        culturalContext: "কর্ণাটকের পুতুল নগরের শতবর্ষের ঐতিহ্যবাহী কাঠের শিল্প।",
        visualFeatures: ["চকচকে প্রাকৃতিক পালিশ", "নিরাপদ মসৃণ ধার"]
      },
      or: {
        craftCategory: "କାଠ କାର୍ଯ୍ୟ",
        craftName: "ଚନ୍ନାପାଟଣା କାଠ ଖେଳଣା",
        productType: "କାଠ ଖେଳଣା",
        material: "ଆଇଭରି କାଠ",
        technique: "ଖରାଦ କାମ ଓ ପ୍ରାକୃତିକ ଲାଖ ପଲିସ୍",
        motif: "ଗୋଲାକାର ରିଙ୍ଗ୍",
        colors: ["ହଳଦିଆ", "ନାଲି", "ସବୁଜ"],
        region: "କର୍ଣ୍ଣାଟକ (ଚନ୍ନାପାଟଣା)",
        description: "ପିଲାଙ୍କ ପାଇଁ ନିରାପଦ ପ୍ରାକୃତିକ ରଙ୍ଗରେ ଝଟକୁଥିବା ପାରମ୍ପରିକ ଚନ୍ନାପାଟଣା କାଠ ଖେଳଣା।",
        culturalContext: "କର୍ଣ୍ଣାଟକର ଖେଳଣା ସହରର ସୁପ୍ରସିଦ୍ଧ ହସ୍ତଶିଳ୍ପ।",
        visualFeatures: ["ଚମକଦାର ଲାଖ ପ୍ରଲେପ", "ସୁନ୍ଦର ଗୋଲାକାର ଧାର"]
      },
      pa: {
        craftCategory: "ਲੱਕੜ ਦਾ ਕੰਮ",
        craftName: "ਚੰਨਾਪਟਨਾ ਲੱਕੜ ਦੇ ਖਿਡੌਣੇ",
        productType: "ਲੱਕੜ ਦਾ ਖਿਡੌਣਾ",
        material: "ਆਈਵਰੀ ਲੱਕੜ",
        technique: "ਖਰਾਦ ਕੰਮ ਅਤੇ ਕੁਦਰਤੀ ਲਾਖ ਪਾਲਿਸ਼",
        motif: "ਗੋਲ ਚੱਕਰ",
        colors: ["ਪੀਲਾ", "ਲਾਲ", "ਹਰਾ"],
        region: "ਕਰਨਾਟਕ (ਚੰਨਾਪਟਨਾ)",
        description: "ਬੱਚਿਆਂ ਲਈ ਪੂਰੀ ਤਰ੍ਹਾਂ ਸੁਰੱਖਿਅਤ ਕੁਦਰਤੀ ਰੰਗਾਂ ਨਾਲ ਤਿਆਰ ਲੱਕੜ ਦਾ ਖਿਡੌਣਾ।",
        culturalContext: "ਕਰਨਾਟਕ ਦੇ ਖਿਡੌਣਾ ਨਗਰ ਦੀ ਮਸ਼ਹੂਰ ਦਸਤਕਾਰੀ।",
        visualFeatures: ["ਲਾਖ ਦੀ ਕੁਦਰਤੀ ਚਮਕ", "ਸੁਰੱਖਿਅਤ ਗੋਲ ਕਿਨਾਰੇ"]
      },
      as: {
        craftCategory: "কাঠশিল্প",
        craftName: "চন্নপাটনা কাঠৰ খেলনা",
        productType: "কাঠৰ খেলনা",
        material: "আইভৰি কাঠ",
        technique: "লেথ টাৰ্নিং আৰু প্ৰাকৃতিক লা পলিচ",
        motif: "বৃত্তাকাৰ আঙুঠি",
        colors: ["হালধীয়া", "ৰঙা", "সেউজীয়া"],
        region: "কৰ্ণাটক (চন্নপাটনা)",
        description: "শিশুৰ বাবে সম্পূৰ্ণ নিৰাপদ প্ৰাকৃতিক ৰঙেৰে তিৰবিৰাই থকা চন্নপাটনা কাঠৰ পুতলা।",
        culturalContext: "কৰ্ণাটকৰ পুতলা নগৰীৰ বিখ্যাত হস্তশিল্প।",
        visualFeatures: ["প্ৰাকৃতিক লাৰ উজ্জ্বলতা", "মৃদু মসৃণ কাষ"]
      }
    }
  },

  // 5. Pottery (Jaipur Blue Pottery / Terracotta)
  {
    keywords: ["blue pottery", "jaipur pottery", "quartz", "ceramic vase", "clay pot", "terracotta", "pottery"],
    canonical: {
      craftCategory: "Pottery",
      craftName: "Jaipur Blue Pottery",
      productType: "Decorative Ceramic Vase",
      material: "Ground Quartz Stone, Fuller's Earth & Natural Gum (Clay-Free)",
      technique: "Open Mold Dough Shaping & Low-Fire Kiln Oxide Glazing",
      motif: "Persian Floral Arabesque & Lotus Petals",
      colors: ["Cobalt Blue", "Turquoise", "Pristine White"],
      region: "Likely Rajasthan (Jaipur)",
      description: "Clay-free handmade ceramic shaped from ground quartz stone dough, hand-painted with cobalt blue mineral oxides, and fired with a glossy vitreous glaze.",
      culturalContext: "Historic Turko-Persian craft lineage patronized by the Jaipur royal courts, unique among world ceramics for using zero clay.",
      visualFeatures: ["Vivid cobalt and turquoise glaze", "Fine under-glaze brushwork", "Slight surface craze characteristic of low-fire quartz"],
      confidence: 0.90,
      uncertainAttributes: ["kiln firing batch"]
    },
    translations: {
      en: {
        craftCategory: "Pottery",
        craftName: "Jaipur Blue Pottery",
        productType: "Decorative Ceramic Vase",
        material: "Ground Quartz Stone, Fuller's Earth & Natural Gum (Clay-Free)",
        technique: "Open Mold Dough Shaping & Low-Fire Kiln Oxide Glazing",
        motif: "Persian Floral Arabesque & Lotus Petals",
        colors: ["Cobalt Blue", "Turquoise", "Pristine White"],
        region: "Likely Rajasthan (Jaipur)",
        description: "Clay-free handmade ceramic shaped from ground quartz stone dough, hand-painted with cobalt blue mineral oxides, and fired with a glossy vitreous glaze.",
        culturalContext: "Historic Turko-Persian craft lineage patronized by the Jaipur royal courts, unique among world ceramics for using zero clay.",
        visualFeatures: ["Vivid cobalt and turquoise glaze", "Fine under-glaze brushwork", "Slight surface craze characteristic of low-fire quartz"]
      },
      hi: {
        craftCategory: "मृत्तिका शिल्प",
        craftName: "जयपुर ब्लू पॉटरी",
        productType: "सजावटी सिरेमिक फूलदान",
        material: "पिसा हुआ क्वार्ट्ज पत्थर, मुल्तानी मिट्टी एवं गोंद (बिना मिट्टी)",
        technique: "खुले सांचे में ढलाई एवं खनिज ऑक्साइड मीनाकारी",
        motif: "पारंपरिक फारसी फूल-पत्तियां और कमल",
        colors: ["कोबाल्ट नीला", "फिरोजी", "सफेद"],
        region: "राजस्थान (जयपुर)",
        description: "क्वार्ट्ज पत्थर के चूर्ण से बिना सामान्य मिट्टी के तैयार किया गया, हाथ से रंगा हुआ जयपुरी ब्लू पॉटरी फूलदान।",
        culturalContext: "जयपुर के राजघराने द्वारा पोषित ऐतिहासिक खनिज पॉटरी परंपरा।",
        visualFeatures: ["गहरा कोबाल्ट और फिरोजी रंग", "हाथ की महीन चित्रकारी", "चमकदार खनिज चमक"]
      },
      te: {
        craftCategory: "మట్టి / పింగాణీ కళ",
        craftName: "జైపూర్ బ్లూ పాట్టరీ",
        productType: "అలంకరణ పూలకుండీ",
        material: "క్వార్ట్జ్ రాయి పొడి & ఖనిజ మిశ్రమం (మట్టి లేని కళ)",
        technique: "మోల్డ్ ప్రెస్సింగ్ & ఖనిజ రంగుల గ్లేజింగ్",
        motif: "పువ్వుల ఆకృతులు & తామర రేకులు",
        colors: ["కోబాల్ట్ నీలం", "మణి నీలం", "తెలుపు"],
        region: "రాజస్థాన్ (జైపూర్)",
        description: "సాధారణ మట్టి లేకుండా కేవలం క్వార్ట్జ్ రాయి మిశ్రమంతో చేతితో తీర్చిదిద్దిన అరుదైన జైపూర్ బ్లూ పాట్టరీ కళాఖండం.",
        culturalContext: "రాజస్థాన్ రాజవంశాల ఆదరణ పొందిన చారిత్రక హస్తకళ.",
        visualFeatures: ["సహజ నీలిరంగు మెరుపు", "చేతితో వేసిన అందమైన పూల డిజైన్లు"]
      },
      ta: {
        craftCategory: "மட்பாண்டக் கலை",
        craftName: "ஜெய்ப்பூர் நீல மட்பாண்டம்",
        productType: "பீங்கான் மலர்க்குவளை",
        material: "குவார்ட்ஸ் கல் பொடி மற்றும் களிமண் கலவை",
        technique: "கைவண்ண அச்சு மற்றும் தாதுக் கண்ணாடிப் பூச்சு",
        motif: "பாரசீக மலர் வேலைப்பாடு",
        colors: ["அடர் நீலம்", "நீலப்பச்சை", "வெள்ளை"],
        region: "ராஜஸ்தான் (ஜெய்ப்பூர்)",
        description: "குவார்ட்ஸ் கல் துகள்களால் செய்யப்பட்டு நீல நிற தாது வண்ணங்களால் வரையப்பட்ட புகழ்பெற்ற ஜெய்ப்பூர் மட்பாண்டப் பொருள்.",
        culturalContext: "ஜெய்ப்பூர் அரச குடும்பத்தாரால் ஆதரிக்கப்பட்ட வரலாற்றுச் சிறப்புமிக்க கலை.",
        visualFeatures: ["கண்ணாடி போன்ற நீல பளபளப்பு", "நுணுக்கமான கை தூரிகை ஓவியம்"]
      },
      kn: {
        craftCategory: "ಮಡಕೆ ಕಲೆ",
        craftName: "ಜೈಪುರ ಬ್ಲೂ ಪಾಟರಿ",
        productType: "ಅಲಂಕಾರಿಕ ಹೂದಾನಿ",
        material: "ಕ್ವಾರ್ಟ್ಜ್ ಪುಡಿ ಮತ್ತು ನೈಸರ್ಗಿಕ ಜೇಡಿಮಣ್ಣು",
        technique: "ಮೋಲ್ಡ್ ಆಕಾರ ಮತ್ತು ಖನಿಜ ಹೊಳಪು",
        motif: "ಕಮಲ ಮತ್ತು ಪರ್ಷಿಯನ್ ಹೂವುಗಳು",
        colors: ["ನೀಲಿ", "ತಿಳಿ ನೀಲಿ", "ಬಿಳಿ"],
        region: "ರಾಜಸ್ಥಾನ (ಜೈಪುರ)",
        description: "ಕ್ವಾರ್ಟ್ಜ್ ಕಲ್ಲಿನಿಂದ ಕೈಯಿಂದ ಮಾಡಿದ ಸುಂದರವಾದ ಜೈಪುರ ಬ್ಲೂ ಪಾಟರಿ ಹೂದಾನಿ.",
        culturalContext: "ರಾಜಸ್ಥಾನದ ರಾಜಮನೆತನದ ಪ್ರಸಿದ್ಧ ಕರಕುಶಲ ಕಲೆ.",
        visualFeatures: ["ಆಕರ್ಷಕ ನೀಲಿ ಮೆರುಗು", "ಕೈಬರಹದ ನಯವಾದ ಚಿತ್ರಕಲೆ"]
      },
      ml: {
        craftCategory: "മൺപാത്ര നിർമ്മാണം",
        craftName: "ജയ്പൂർ ബ്ലൂ പോട്ടറി",
        productType: "സെറാമിക് പാത്രം",
        material: "ക്വാർട്സ് പൊടിയും പ്രകൃതിദത്ത കൂട്ടുകളും",
        technique: "മോൾഡ് ഷേപ്പിംഗും മിനറൽ ഗ്ലേസിംഗും",
        motif: "പൂക്കളുടെ ഡിസൈനുകൾ",
        colors: ["കോബാൾട്ട് നീല", "വെള്ള"],
        region: "രാജസ്ഥാൻ",
        description: "ക്വാർട്സ് കല്ല് പൊടിച്ച് കൈകൊണ്ട് രൂപപ്പെടുത്തിയ പ്രശസ്തമായ ജയ്പൂർ നീല സെറാമിക് കല.",
        culturalContext: "രാജസ്ഥാനിലെ രാജകീയ പാരമ്പര്യമുള്ള കരകൗശലവിദ്യ.",
        visualFeatures: ["നീലനിറത്തിലെ തിളക്കം", "സൂക്ഷ്മമായ ചിത്രപ്പണികൾ"]
      },
      mr: {
        craftCategory: "कुंभारकाम",
        craftName: "जयपूर ब्लू पॉटरी",
        productType: "सिरेमिक फुलदाणी",
        material: "क्वार्ट्झ पावडर आणि खनिजे",
        technique: "मोल्ड घडणावळ आणि ऑक्साइड चमक",
        motif: "कमळाची फुले आणि नक्षी",
        colors: ["निळा", "फिकट निळा", "पांढरा"],
        region: "राजस्थान (जयपूर)",
        description: "मातीशिवाय क्वार्ट्झ दगडाच्या भुकटीने बनवलेली जयपूरची प्रसिद्ध निळी पॉटरी.",
        culturalContext: "जयपूरच्या राजघराण्याने जोपासलेली ऐतिहासिक कला.",
        visualFeatures: ["गडद निळी चकचकीत चकाकी", "हाताने काढलेली वेलबुट्टी"]
      },
      gu: {
        craftCategory: "માટીકામ",
        craftName: "જયપુર બ્લુ પોટરી",
        productType: "સિરામિક કૂંજો",
        material: "ક્વાર્ટ્ઝ પાવડર અને મુલતાની માટી",
        technique: "મોલ્ડ આકાર અને ગ્લેઝિંગ",
        motif: "કમળ અને ફૂલવેલ",
        colors: ["ઘેરો વાદળી", "આકાશી", "સફેદ"],
        region: "રાજસ્થાન (જયપુર)",
        description: "સામાન્ય માટી વિના ક્વાર્ટ્ઝથી હાથ વડે ઘડેલી જયપુરની વિશ્વવિખ્યાત બ્લુ પોટરી.",
        culturalContext: "જયપુરના રાજાઓ દ્વારા પોષિત પરંપરાગત હસ્તકલા.",
        visualFeatures: ["ચળકતી વાદળી સપાટી", "બારીક ચિત્રકામ"]
      },
      bn: {
        craftCategory: "মৃৎশিল্প",
        craftName: "জয়পুর ব্লু পটারি",
        productType: "সিরামিক ফুলদানি",
        material: "কোয়ার্টজ পাথর গুঁড়ো ও প্রাকৃতিক আঠা",
        technique: "হাতে গড়া ও অক্সাইড প্রলেপ",
        motif: "পদ্ম ও পারস্য নকশা",
        colors: ["গাঢ় নীল", "ফিরোজা", "সাদা"],
        region: "রাজস্থান (জয়পুর)",
        description: "মাটি ছাড়া কেবল কোয়ার্টজ গুঁড়ো দিয়ে হাতে গড়া জয়পুরের বিখ্যাত ব্লু পটারি ফুলদানি।",
        culturalContext: "জয়পুরের রাজকীয় ঐতিহ্যের অন্যতম শ্রেষ্ঠ নিদর্শন।",
        visualFeatures: ["উজ্জ্বল নীল কাঁচের মতো দীপ্তি", "সূক্ষ্ম হাতের তুলির কাজ"]
      },
      or: {
        craftCategory: "ମାଟିପାତ୍ର କଳା",
        craftName: "ଜୟପୁର ବ୍ଲୁ ପଟେରୀ",
        productType: "ସେରାମିକ ଫୁଲଦାନୀ",
        material: "କ୍ୱାର୍ଟଜ୍ ପଥର ଗୁଣ୍ଡ ଓ ଖଣିଜ ରଙ୍ଗ",
        technique: "ହସ୍ତନିର୍ମିତ ଛାଞ୍ଚ ଓ ଚମକଦାର ପଲିସ୍",
        motif: "ପଦ୍ମ ଓ ଲତା",
        colors: ["ଗାଢ଼ ନୀଳ", "ଆକାଶୀ", "ଧଳା"],
        region: "ରାଜସ୍ଥାନ (ଜୟପୁର)",
        description: "କ୍ୱାର୍ଟଜ୍ ପଥରରୁ ହାତରେ ଗଢ଼ା ଯାଇଥିବା ରାଜସ୍ଥାନର ପ୍ରସିଦ୍ଧ ଜୟପୁର ବ୍ଲୁ ପଟେରୀ।",
        culturalContext: "ଜୟପୁର ରାଜଦରବାରର ଐତିହାସିକ କାରୁକାର୍ଯ୍ୟ।",
        visualFeatures: ["ଚମକଦାର ନୀଳ ଆଭା", "ସୂକ୍ଷ୍ମ ହସ୍ତଚିତ୍ର"]
      },
      pa: {
        craftCategory: "ਮਿੱਟੀ ਦੇ ਭਾਂਡੇ",
        craftName: "ਜੈਪੁਰ ਬਲੂ ਪੌਟਰੀ",
        productType: "ਸਜਾਵਟੀ ਫੁੱਲਦਾਨ",
        material: "ਕੁਆਰਟਜ਼ ਪੱਥਰ ਦਾ ਚੂਰਾ",
        technique: "ਹੱਥੀਂ ਘੜਾਈ ਅਤੇ ਗਲੇਜ਼ਿੰਗ",
        motif: "ਕਮਲ ਅਤੇ ਫੁੱਲ ਪੱਤੀਆਂ",
        colors: ["ਗੂੜ੍ਹਾ ਨੀਲਾ", "ਅਸਮਾਨੀ", "ਚਿੱਟਾ"],
        region: "ਰਾਜਸਥਾਨ (ਜੈਪੁਰ)",
        description: "ਕੁਆਰਟਜ਼ ਪੱਥਰ ਨਾਲ ਬਣੀ ਬਿਨਾਂ ਮਿੱਟੀ ਵਾਲੀ ਪ੍ਰਸਿੱਧ ਜੈਪੁਰੀ ਨੀਲੀ ਪੌਟਰੀ।",
        culturalContext: "ਰਾਜਸਥਾਨੀ ਸ਼ਾਹੀ ਘਰਾਣਿਆਂ ਦੀ ਸ਼ਾਨਦਾਰ ਦਸਤਕਾਰੀ।",
        visualFeatures: ["ਚਮਕੀਲੀ ਨੀਲੀ ਸਤਹ", "ਹੱਥ ਦੀ ਬਾਰੀਕ ਚਿੱਤਰਕਾਰੀ"]
      },
      as: {
        craftCategory: "মৃৎশিল্প",
        craftName: "জয়পুৰ ব্লু পটাৰী",
        productType: "সিৰামিক ফুলদানী",
        material: "কোৱাৰ্টজ শিলৰ গুৰি",
        technique: "হাতেৰে গঢ়া আৰু অক্সাইড গ্লেজিং",
        motif: "পদুম আৰু ফুলৰ পাহি",
        colors: ["গাঢ় নীলা", "ফিৰোজা", "বগা"],
        region: "ৰাজস্থান (জয়পুৰ)",
        description: "মাটি নোহোৱাকৈ কোৱাৰ্টজ শিলেৰে হাতেৰে নিৰ্মিত জয়পুৰৰ বিখ্যাত ব্লু পটাৰী।",
        culturalContext: "ৰাজপুত ৰজাসকলৰ পৃষ্ঠপোষকতা লাভ কৰা ঐতিহাসিক মৃৎশিল্প।",
        visualFeatures: ["উজ্জ্বল নীলা ৰঙৰ জিলিকনি", "সূক্ষ্ম হস্ত চিত্ৰকলা"]
      }
    }
  },

  // 6. Bamboo basket (Assam Bamboo & Cane Basketry)
  {
    keywords: ["bamboo basket", "cane", "basketry", "assam bamboo", "woven basket", "bamboo craft"],
    canonical: {
      craftCategory: "Bamboo Craft",
      craftName: "Assam Bamboo & Cane Basketry",
      productType: "Storage Basket",
      material: "Natural Seasoned Bamboo & Split Cane Splints",
      technique: "Hexagonal Twill Plaiting & Interlaced Weft Weaving",
      motif: "Diamond Plait & Geometric Herringbone",
      colors: ["Natural Golden Bamboo", "Toasted Amber", "Smoky Ochre"],
      region: "Likely Assam / Northeast India",
      description: "Hand-plaited eco-friendly basket woven from fine bamboo splints, cured with smoke for natural insect resistance and strength.",
      culturalContext: "Sustainable indigenous craft tradition of the Brahmaputra valley utilizing fast-growing renewable bamboo.",
      visualFeatures: ["Even hand-split bamboo ribs", "Tightly interlocked twill rim", "Natural unbleached golden woody texture"],
      confidence: 0.89,
      uncertainAttributes: ["exact district cluster"]
    },
    translations: {
      en: {
        craftCategory: "Bamboo Craft",
        craftName: "Assam Bamboo & Cane Basketry",
        productType: "Storage Basket",
        material: "Natural Seasoned Bamboo & Split Cane Splints",
        technique: "Hexagonal Twill Plaiting & Interlaced Weft Weaving",
        motif: "Diamond Plait & Geometric Herringbone",
        colors: ["Natural Golden Bamboo", "Toasted Amber", "Smoky Ochre"],
        region: "Likely Assam / Northeast India",
        description: "Hand-plaited eco-friendly basket woven from fine bamboo splints, cured with smoke for natural insect resistance and strength.",
        culturalContext: "Sustainable indigenous craft tradition of the Brahmaputra valley utilizing fast-growing renewable bamboo.",
        visualFeatures: ["Even hand-split bamboo ribs", "Tightly interlocked twill rim", "Natural unbleached golden woody texture"]
      },
      te: {
        craftCategory: "వెదురు కళ",
        craftName: "అస్సాం వెదురు & బెత్తం బుట్ట",
        productType: "నిల్వ బుట్ట",
        material: "సహజ వెదురు మరియు బెత్తం",
        technique: "చేతితో అల్లిన హెగ్సాగోనల్ నేత",
        motif: "జ్యామితీయ డైమండ్ అల్లిక",
        colors: ["బంగారు వెదురు రంగు", "సహజ గోధుమ"],
        region: "అస్సాం / ఈశాన్య భారతదేశం",
        description: "పర్యావరణ హిత సహజ వెదురు బద్దలతో అత్యంత పటిష్టంగా అల్లిన సాంప్రదాయ వెదురు బుట్ట.",
        culturalContext: "ఈశాన్య భారతీయ సాంప్రదాయ సుస్థిర వెదురు హస్తకళ.",
        visualFeatures: ["సన్నని వెదురు పేలికల అల్లిక", "ధృడమైన చేతి నేత అంచు"]
      },
      hi: {
        craftCategory: "बांस एवं बेंत शिल्प",
        craftName: "असम बांस एवं बेंत टोकरी",
        productType: "भंडारण टोकरी",
        material: "प्राकृतिक परिपक्व बांस एवं बेंत",
        technique: "हाथ से गुंथी हुई षट्कोणीय बुनाई",
        motif: "ज्यामितीय जालीदार बुनाई",
        colors: ["प्राकृतिक सुनहरा बांस", "हल्का भूरा"],
        region: "संभावित असम / पूर्वोत्तर भारत",
        description: "बारीक बांस की तीलियों से हाथ से बुनी गई पर्यावरण-अनुकूल टिकाऊ बांस की टोकरी।",
        culturalContext: "पूर्वोत्तर भारत की सदियों पुरानी पर्यावरण-हितैषी वन शिल्प परंपरा।",
        visualFeatures: ["समान बांस की तीलियां", "मजबूत हाथ की बुनावट"]
      },
      ta: {
        craftCategory: "மூங்கில் கைவினை",
        craftName: "அசாம் மூங்கில் கூடை",
        productType: "சேமிப்புக் கூடை",
        material: "இயற்கை மூங்கில் மற்றும் பிரம்பு",
        technique: "கைப்பின்னல் நெசவு",
        motif: "வடிவியல் பின்னல்",
        colors: ["பொன் மூங்கில் நிறம்", "மண் பழுப்பு"],
        region: "அசாம் / வடகிழக்கு இந்தியா",
        description: "மூங்கில் கீற்றுகளால் கைவினைஞர்களால் நேர்த்தியாகப் பின்னப்பட்ட நீடித்து உழைக்கும் இயற்கைக் கூடை.",
        culturalContext: "வடகிழக்கு இந்தியாவின் பாரம்பரிய சூழல்-நட்பு மூங்கில் கலை.",
        visualFeatures: ["சீரான மூங்கில் கீற்றுகள்", "வலுவான கை பின்னல் விளிம்பு"]
      },
      kn: {
        craftCategory: "ಬಿದಿರು ಕರಕುಶಲ",
        craftName: "ಅಸ್ಸಾಂ ಬಿದಿರು ಬುಟ್ಟಿ",
        productType: "ಬುಟ್ಟಿ",
        material: "ನೈಸರ್ಗಿಕ ಬಿದಿರು ಮತ್ತು ಬೆತ್ತ",
        technique: "ಕೈ ಹೆಣಿಗೆ",
        motif: "ಜ್ಯಾಮಿತೀಯ ಹೆಣಿಗೆ ವಿನ್ಯಾಸ",
        colors: ["ಚಿನ್ನದ ಬಿದಿರು ಬಣ್ಣ", "ಕಂದು"],
        region: "ಅಸ್ಸಾಂ / ಈಶಾನ್ಯ ಭಾರತ",
        description: "ನೈಸರ್ಗಿಕ ಬಿದಿರಿನ ಪಟ್ಟಿಗಳಿಂದ ಕೈಯಿಂದ ಹೆಣೆದ ಪರಿಸರ ಸ್ನೇಹಿ ಸುಂದರ ಬುಟ್ಟಿ.",
        culturalContext: "ಈಶಾನ್ಯ ಭಾರತದ ಸುಸ್ಥಿರ ಬಿದಿರು ಪರಂಪರೆ.",
        visualFeatures: ["ಸಮತೋಲಿತ ಬಿದಿರು ಪಟ್ಟಿಗಳು", "ಬಲವಾದ ಅಂಚಿನ ಹೆಣಿಗೆ"]
      },
      ml: {
        craftCategory: "മുള കരകൗശലം",
        craftName: "അസം മുള കൊട്ട",
        productType: "സ്റ്റോറേജ് കൊട്ട",
        material: "പ്രകൃതിദത്ത മുളയും ചൂരലും",
        technique: "കൈകൊണ്ടുള്ള നെയ്ത്ത്",
        motif: "ജ്യാമിതീയ പാറ്റേൺ",
        colors: ["മുളയുടെ മഞ്ഞ നിറം", "തവിട്ട്"],
        region: "അസം",
        description: "പരിസ്ഥിതി സൗഹൃദമായ മുള ചീളുകൾ കൊണ്ട് നിർമ്മിച്ച പരമ്പരാഗത കൊട്ട.",
        culturalContext: "വടക്കുകിഴക്കൻ ഇന്ത്യയുടെ പാരമ്പര്യ കരകൗശലവിദ്യ.",
        visualFeatures: ["സുദൃഢമായ നെയ്ത്ത്", "സ്വാഭാവിക മുളയുടെ ഘടന"]
      },
      mr: {
        craftCategory: "बांबू हस्तकला",
        craftName: "आसाम बांबू टोपली",
        productType: "टोपली",
        material: "नैसर्गिक बांबू आणि वेत",
        technique: "हाताने विणलेली जाळी",
        motif: "भूमितीय नक्षी",
        colors: ["सोनेरी बांबू रंग", "तपकिरी"],
        region: "आसाम / ईशान्य भारत",
        description: "बांबूच्या बारीक पट्ट्यांपासून हाताने विणलेली टिकाऊ आणि पर्यावरणपूरक टोपली.",
        culturalContext: "ईशान्य भारतातील पारंपरिक बांबू हस्तकला.",
        visualFeatures: ["मजबूत विणकाम", "नैसर्गिक बांबू पोत"]
      },
      gu: {
        craftCategory: "વાંસકામ",
        craftName: "આસામ વાંસની ટોપલી",
        productType: "ટોપલી",
        material: "કુદરતી વાંસ અને નેતર",
        technique: "હાથ વણાટકામ",
        motif: "ભૌમિતિક ગૂંથણી",
        colors: ["સોનેરી વાંસ રંગ", "બદામી"],
        region: "આસામ / પૂર્વોત્તર ભારત",
        description: "કુદરતી વાંસની સળીઓથી હાથેથી ગૂંથેલી મજબૂત અને ઇકો-ફ્રેન્ડલી ટોપલી.",
        culturalContext: "પૂર્વોત્તર ભારતની પ્રકૃતિ-આધારિત પ્રાચીન શિલ્પકળા.",
        visualFeatures: ["સુંવાળી વાંસની પટ્ટીઓ", "મજબૂત કિનાર"]
      },
      bn: {
        craftCategory: "বাঁশ ও বেত শিল্প",
        craftName: "আসাম বাঁশের ঝুড়ি",
        productType: "ঝুড়ি",
        material: "প্রাকৃতিক বাঁশ ও বেত",
        technique: "হাতে বোনা জালতি",
        motif: "জ্যামিতিক বিন্যাস",
        colors: ["সোনালী বাঁশ রং", "বাদামী"],
        region: "আসাম / উত্তর-পূর্ব ভারত",
        description: "সূক্ষ্ম বাঁশের চটা দিয়ে নিপুণ হাতে তৈরি পরিবেশবান্ধব মজবুত ঝুড়ি।",
        culturalContext: "উত্তর-পূর্ব ভারতের প্রাচীন ও ঐতিহ্যবাহী বাঁশ শিল্প।",
        visualFeatures: ["সুদৃঢ় হাতের বুনন", "প্রাকৃতিক বাঁশের টান"]
      },
      or: {
        craftCategory: "ବାଉଁଶ ଶିଳ୍ପ",
        craftName: "ଆସାମ ବାଉଁଶ ଟୋକେଇ",
        productType: "ଟୋକେଇ",
        material: "ପ୍ରାକୃତିକ ବାଉଁଶ ଓ ବେତ",
        technique: "ହସ୍ତବୁଣା ଶୈଳୀ",
        motif: "ଜ୍ୟାମିତିକ ଜାଲି",
        colors: ["ସୁନେଲି ବାଉଁଶ ରଙ୍ଗ", "ବାଦାମୀ"],
        region: "ଆସାମ",
        description: "ସରୁ ବାଉଁଶ ବତାରେ ହାତରେ ବୁଣା ଯାଇଥିବା ମଜବୁତ ଓ ସୁନ୍ଦର ଟୋକେଇ।",
        culturalContext: "ଉତ୍ତର-ପୂର୍ବ ଭାରତର ପାରମ୍ପରିକ ବାଉଁଶ କାରିଗରୀ।",
        visualFeatures: ["ସମାନ ବାଉଁଶ କାଠି", "ଦୃଢ଼ ହସ୍ତଶିଳ୍ପ"]
      },
      pa: {
        craftCategory: "ਬਾਂਸ ਦਸਤਕਾਰੀ",
        craftName: "ਅਸਾਮ ਬਾਂਸ ਦੀ ਟੋਕਰੀ",
        productType: "ਟੋਕਰੀ",
        material: "ਕੁਦਰਤੀ ਬਾਂਸ ਅਤੇ ਬੈਂਤ",
        technique: "ਹੱਥੀਂ ਬੁਣਾਈ",
        motif: "ਜਿਓਮੈਟ੍ਰਿਕ ਜਾਲੀ",
        colors: ["ਸੁਨਹਿਰੀ ਬਾਂਸ ਰੰਗ", "ਭੂਰਾ"],
        region: "ਅਸਾਮ",
        description: "ਬਾਂਸ ਦੀਆਂ ਬਰੀਕ ਤੀਲਾਂ ਨਾਲ ਹੱਥੀਂ ਬੁਣੀ ਗਈ ਵਾਤਾਵਰਣ ਅਨੁਕੂਲ ਟੋਕਰੀ।",
        culturalContext: "ਉੱਤਰ-ਪੂਰਬੀ ਭਾਰਤ ਦੀ ਰਵਾਇਤੀ ਬਾਂਸ ਕਲਾ।",
        visualFeatures: ["ਮਜ਼ਬੂਤ ਹੱਥ ਦੀ ਬੁਣਾਈ", "ਕੁਦਰਤੀ ਬਾਂਸ ਦੀ ਬਣਤਰ"]
      },
      as: {
        craftCategory: "বাঁহ-বেতৰ শিল্প",
        craftName: "অসমৰ বাঁহ আৰু বেতৰ পাচি",
        productType: "পাচি / খৰাহী",
        material: "প্ৰাকৃতিক বাঁহ আৰু বেত",
        technique: "হাতেৰে বোৱা বিন্যাস",
        motif: "জ্যামিতিক চানেকি",
        colors: ["সোণালী বাঁহৰ ৰং", "মটীয়া"],
        region: "অসম",
        description: "বাঁহৰ মিহি চঁচিৰে হাতেৰে বৈ উলিওৱা অসমৰ পৰম্পৰাগত সুন্দৰ আৰু মজবুত পাচি।",
        culturalContext: "অসমৰ ঐতিহ্যমণ্ডিত লোকসংস্কৃতি আৰু বাঁহ শিল্প।",
        visualFeatures: ["মিহি বাঁহৰ কামি", "মজবুত গাঁথনি", "প্ৰাকৃতিক কাঠৰ সুবাস"]
      }
    }
  },

  // 7. Embroidery (Lucknowi Chikankari)
  {
    keywords: ["chikankari", "lucknowi", "shadow work", "bakhiya", "chikan", "hand embroidery", "embroidery"],
    canonical: {
      craftCategory: "Embroidery",
      craftName: "Lucknowi Chikankari",
      productType: "Embroidered Kurta Fabric",
      material: "Pure Handloom Cotton / Mulmul with Untwisted Cotton Floss",
      technique: "Traditional Needlework Shadow Stitching (Bakhiya, Tepchi, Jaali)",
      motif: "Paisley Kalka & Jasmine Vines",
      colors: ["Pristine White", "Ivory Cream", "Pastel Mint"],
      region: "Likely Uttar Pradesh (Lucknow)",
      description: "Delicate needlework embroidery hand-stitched on sheer cotton muslin fabric, casting subtle shadow patterns through reverse herringbone stitches.",
      culturalContext: "Refined Mughal court needlework tradition nurtured by generations of rural women artisans across Awadh.",
      visualFeatures: ["Intricate shadow-work on reverse fabric", "Micro-perforated openwork jaali", "Untwisted fine floss thread relief"],
      confidence: 0.87,
      uncertainAttributes: ["exact needle count", "artisan cluster name"]
    },
    translations: {
      en: {
        craftCategory: "Embroidery",
        craftName: "Lucknowi Chikankari",
        productType: "Embroidered Kurta Fabric",
        material: "Pure Handloom Cotton / Mulmul with Untwisted Cotton Floss",
        technique: "Traditional Needlework Shadow Stitching (Bakhiya, Tepchi, Jaali)",
        motif: "Paisley Kalka & Jasmine Vines",
        colors: ["Pristine White", "Ivory Cream", "Pastel Mint"],
        region: "Likely Uttar Pradesh (Lucknow)",
        description: "Delicate needlework embroidery hand-stitched on sheer cotton muslin fabric, casting subtle shadow patterns through reverse herringbone stitches.",
        culturalContext: "Refined Mughal court needlework tradition nurtured by generations of rural women artisans across Awadh.",
        visualFeatures: ["Intricate shadow-work on reverse fabric", "Micro-perforated openwork jaali", "Untwisted fine floss thread relief"]
      },
      hi: {
        craftCategory: "कशीदाकारी / कढ़ाई",
        craftName: "लखनवी चिकनकारी",
        productType: "कढ़ाई किया हुआ कुर्ता वस्त्र",
        material: "शुद्ध मलमल सूती कपड़ा एवं रेशमी धागा",
        technique: "पारंपरिक सुई का काम (बखिया, तेपची और जाली)",
        motif: "केरी (कैलका) और चमेली की बेल",
        colors: ["दूधिया सफेद", "हाथीदांत क्रीम", "हल्का हरा"],
        region: "उत्तर प्रदेश (लखनऊ)",
        description: "महीन मलमल के कपड़े पर ग्रामीण महिला कारीगरों द्वारा सुई-धागे से की गई सूक्ष्म लखनवी चिकनकारी कढ़ाई।",
        culturalContext: "अवध की नवाबी संस्कृति से उपजी भारत की सबसे परिष्कृत हाथ की कढ़ाई।",
        visualFeatures: ["कपड़े के पीछे बारीक बखिया काम", "हाथ से कटी हुई महीन जाली", "नाजुक छायादार रूप"]
      },
      te: {
        craftCategory: "ఎంబ్రాయిడరీ / కుట్టుపని",
        craftName: "లక్నో చికంకారీ",
        productType: "ఎంబ్రాయిడరీ కుర్తా వస్త్రం",
        material: "స్వచ్ఛమైన మల్మల్ పత్తి వస్త్రం",
        technique: "సూది కుట్టుపని షాడో వర్క్ (బఖియా, తేప్చి, జాలీ)",
        motif: "మామిడి పిందె (కల్కా) & మల్లె తీగలు",
        colors: ["స్వచ్ఛమైన తెలుపు", "క్రీమ్ రంగు", "లేత రంగులు"],
        region: "ఉత్తర ప్రదేశ్ (లక్నో)",
        description: "తేలికపాటి మల్మల్ కాటన్ వస్త్రంపై గ్రామీణ మహిళలు సూదితో అద్భుతంగా అల్లిన సాంప్రదాయ లక్నో చికంకారీ కళ.",
        culturalContext: "అవధ్ నవాబుల కాలం నాటి అత్యంత సున్నితమైన భారతీయ చేతి కుట్టుపని కళ.",
        visualFeatures: ["వస్త్రం వెనుక చేసిన సూక్ష్మమైన నీడ అల్లిక", "చేతితో చేసిన సున్నితమైన జాలీ పని"]
      },
      ta: {
        craftCategory: "தையல் கலை",
        craftName: "லக்னோ சிக்கன்காரி",
        productType: "எம்பிராய்டரி ஆடை",
        material: "மெல்லிய மல்மல் பருத்தி துணி",
        technique: "பாரம்பரிய நிழல் தையல் வேலைப்பாடு",
        motif: "மாங்காய் வடிவம் மற்றும் மல்லிகை மலர்",
        colors: ["வெள்ளை", "கிரீம்", "இளம்பச்சை"],
        region: "உத்தரப் பிரதேசம் (லக்னோ)",
        description: "மெல்லிய மஸ்லின் துணியில் கைவினைக் கலைஞர்களால் ஊசியால் நுணுக்கமாக தைக்கப்பட்ட புகழ்பெற்ற சிக்கன்காரி ஆடை.",
        culturalContext: "அவத் நவாபுகள் காலத்தில் மலர்ந்த மென்மையான கைத்தையல் கலை.",
        visualFeatures: ["நிழல் போன்ற தையல் முறை", "நுண்ணிய ஜாலி வேலைப்பாடு"]
      },
      kn: {
        craftCategory: "ಕಸೂತಿ ಕಲೆ",
        craftName: "ಲಕ್ನೋ ಚಿಕಂಕಾರಿ",
        productType: "ಕಸೂತಿ ಬಟ್ಟೆ",
        material: "ಮೃದುವಾದ ಮಲ್ಮಲ್ ಹತ್ತಿ",
        technique: "ಸೂಜಿ ಕಸೂತಿ ಕೆಲಸ (ಶ್ಯಾಡೋ ವರ್ಕ್)",
        motif: "ಮಾವಿನಕಾಯಿ ಮತ್ತು ಹೂವಿನ ಬಳ್ಳಿ",
        colors: ["ಹಾಲು ಬಿಳಿ", "ಕೆನೆ ಬಿಳಿ"],
        region: "ಉತ್ತರ ಪ್ರದೇಶ (ಲಕ್ನೋ)",
        description: "ತೆಳುವಾದ ಮಲ್ಮಲ್ ಹತ್ತಿ ಬಟ್ಟೆಯ ಮೇಲೆ ಸೂಜಿದಾರದಿಂದ ಮಾಡಿದ ಅತಿ ಸೂಕ್ಷ್ಮ ಲಕ್ನೋ ಚಿಕಂಕಾರಿ ಕಸೂತಿ.",
        culturalContext: "ಐತಿಹಾಸಿಕ ಭಾರತೀಯ ರಾಜಮನೆತನದ ಕಸೂತಿ ಕಲೆ.",
        visualFeatures: ["ಸೂಕ್ಷ್ಮ ಶ್ಯಾಡೋ ವರ್ಕ್", "ಕೈಕಸೂತಿಯ ಪಾರದರ್ಶಕತೆ"]
      },
      ml: {
        craftCategory: "എംബ്രോയിഡറി",
        craftName: "ലഖ്‌നൗ ചിക്കൻകാരി",
        productType: "എംബ്രോയിഡറി വസ്ത്രം",
        material: "മൽമൽ കോട്ടൺ",
        technique: "ഷാഡോ സ്റ്റിച്ചിംഗ്",
        motif: "മാങ്ങ മാതൃകയും വള്ളികളും",
        colors: ["വെള്ള", "ക്രീം"],
        region: "ഉത്തർപ്രദേശ്",
        description: "കോട്ടൺ തുണിയിൽ സൂചിയും നൂലും കൊണ്ട് നെയ്തെടുത്ത അത്ഭുതകരമായ ചിക്കൻകാരി കല.",
        culturalContext: "മുഗൾ രാജവംശത്തിന്റെ പാരമ്പര്യ തുന്നൽവിദ്യ.",
        visualFeatures: ["സൂക്ഷ്മമായ തുന്നലുകൾ", "നിഴൽ പാറ്റേണുകൾ"]
      },
      mr: {
        craftCategory: "भरतकाम",
        craftName: "लखनवी चिकनकारी",
        productType: "कुर्ता कापड",
        material: "मलमल सुती कापड",
        technique: "सुईचे बारीक भरतकाम (बखिया, जाळी)",
        motif: "कैरी आणि फुलांची वेल",
        colors: ["पांढरा", "क्रीम"],
        region: "उत्तर प्रदेश (लखनौ)",
        description: "मऊ मलमल कापडावर हाताने सुई-दोऱ्याने केलेली नाजूक लखनवी चिकनकारी.",
        culturalContext: "अवध संस्कृतीतील अत्यंत सुप्रसिद्ध हात भरतकाम.",
        visualFeatures: ["बारीक जाळीकाम", "छायादार भरतकाम"]
      },
      gu: {
        craftCategory: "ભરતકામ",
        craftName: "લખનવી ચિકનકારી",
        productType: "ભરત ભરેલું કાપડ",
        material: "મલમલ સુતરાઉ કાપડ",
        technique: "સોય-દોરાનું શેડો ભરતકામ",
        motif: "કેરી અને ચમેલીની વેલ",
        colors: ["સફેદ", "ઓફ વ્હાઇટ"],
        region: "ઉત્તર પ્રદેશ (લખનૌ)",
        description: "ઝીણા મલમલના કપડા પર ગ્રામીણ કારીગરો દ્વારા હાથેથી કરાયેલ નાજુક ચિકનકારી ભરતકામ.",
        culturalContext: "નવાબી યુગની ભારતની સૌથી શિષ્ટ ભરતકળા.",
        visualFeatures: ["બારીક શેડો વર્ક", "હાથની ઝીણી જાળી"]
      },
      bn: {
        craftCategory: "সূচিকর্ম",
        craftName: "লখনউ চিকনকারী",
        productType: "চিকনের কুর্তা বস্ত্র",
        material: "নরম মলমল সুতি",
        technique: "সুঁই-সুতো দিয়ে শ্যাডো কাজ",
        motif: "কলকা ও জুঁই ফুল",
        colors: ["দুধসাদা", "ক্রিম"],
        region: "উত্তর প্রদেশ (লখনউ)",
        description: "সূক্ষ্ম মলমল কাপড়ের ওপর হাতে বোনা বিশ্ববিখ্যাত লখনউ চিকনকারী সূচিকর্ম।",
        culturalContext: "নবাবী আমলের এক অপূর্ব সূচিশিল্প ঐতিহ্য।",
        visualFeatures: ["কাপড়ের উল্টোপিঠে নিখুঁত কাজ", "হাতে কাটা সূক্ষ্ম জালি"]
      },
      or: {
        craftCategory: "କସିଦାକାରୀ",
        craftName: "ଲକ୍ଷ୍ନୌ ଚିକନକାରୀ",
        productType: "କସିଦା କୁର୍ତ୍ତା କପଡ଼ା",
        material: "ମଲମଲ ସୂତା କପଡ଼ା",
        technique: "ହାତ ସୂଚୀକର୍ମ (ବଖିଆ ଓ ଜାଲି କାମ)",
        motif: "କେରି ଓ ମଲ୍ଲୀ ଲତା",
        colors: ["ଧଳା", "କ୍ରିମ୍"],
        region: "ଉତ୍ତର ପ୍ରଦେଶ (ଲକ୍ଷ୍ନୌ)",
        description: "ନରମ ମଲମଲ କପଡ଼ାରେ ହାତରେ ଛୁଞ୍ଚି ସୂତାରେ ବୁଣା ଯାଇଥିବା ସୁନ୍ଦର ଚିକନକାରୀ କାରୁକାର୍ଯ୍ୟ।",
        culturalContext: "ଅବଧ ସଂସ୍କୃତିର ପ୍ରାଚୀନ ହସ୍ତତନ୍ତ ସୂଚୀକଳା।",
        visualFeatures: ["ଛାୟାଚିତ୍ର ସୂଚୀକର୍ମ", "ମହିନ ଜାଲି କାମ"]
      },
      pa: {
        craftCategory: "ਕਢਾਈ",
        craftName: "ਲਖਨਊ ਚਿਕਨਕਾਰੀ",
        productType: "ਕਢਾਈ ਵਾਲਾ ਕੱਪੜਾ",
        material: "ਮਲਮਲ ਦਾ ਸੂਤੀ ਕੱਪੜਾ",
        technique: "ਹੱਥ ਦੀ ਸੂਈ ਕਢਾਈ (ਸ਼ੈਡੋ ਵਰਕ)",
        motif: "ਅੰਬੀ ਅਤੇ ਵੇਲ ਬੂਟੇ",
        colors: ["ਦੁੱਧੀਆ ਚਿੱਟਾ", "ਕ੍ਰੀਮ"],
        region: "ਉੱਤਰ ਪ੍ਰਦੇਸ਼ (ਲਖਨਊ)",
        description: "ਬਰੀਕ ਮਲਮਲ ਦੇ ਕੱਪੜੇ 'ਤੇ ਹੱਥੀਂ ਕੀਤੀ ਗਈ ਨਾਜ਼ੁਕ ਲਖਨਵੀ ਚਿਕਨਕਾਰੀ ਕਢਾਈ।",
        culturalContext: "ਅਵਧ ਦੇ ਨਵਾਬਾਂ ਦੇ ਦੌਰ ਦੀ ਨਫ਼ਾਸਤ ਭਰੀ ਦਸਤਕਾਰੀ।",
        visualFeatures: ["ਸ਼ੈਡੋ ਵਰਕ ਦੀ ਕਢਾਈ", "ਹੱਥ ਦੀ ਮਹੀਨ ਜਾਲੀ"]
      },
      as: {
        craftCategory: "সূচিশিল্প",
        craftName: "লখনউ চিকনকাৰী",
        productType: "কঢাই কৰা কাপোৰ",
        material: "মলমল কপাহী কাপোৰ",
        technique: "বেজী আৰু সূতাৰ ছাঁয়া বয়ন",
        motif: "কল্কা আৰু ফুলৰ লতা",
        colors: ["গাখীৰতী বগা", "ক্ৰিম"],
        region: "উত্তৰ প্ৰদেশ (লখনউ)",
        description: "মিহি মলমল কাপোৰৰ ওপৰত হাতেৰে বেজী-সূতাৰে কৰা অনুপম চিকনকাৰী সূচিশিল্প।",
        culturalContext: "ভাৰতীয় ঐতিহ্যমণ্ডিত চহকী হাতৰ সূচীকৰ্ম।",
        visualFeatures: ["সূক্ষ্ম ছাঁয়া বয়ন", "হাতে কটা জালিৰ কাম"]
      }
    }
  },

  // 8. Metal handicraft (Bastar Dhokra)
  {
    keywords: ["dhokra", "dokra", "lost wax", "bell metal", "brass", "bastar", "tribal bull", "kondagaon", "metal handicraft"],
    canonical: {
      craftCategory: "Metalcraft",
      craftName: "Bastar Dhokra",
      productType: "Bell Metal Sculpture",
      material: "Lost-Wax Cast Bell Metal (Bronze & Brass Alloy)",
      technique: "Cire Perdue (Lost-Wax Casting) with Hand-Coiled Wax",
      motif: "Tribal Bull / Folk Animal with Coiled Spirals",
      colors: ["Antique Bronze", "Warm Gold Patina", "Earthy Charcoal"],
      region: "Likely Chhattisgarh / Central India Tribal Belt",
      description: "Cast using the 4,000-year-old lost-wax technique where hand-coiled beeswax threads form the mold before being melted out and filled with molten bronze alloy.",
      culturalContext: "Ancient tribal metallurgic tradition dating back to the Indus Valley Dancing Girl figurine, preserving animist folk reverence.",
      visualFeatures: ["Hand-coiled wire-line surface relief", "Unrepeated single-cast clay core texture", "Antique metallic patina"],
      confidence: 0.89,
      uncertainAttributes: ["exact tribal hamlet"]
    },
    translations: {
      en: {
        craftCategory: "Metalcraft",
        craftName: "Bastar Dhokra",
        productType: "Bell Metal Sculpture",
        material: "Lost-Wax Cast Bell Metal (Bronze & Brass Alloy)",
        technique: "Cire Perdue (Lost-Wax Casting) with Hand-Coiled Wax",
        motif: "Tribal Bull / Folk Animal with Coiled Spirals",
        colors: ["Antique Bronze", "Warm Gold Patina", "Earthy Charcoal"],
        region: "Likely Chhattisgarh / Central India Tribal Belt",
        description: "Cast using the 4,000-year-old lost-wax technique where hand-coiled beeswax threads form the mold before being melted out and filled with molten bronze alloy.",
        culturalContext: "Ancient tribal metallurgic tradition dating back to the Indus Valley Dancing Girl figurine, preserving animist folk reverence.",
        visualFeatures: ["Hand-coiled wire-line surface relief", "Unrepeated single-cast clay core texture", "Antique metallic patina"]
      },
      hi: {
        craftCategory: "धातु शिल्प",
        craftName: "बस्तर ढोकरा",
        productType: "कांस्य धातु मूर्ति",
        material: "बेल मेटल (कांसा एवं पीतल मिश्र धातु)",
        technique: "लुप्त-मोम ढलाई (लॉस्ट-वैक्स कास्टिंग)",
        motif: "जनजातीय बैल एवं कुंडलित रेखाएं",
        colors: ["प्राचीन कांस्य", "स्वर्णिम आभा", "धूसर चारकोल"],
        region: "बस्तर, छत्तीसगढ़",
        description: "4,000 वर्ष पुरानी लुप्त-मोम तकनीक से हाथ से ढाली गई अद्वितीय जनजातीय कांस्य मूर्ति।",
        culturalContext: "सिंधु घाटी सभ्यता से जुड़ी अत्यंत प्राचीन भारतीय जनजातीय धातु कला।",
        visualFeatures: ["तार जैसी हाथ की कुंडलित बनावट", "एकल मोल्ड की अनूठी बनावट", "प्राकृतिक धातु आभा"]
      },
      te: {
        craftCategory: "లోహ కళ",
        craftName: "బస్తర్ ధోక్రా",
        productType: "కంచు విగ్రహం",
        material: "బెల్ మెటల్ (కంచు మరియు ఇత్తడి మిశ్రమం)",
        technique: "లాస్ట్-వాక్స్ కాస్టింగ్ (మైనపు అచ్చు పోత)",
        motif: "గిరిజన ఎద్దు / జానపద ఆకృతి",
        colors: ["పురాతన కంచు", "బంగారు వన్నె", "బొగ్గు నలుపు"],
        region: "మధ్య భారత గిరిజన ప్రాంతం (బస్తర్)",
        description: "4,000 ఏళ్ల పురాతన మైనపు అచ్చు విధానంలో చేతితో తయారు చేసిన అసలైన గిరిజన కంచు లోహ కళాఖండం.",
        culturalContext: "సింధు లోయ నాగరికత నాటి ప్రాచీన భారతీయ గిరిజన లోహ సాంకేతికత.",
        visualFeatures: ["చేతితో చుట్టిన మైనపు తీగల నమూనా", "ప్రత్యేకమైన లోహపు ఆకృతి"]
      },
      ta: {
        craftCategory: "உலோகக் கலை",
        craftName: "பஸ்தர் தோக்ரா",
        productType: "வெண்கலச் சிற்பம்",
        material: "பெல் மெட்டல் (வெண்கலம் & பித்தளை கலவை)",
        technique: "மெழுகு வார்ப்பு முறை",
        motif: "பழங்குடி காளை உருவம்",
        colors: ["பழங்கால வெண்கலம்", "தங்க நிறம்"],
        region: "சத்தீஸ்கர் (பஸ்தர்)",
        description: "4,000 ஆண்டுகள் பழமையான மெழுகு வார்ப்பு முறையில் வடிக்கப்பட்ட பாரம்பரிய பழங்குடி வெண்கலச் சிற்பம்.",
        culturalContext: "சிந்து சமவெளி நாகரிகக் காலம் தொட்டு தொடரும் பழங்குடி உலோகக் கலை.",
        visualFeatures: ["மெல்லிய கம்பிச் சுருள் வடிவமைப்பு", "தனித்துவமான உலோக வார்ப்பு"]
      },
      kn: {
        craftCategory: "ಲೋಹದ ಕಲೆ",
        craftName: "ಬಸ್ತಾರ್ ಧೋಕ್ರಾ",
        productType: "ಕಂಚಿನ ಲೋಹ ಶಿಲ್ಪ",
        material: "ಬೆಲ್ ಮೆಟಲ್ (ಕಂಚು ಮತ್ತು ಹಿತ್ತಾಳೆ)",
        technique: "ಮೇಣದ ಎರಕ ಹೊಯ್ಯುವ ಕಲೆ",
        motif: "ಬುಡಕಟ್ಟು ಎತ್ತು ಮತ್ತು ಸುರುಳಿ ರೇಖೆಗಳು",
        colors: ["ಕಂಚಿನ ಬಣ್ಣ", "ಚಿನ್ನದ ಛಾಯೆ"],
        region: "ಛತ್ತೀಸ್‌ಗಢ (ಬಸ್ತಾರ್)",
        description: "ಸಾವಿರಾರು ವರ್ಷಗಳ ಪುರಾತನ ಮೇಣದ ಅಚ್ಚು ವಿಧಾನದಲ್ಲಿ ತಯಾರಾದ ಬಸ್ತಾರ್ ಧೋಕ್ರಾ ಕಂಚಿನ ಮೂರ್ತಿ.",
        culturalContext: "ಪ್ರಾಚೀನ ಸಿಂಧೂ ನಾಗರಿಕತೆಯ ಬುಡಕಟ್ಟು ಲೋಹ ಪರಂಪರೆ.",
        visualFeatures: ["ತಂತಿಯಂತಹ ಮೇಣದ ವಿನ್ಯಾಸ", "ನೈಸರ್ಗಿಕ ಲೋಹದ ಹೊಳಪು"]
      },
      ml: {
        craftCategory: "ലോഹപ്പണി",
        craftName: "ബസ്തർ ധോക്ര",
        productType: "വെങ്കല ശിൽപം",
        material: "ബെൽ മെറ്റൽ",
        technique: "ലോസ്റ്റ്-വാക്സ് കാസ്റ്റിംഗ്",
        motif: "ഗോത്ര കാള രൂപം",
        colors: ["പഴയ വെങ്കല നിറം", "സ്വർണ്ണ വർണ്ണം"],
        region: "ഛത്തീസ്ഗഡ്",
        description: "പുരാതന മെഴുക് അച്ചുപയോഗിച്ച് നിർമ്മിച്ച അതിവിശിഷ്ടമായ ഗോത്ര വെങ്കല ശിൽപം.",
        culturalContext: "സിന്ധുനദീതട സംസ്കാരത്തോളം പഴക്കമുള്ള ഗോത്ര ലോഹ നിർമ്മിതി.",
        visualFeatures: ["വയർ ലൈൻ മാതൃക", "തനിമയാർന്ന പ്രതലം"]
      },
      mr: {
        craftCategory: "धातुकाम",
        craftName: "बस्तर ढोकरा",
        productType: "कांस्य धातू मूर्ती",
        material: "बेल मेटल (कासे आणि पितळ)",
        technique: "लॉस्ट-वॅक्स कास्टिंग",
        motif: "आदिवासी बैल आणि नक्षी",
        colors: ["प्राचीन कासे", "सोनेरी झाक"],
        region: "छत्तीसगड (बस्तर)",
        description: "४,००० वर्षे जुन्या पारंपरिक मेण ओतकाम तंत्राने बनवलेली आदिवासी धातू मूर्ती.",
        culturalContext: "सिंधू संस्कृतीशी नाते सांगणारी प्राचीन भारतीय धातू कला.",
        visualFeatures: ["तारेसारखी वळणदार नक्षी", "अस्सल धातू पोत"]
      },
      gu: {
        craftCategory: "ધાતુકામ",
        craftName: "બસ્તર ધોકરા",
        productType: "કાંસાનું શિલ્પ",
        material: "બેલ મેટલ (કાંસું અને પિત્તળ)",
        technique: "મીણ ઢાળવાની પદ્ધતિ (લોસ્ટ-વેક્સ)",
        motif: "આદિવાસી આખલો અને કુંડળી ભાત",
        colors: ["એન્ટિક કાંસું", "સોનેરી"],
        region: "છત્તીસગઢ (બસ્તર)",
        description: "૪,૦૦૦ વર્ષ જૂની મીણ ઢાળવાની પદ્ધતિથી હાથેથી ઘડેલું પરંપરાગત આદિવાસી કાંસા શિલ્પ.",
        culturalContext: "સિંધુ ખીણની સભ્યતા સાથે જોડાયેલી ભારતની અતિ પ્રાચીન ધાતુ કળા.",
        visualFeatures: ["તાર જેવી ગૂંથેલી સપાટી", "અસલ ધાતુનો રંગ"]
      },
      bn: {
        craftCategory: "ধাতুশিল্প",
        craftName: "বস্তার ঢোকরা",
        productType: "কাঁসা ও পিতলের মূর্তি",
        material: "বেল মেটাল",
        technique: "লস্ট-ওয়াক্স কাস্টিং (মোম ছাঁচ পদ্ধতি)",
        motif: "আদিবাসী ষাঁড় ও সর্পিলাকার রেখা",
        colors: ["প্রাচীন ব্রোঞ্জ", "সোনালী আভা"],
        region: "ছত্তিশগড় (বস্তার)",
        description: "৪,০০০ বছরের প্রাচীন মোম ছাঁচ পদ্ধতিতে ঢালাই করা অনুপম আদিবাসী ধাতব ভাস্কর্য।",
        culturalContext: "সিন্ধু সভ্যতার ঐতিহ্যবাহী অতি প্রাচীন আদিবাসী ধাতুশিল্প।",
        visualFeatures: ["তারের মতো কুন্ডলী নকশা", "অদ্বিতীয় একক ঢালাই"]
      },
      or: {
        craftCategory: "ଧାତୁ କଳା",
        craftName: "ବସ୍ତର ଢୋକ୍ରା",
        productType: "କଂସା ପିତ୍ତଳ ମୂର୍ତ୍ତି",
        material: "ବେଲ୍ ମେଟାଲ (କଂସା ଓ ପିତ୍ତଳ)",
        technique: "ମହମ ଛାଞ୍ଚ ଢଳେଇ (ଲଷ୍ଟ-ୱାକ୍ସ)",
        motif: "ଆଦିବାସୀ ବଳଦ ଓ ଗୁଡ଼ାଯାଇଥିବା ତାର",
        colors: ["ପ୍ରାଚୀନ କଂସା", "ସୁନେଲି ଆଭା"],
        region: "ଛତିଶଗଡ଼ (ବସ୍ତର)",
        description: "୪,୦୦୦ ବର୍ଷ ପୁରୁଣା ମହମ ଛାଞ୍ଚ ପଦ୍ଧତିରେ ଗଢ଼ା ଯାଇଥିବା ଅଦ୍ୱିତୀୟ ଆଦିବାସୀ କଂସା ମୂର୍ତ୍ତି।",
        culturalContext: "ସିନ୍ଧୁ ସଭ୍ୟତାର ପ୍ରାଚୀନ ଆଦିବାସୀ ଧାତୁ ଶିଳ୍ପ।",
        visualFeatures: ["ତାର ଗୁଡ଼ା ସୂକ୍ଷ୍ମ କାମ", "ଅନନ୍ୟ ଧାତବ ଚମକ"]
      },
      pa: {
        craftCategory: "ਧਾਤ ਦਾ ਕੰਮ",
        craftName: "ਬਸਤਰ ਢੋਕਰਾ",
        productType: "ਕਾਂਸੀ ਦੀ ਮੂਰਤੀ",
        material: "ਬੈੱਲ ਮੈਟਲ (ਕਾਂਸੀ ਅਤੇ ਪਿੱਤਲ)",
        technique: "ਮੋਮ ਢਲਾਈ ਤਕਨੀਕ",
        motif: "ਕਬਾਇਲੀ ਬਲਦ ਅਤੇ ਚੱਕਰ",
        colors: ["ਪੁਰਾਣੀ ਕਾਂਸੀ", "ਸੁਨਹਿਰੀ"],
        region: "ਛੱਤੀਸਗੜ੍ਹ",
        description: "੪,੦੦੦ ਸਾਲ ਪੁਰਾਣੀ ਮੋਮ ਢਲਾਈ ਵਿਧੀ ਨਾਲ ਤਿਆਰ ਕੀਤੀ ਗਈ ਸ਼ਾਨਦਾਰ ਕਬਾਇਲੀ ਮੂਰਤੀ।",
        culturalContext: "ਸਿੰਧ ਘਾਟੀ ਸਭਿਅਤਾ ਨਾਲ ਜੁੜੀ ਪ੍ਰਾਚੀਨ ਕਬਾਇਲੀ ਧਾਤੂ ਕਲਾ।",
        visualFeatures: ["ਤਾਰ ਵਰਗੀ ਸਤਹ", "ਪ੍ਰਮਾਣਿਕ ਧਾਤੂ ਰੂਪ"]
      },
      as: {
        craftCategory: "ধাতুশিল্প",
        craftName: "বস্তাৰ ঢোকৰা",
        productType: "কাঁহ-পিতলৰ ভাস্কৰ্য",
        material: "বেল মেটেল",
        technique: "মম গলাই ছাঁচ বনোৱা পদ্ধতি",
        motif: "জনজাতীয় বলধ আৰু ঘূৰণীয়া ৰেখা",
        colors: ["প্ৰাচীন কাঁহৰ ৰং", "সোণালী"],
        region: "ছত্তীশগড়",
        description: "৪,০০০ বছৰীয়া প্ৰাচীন মম ছাঁচ পদ্ধতিৰে হাতেৰে গঢ়া অনুপম জনজাতীয় কাঁহৰ ভাস্কৰ্য।",
        culturalContext: "সিন্ধু সভ্যতাৰ কালৰ পৰা চলি অহা অতি প্ৰাচীন ধাতুবিদ্যাৰ ঐতিহ্য।",
        visualFeatures: ["তাঁৰৰ দৰে মেৰিয়াই কৰা কাম", "অনবদ্য ধাতুৰ উজ্জ্বলতা"]
      }
    }
  },

  // 9. Traditional Doll (Kondapalli Heritage Doll)
  {
    keywords: ["traditional doll", "kondapalli", "doll", "dancing doll", "terracotta doll", "wooden doll", "thanjavur doll"],
    canonical: {
      craftCategory: "Toy & Doll Craft",
      craftName: "Kondapalli Heritage Doll",
      productType: "Artisan Handicraft Doll",
      material: "Tella Poniki Wood & Tamarind Seed Paste",
      technique: "Hand Carving & Natural Mineral Pigment Painting",
      motif: "Village Folk Life & Traditional Dancers",
      colors: ["Vermilion Red", "Turmeric Yellow", "Indigo Blue"],
      region: "Likely Andhra Pradesh (Kondapalli)",
      description: "Hand-carved wooden doll sculpted from light softwood, joined using tamarind seed adhesive, and hand-painted with vivid non-toxic colors depicting rural folk traditions.",
      culturalContext: "400-year-old hereditary artisan doll tradition of Andhra Pradesh patronized during festive Navaratri Bommala Koluvu celebrations.",
      visualFeatures: ["Expressive hand-painted facial features", "Carved anatomical proportion", "Matte natural earth pigment finish"],
      confidence: 0.90,
      uncertainAttributes: ["artisan dynasty cluster"]
    },
    translations: {
      en: {
        craftCategory: "Toy & Doll Craft",
        craftName: "Kondapalli Heritage Doll",
        productType: "Artisan Handicraft Doll",
        material: "Tella Poniki Wood & Tamarind Seed Paste",
        technique: "Hand Carving & Natural Mineral Pigment Painting",
        motif: "Village Folk Life & Traditional Dancers",
        colors: ["Vermilion Red", "Turmeric Yellow", "Indigo Blue"],
        region: "Likely Andhra Pradesh (Kondapalli)",
        description: "Hand-carved wooden doll sculpted from light softwood, joined using tamarind seed adhesive, and hand-painted with vivid non-toxic colors depicting rural folk traditions.",
        culturalContext: "400-year-old hereditary artisan doll tradition of Andhra Pradesh patronized during festive Navaratri Bommala Koluvu celebrations.",
        visualFeatures: ["Expressive hand-painted facial features", "Carved anatomical proportion", "Matte natural earth pigment finish"]
      },
      te: {
        craftCategory: "బొమ్మల కళ",
        craftName: "కొండపల్లి సాంప్రదాయ బొమ్మ",
        productType: "హస్తకళా బొమ్మ",
        material: "తెల్ల పొనికి చెక్క & చింతగింజల జిగురు",
        technique: "చేతి చెక్కడము & సహజ రంగుల చిత్రణ",
        motif: "గ్రామీణ జీవనం & సాంప్రదాయ నృత్యకారులు",
        colors: ["సిందూర ఎరుపు", "పసుపు", "నీలం"],
        region: "ఆంధ్రప్రదేశ్ (కొండపల్లి)",
        description: "తేలికపాటి పొనికి చెక్కతో చేతితో చెక్కి, సహజ రంగులతో తీర్చిదిద్దిన చారిత్రక కొండపల్లి బొమ్మ.",
        culturalContext: "దసరా బొమ్మల కొలువులో వెలిగిపోయే 400 ఏళ్ల నాటి ఆంధ్ర హస్తకళా వైభవం.",
        visualFeatures: ["సజీవమైన ముఖ కవళికలు", "చేతితో వేసిన సహజ రంగులు", "తేలికపాటి పొనికి చెక్క"]
      },
      hi: {
        craftCategory: "गुड़िया एवं खिलौना शिल्प",
        craftName: "कोंडापल्ली पारंपरिक गुड़िया",
        productType: "हस्तशिल्प गुड़िया",
        material: "पुनिकी लकड़ी एवं इमली बीज गोंद",
        technique: "हस्त नक्काशी एवं प्राकृतिक रंगों से चित्रकारी",
        motif: "ग्रामीण लोक जीवन एवं नर्तक",
        colors: ["सिंदूरी लाल", "हल्दी पीला", "नीला"],
        region: "आंध्र प्रदेश (कोंडापल्ली)",
        description: "हल्की पुनिकी लकड़ी से हाथ से तराशी गई और प्राकृतिक रंगों से रंगी गई पारंपरिक कोंडापल्ली गुड़िया।",
        culturalContext: "आंध्र प्रदेश की 400 वर्ष पुरानी पारंपरिक हस्तनिर्मित गुड़िया शिल्पकला।",
        visualFeatures: ["हाथ से बने सजीव चेहरे के भाव", "पारंपरिक लोक वेशभूषा", "प्राकृतिक रंग"]
      },
      ta: {
        craftCategory: "பொம்மை கலை",
        craftName: "கொண்டபள்ளி பாரம்பரிய பொம்மை",
        productType: "கைவினை பொம்மை",
        material: "பொனிகி மென்மரம் மற்றும் இயற்கை வண்ணங்கள்",
        technique: "கை செதுக்கல் மற்றும் வண்ண ஓவியம்",
        motif: "கிராமிய நடனம் மற்றும் நாட்டுப்புற வாழ்க்கை",
        colors: ["செந்தூரம்", "மஞ்சள்", "நீலம்"],
        region: "ஆந்திரப் பிரதேசம் (கொண்டபள்ளி)",
        description: "மென்மையான மரத்தில் கைவினைஞர்களால் நேர்த்தியாக செதுக்கப்பட்டு வர்ணம் தீட்டப்பட்ட பாரம்பரிய பொம்மை.",
        culturalContext: "நவராத்திரி பொம்மை கொலுவில் முதன்மை இடம் பெறும் 400 ஆண்டு பாரம்பரியக் கலை.",
        visualFeatures: ["உயிரோட்டமான முகபாவங்கள்", "இயற்கை வண்ணப் பூச்சு"]
      },
      kn: {
        craftCategory: "ಗೊಂಬೆ ಕಲೆ",
        craftName: "ಕೊಂಡಪಲ್ಲಿ ಸಾಂಪ್ರದಾಯಿಕ ಗೊಂಬೆ",
        productType: "ಕರಕುಶಲ ಗೊಂಬೆ",
        material: "ಪೊನಿಕಿ ಮರ ಮತ್ತು ನೈಸರ್ಗಿಕ ಬಣ್ಣಗಳು",
        technique: "ಕೈ ಕೆತ್ತನೆ ಮತ್ತು ನೈಸರ್ಗಿಕ ಬಣ್ಣಗಾರಿಕೆ",
        motif: "ಗ್ರಾಮೀಣ ಜನಪದ ಬದುಕು",
        colors: ["ಕೆಂಪು", "ಹಳದಿ", "ನೀಲಿ"],
        region: "ಆಂಧ್ರಪ್ರದೇಶ (ಕೊಂಡಪಲ್ಲಿ)",
        description: "ಹಗುರವಾದ ಮರದಿಂದ ಕೆತ್ತಲ್ಪಟ್ಟು ನೈಸರ್ಗಿಕ ಬಣ್ಣಗಳಿಂದ ಕಂಗೊಳಿಸುವ ಕೊಂಡಪಲ್ಲಿ ಕರಕುಶಲ ಗೊಂಬೆ.",
        culturalContext: "ದಸರಾ ಬೊಂಬೆ ಹಬ್ಬದ 400 ವರ್ಷಗಳ ಐತಿಹಾಸಿಕ ಪರಂಪರೆ.",
        visualFeatures: ["ಸುಂದರ ಮುಖಭಾವಗಳು", "ಪಾರಂಪರಿಕ ನೈಸರ್ಗಿಕ ಬಣ್ಣ"]
      },
      ml: {
        craftCategory: "പാവ നിർമ്മാണം",
        craftName: "കൊണ്ടപ്പള്ളി പാരമ്പര്യ പാവ",
        productType: "കരകൗശല പാവ",
        material: "തടിയും പ്രകൃതിദത്ത ചായങ്ങളും",
        technique: "കൈ കൊത്തുപണിയും ചിത്രരചനയും",
        motif: "നാടോടി ജീവിതം",
        colors: ["സിന്ദൂരം", "മഞ്ഞ", "നീല"],
        region: "ആന്ധ്രാപ്രദേശ്",
        description: "കൈകൊണ്ട് തടിയിൽ കൊത്തിയുണ്ടാക്കി സ്വാഭാവിക വർണ്ണങ്ങൾ ചാലിച്ച മനോഹര പാവ.",
        culturalContext: "നവരാത്രി ഉത്സവങ്ങൾക്ക് മാറ്റുകൂട്ടുന്ന ദക്ഷിണേന്ത്യൻ പാരമ്പര്യം.",
        visualFeatures: ["സൂക്ഷ്മമായ മുഖഭാവങ്ങൾ", "പ്രകൃതിദത്ത വർണ്ണങ്ങൾ"]
      },
      mr: {
        craftCategory: "बाहुली हस्तकला",
        craftName: "कोंडापल्ली पारंपरिक बाहुली",
        productType: "हस्तकला बाहुली",
        material: "हलके लाकूड आणि नैसर्गिक रंग",
        technique: "हाताने कोरीव काम आणि रंगकाम",
        motif: "ग्रामीण लोकजीवन आणि नर्तक",
        colors: ["लाल", "पिवळा", "निळा"],
        region: "आंध्र प्रदेश (कोंडापल्ली)",
        description: "हलक्या लाकडावर हाताने कोरीव काम करून अस्सल रंगात रंगवलेली कोंडापल्ली बाहुली.",
        culturalContext: "आंध्र प्रदेशातील ४०० वर्षे जुनी ऐतिहासिक खेळणी कला.",
        visualFeatures: ["सुबक चेहरेपट्टी", "पारंपरिक रंगसंगती"]
      },
      gu: {
        craftCategory: "ઢીંગલી કળા",
        craftName: "કોંડાપલ્લી પરંપરાગત ઢીંગલી",
        productType: "હસ્તકલા ઢીંગલી",
        material: "હલકું લાકડું અને કુદરતી રંગો",
        technique: "હાથ નકશીકામ અને રંગકામ",
        motif: "ગ્રામીણ લોકજીવન",
        colors: ["લાલ", "પીળો", "વાદળી"],
        region: "આંધ્રપ્રદેશ (કોંડાપલ્લી)",
        description: "હળવા લાકડામાંથી હાથેથી ઘડેલી અને કુદરતી રંગોથી સજાવેલી પ્રખ્યાત કોંડાપલ્લી ઢીંગલી.",
        culturalContext: "૪૦૦ વર્ષ પુરાણી દક્ષિણ ભારતની રમકડાં પરંપરા.",
        visualFeatures: ["જીવંત ચહેરાના હાવભાવ", "હાથથી ભરેલા રંગો"]
      },
      bn: {
        craftCategory: "পুতুল শিল্প",
        craftName: "কোন্ডাপল্লী ঐতিহ্যবাহী পুতুল",
        productType: "হস্তশিল্প পুতুল",
        material: "হালকা কাঠ ও প্রাকৃতিক রং",
        technique: "হাতে খোদাই ও প্রাকৃতিক রঙের তুলির কাজ",
        motif: "পল্লী জীবন ও নর্তকী",
        colors: ["সিঁদুরে লাল", "হলুদ", "নীল"],
        region: "অন্ধ্রপ্রদেশ (কোন্ডাপল্লী)",
        description: "হালকা কাঠে নিখুঁত হাতে খোদাই করে প্রাকৃতিক রঙে আঁকা ঐতিহ্যবাহী কোন্ডাপল্লী পুতুল।",
        culturalContext: "৪০০ বছরের সুপ্রাচীন অন্ধ্র পুতুল শিল্পের নিদর্শন।",
        visualFeatures: ["জীবন্ত মুখের অভিব্যক্তি", "হাতে আঁকা নকশা"]
      },
      or: {
        craftCategory: "କଣ୍ଢେଇ ଶିଳ୍ପ",
        craftName: "କୋଣ୍ଡାପଲ୍ଲୀ ପାରମ୍ପରିକ କଣ୍ଢେଇ",
        productType: "ହସ୍ତଶିଳ୍ପ କଣ୍ଢେଇ",
        material: "ହାଲୁକା କାଠ ଓ ପ୍ରାକୃତିକ ରଙ୍ଗ",
        technique: "ହାତ ଖୋଦେଇ ଓ ରଙ୍ଗ ଚିତ୍ରଣ",
        motif: "ଗ୍ରାମୀଣ ଲୋକଜୀବନ",
        colors: ["ସିନ୍ଦୂର ନାଲି", "ହଳଦିଆ", "ନୀଳ"],
        region: "ଆନ୍ଧ୍ରପ୍ରଦେଶ",
        description: "ହାଲୁକା କାଠରେ ହାତରେ ଖୋଦେଇ ହୋଇ ପ୍ରାକୃତିକ ରଙ୍ଗରେ ସଜ୍ଜିତ ପ୍ରସିଦ୍ଧ କୋଣ୍ଡାପଲ୍ଲୀ କଣ୍ଢେଇ।",
        culturalContext: "ଦକ୍ଷିଣ ଭାରତର ୪୦୦ ବର୍ଷ ପୁରୁଣା କଣ୍ଢେଇ ନିର୍ମାଣ ପରମ୍ପରା।",
        visualFeatures: ["ଜୀବନ୍ତ ମୁଖାକୃତି", "ସୁନ୍ଦର ପ୍ରାକୃତିକ ରଙ୍ଗ"]
      },
      pa: {
        craftCategory: "ਗੁੱਡੀ ਦਸਤਕਾਰੀ",
        craftName: "ਕੋਂਡਾਪੱਲੀ ਰਵਾਇਤੀ ਗੁੱਡੀ",
        productType: "ਦਸਤਕਾਰੀ ਗੁੱਡੀ",
        material: "ਹਲਕੀ ਲੱਕੜ ਅਤੇ ਕੁਦਰਤੀ ਰੰਗ",
        technique: "ਹੱਥੀਂ ਤਰਾਸ਼ੀ ਅਤੇ ਰੰਗਾਈ",
        motif: "ਪੇਂਡੂ ਲੋਕ ਜੀਵਨ",
        colors: ["ਸੰਧੂਰੀ ਲਾਲ", "ਪੀਲਾ", "ਨੀਲਾ"],
        region: "ਆਂਧਰਾ ਪ੍ਰਦੇਸ਼",
        description: "ਹਲਕੀ ਲੱਕੜ ਤੋਂ ਹੱਥੀਂ ਘੜੀ ਅਤੇ ਕੁਦਰਤੀ ਰੰਗਾਂ ਨਾਲ ਸਜਾਈ ਗਈ ਕੋਂਡਾਪੱਲੀ ਗੁੱਡੀ।",
        culturalContext: "੪੦੦ ਸਾਲ ਪੁਰਾਣੀ ਭਾਰਤੀ ਗੁੱਡੀ ਬਣਾਉਣ ਦੀ ਵਿਰਾਸਤ।",
        visualFeatures: ["ਜੀਵੰਤ ਚਿਹਰੇ ਦੇ ਹਾਵ-ਭਾਵ", "ਰਵਾਇਤੀ ਲੋਕ ਰੰਗ"]
      },
      as: {
        craftCategory: "পুতলা শিল্প",
        craftName: "কোণ্ডাপল্লী পৰম্পৰাগত পুতলা",
        productType: "হস্তশিল্প পুতলা",
        material: "পাতল কাঠ আৰু প্ৰাকৃতিক ৰং",
        technique: "হাতেৰে কটা আৰু চিত্ৰাংকন",
        motif: "গাঁওলীয়া জীৱনৰ চিত্ৰ",
        colors: ["সেন্দুৰীয়া ৰঙা", "হালধীয়া", "নীলা"],
        region: "অন্ধ্ৰপ্ৰদেশ",
        description: "পাতল কাঠত হাতেৰে কাটি প্ৰাকৃতিক ৰঙেৰে জীবন্ত ৰূপ দিয়া ঐতিহ্যমণ্ডিত কোণ্ডাপল্লী পুতলা।",
        culturalContext: "৪০০ বছৰীয়া ভাৰতীয় লোকশিল্প পুতলা ঐতিহ্য।",
        visualFeatures: ["জীৱন্ত মুখৰ ভংগিমা", "প্ৰাকৃতিক ৰঙৰ প্ৰলেপ"]
      }
    }
  },

  // 10. Handmade Jewelry (Temple & Terracotta Artisan Jewelry)
  {
    keywords: ["handmade jewelry", "terracotta jewelry", "meenakari", "filigree", "tarakasi", "tribal jewelry", "beadwork", "jewelry"],
    canonical: {
      craftCategory: "Jewelry",
      craftName: "Handmade Artisan Jewelry",
      productType: "Jewelry Set (Necklace & Earrings)",
      material: "Natural Terracotta Clay / Brass with Semi-Precious Beads",
      technique: "Kiln Firing & Hand-Painted Filigree Embellishment",
      motif: "Peacock Mayura & Floral Medallion",
      colors: ["Antique Gold", "Ruby Red", "Deep Emerald"],
      region: "Likely Cuttack (Odisha) / Bengal / South India",
      description: "Artisan-crafted statement jewelry hand-modeled and kiln-baked with fine filigree motifs, finished in antique luster.",
      culturalContext: "Centuries-old Indian temple jewelry and clay adornment tradition crafted for celebratory festive adornment.",
      visualFeatures: ["Hand-crimped filigree wire relief", "Baked clay chime resonance", "Hand-set traditional glass cabochons"],
      confidence: 0.88,
      uncertainAttributes: ["gem authenticity"]
    },
    translations: {
      en: {
        craftCategory: "Jewelry",
        craftName: "Handmade Artisan Jewelry",
        productType: "Jewelry Set",
        material: "Natural Terracotta Clay / Brass with Semi-Precious Beads",
        technique: "Kiln Firing & Hand-Painted Filigree Embellishment",
        motif: "Peacock Mayura & Floral Medallion",
        colors: ["Antique Gold", "Ruby Red", "Deep Emerald"],
        region: "Likely Cuttack / Bengal / South India",
        description: "Artisan-crafted statement jewelry hand-modeled and kiln-baked with fine filigree motifs, finished in antique luster.",
        culturalContext: "Centuries-old Indian temple jewelry and clay adornment tradition crafted for celebratory festive adornment.",
        visualFeatures: ["Hand-crimped filigree wire relief", "Baked clay chime resonance", "Hand-set traditional glass cabochons"]
      },
      te: {
        craftCategory: "ఆభరణాల కళ",
        craftName: "చేతితో చేసిన కళాత్మక నగలు",
        productType: "నగల సెట్",
        material: "సహజ టెర్రకోట మట్టి / ఇత్తడి & పూసలు",
        technique: "బట్టీ కాల్పులు & చేతి నగిషీ పని",
        motif: "నెమలి మరియు పూల పతకం",
        colors: ["పురాతన బంగారం", "కెంపు ఎరుపు", "పచ్చ"],
        region: "దక్షిణ / తూర్పు భారత హస్తకళా ప్రాంతం",
        description: "చేతితో మట్టిని మలిచి, బట్టీలో కాల్చి సాంప్రదాయ నగిషీలతో తయారు చేసిన అందమైన హస్తకళా ఆభరణాలు.",
        culturalContext: "భారతీయ సాంప్రదాయ ఆలయ ఆభరణాల వారసత్వం.",
        visualFeatures: ["సున్నితమైన చేతి నగిషీ", "పురాతన బంగారు మెరుపు"]
      },
      hi: {
        craftCategory: "आभूषण शिल्प",
        craftName: "हस्तनिर्मित पारंपरिक आभूषण",
        productType: "आभूषण सेट",
        material: "टेराकोटा मिट्टी / पीतल एवं मनके",
        technique: "भट्ठी में पकाई एवं बारीक मीनाकारी",
        motif: "मयूर एवं पारंपरिक पदक",
        colors: ["प्राचीन स्वर्ण", "माणिक लाल", "पन्ना हरा"],
        region: "संभावित कटक / बंगाल / दक्षिण भारत",
        description: "हाथ से गढ़ा हुआ और भट्ठी में पकाया गया आकर्षक पारंपरिक आभूषण सेट, जिसमें बारीक हस्तकला दिखाई देती है।",
        culturalContext: "भारतीय मंदिर आभूषण और लोक कला की प्राचीन विरासत।",
        visualFeatures: ["हाथ की महीन तारकशी", "पारंपरिक शाही रूप"]
      },
      ta: {
        craftCategory: "நகை கைவினை",
        craftName: "கைவினை பாரம்பரிய நகைகள்",
        productType: "நகைத் தொகுப்பு",
        material: "சுடுமண் / பித்தளை மற்றும் மணிகள்",
        technique: "சுடுமண் உருவாக்கம் மற்றும் நுண் வேலைப்பாடு",
        motif: "மயில் மற்றும் தாமரை வடிவம்",
        colors: ["பழங்கால தங்கம்", "சிவப்பு", "பச்சை"],
        region: "தென்னிந்தியா / ஒடிசா பகுதி",
        description: "கைவினைக் கலைஞர்களால் கையால் வடிக்கப்பட்டு சுடப்பட்ட தனித்துவமான கலைநயமிக்க பாரம்பரிய நகை.",
        culturalContext: "கோயில் நகைக்கலையின் பழமையான பாரம்பரியம்.",
        visualFeatures: ["நுணுக்கமான கைவேலைப்பாடு", "பழங்கால தங்கப் பொலிவு"]
      },
      kn: {
        craftCategory: "ಆಭರಣ ಕಲೆ",
        craftName: "ಕೈಯಿಂದ ಮಾಡಿದ ಆಭರಣಗಳು",
        productType: "ಆಭರಣ ಸೆಟ್",
        material: "ಟೆರ್ರಾಕೋಟಾ ಜೇಡಿಮಣ್ಣು / ಹಿತ್ತಾಳೆ",
        technique: "ಕೈ ಕೆತ್ತನೆ ಮತ್ತು ನೈಸರ್ಗಿಕ ಹೊಳಪು",
        motif: "ನವಿಲು ಮತ್ತು ಹೂವಿನ ವಿನ್ಯಾಸ",
        colors: ["ಚಿನ್ನದ ಛಾಯೆ", "ಮಾಣಿಕ್ಯ ಕೆಂಪು", "ಹಸಿರು"],
        region: "ದಕ್ಷಿಣ ಭಾರತ",
        description: "ಮಣ್ಣಿನಿಂದ ಕೈಯಲ್ಲೇ ರೂಪಿಸಿ ಸುಟ್ಟ ಆಕರ್ಷಕ ಪಾರಂಪರಿಕ ಕರಕುಶಲ ಆಭರಣ.",
        culturalContext: "ಭಾರತದ ಐತಿಹಾಸಿಕ ದೇವಾಲಯ ಆಭರಣ ಸಂಸ್ಕೃತಿ.",
        visualFeatures: ["ಸೂಕ್ಷ್ಮ ಕೈಕೆಲಸ", "ಪ್ರಾಚೀನ ರಾಯಲ್ ನೋಟ"]
      },
      ml: {
        craftCategory: "ആഭരണ നിർമ്മാണം",
        craftName: "ഹാൻഡ്‌മെയ്ഡ് പാരമ്പര്യ ആഭരണങ്ങൾ",
        productType: "ആഭരണ സെറ്റ്",
        material: "ടെറാക്കോട്ട / പിച്ചള",
        technique: "കൈകൊണ്ടുള്ള നിർമ്മാണവും മിനുക്കുപണിയും",
        motif: "മയിൽ മാതൃക",
        colors: ["ആന്റിക് ഗോൾഡ്", "മാണിക്യ ചുവപ്പ്", "പച്ച"],
        region: "ദക്ഷിണേന്ത്യ",
        description: "കൈകൊണ്ട് അതിവിദഗ്ദ്ധമായി നിർമ്മിച്ച തനിമയാർന്ന കരകൗശല ആഭരണം.",
        culturalContext: "ക്ഷേത്ര ആഭരണ നിർമ്മാണത്തിന്റെ പാരമ്പര്യം.",
        visualFeatures: ["സൂക്ഷ്മമായ കൊത്തുപണികൾ", "പഴമയുടെ ഭംഗി"]
      },
      mr: {
        craftCategory: "दागिने हस्तकला",
        craftName: "हस्तनिर्मित पारंपरिक दागिने",
        productType: "दागिने संच",
        material: "टेराकोटा माती / पितळ",
        technique: "हातघडणावळ आणि मीनाकारी",
        motif: "मोर आणि फुले",
        colors: ["प्राचीन सोनेरी", "माणिक लाल", "हिरवा"],
        region: "महाराष्ट्र / दक्षिण भारत",
        description: "हाताने मातीतून घडवून भाजलेले आणि रंगवलेले पारंपरिक राजेशाही दागिने.",
        culturalContext: "प्राचीन भारतीय मंदिर दागिने परंपरा.",
        visualFeatures: ["बारीक कलाकुसर", "अस्सल पारंपरिक रूप"]
      },
      gu: {
        craftCategory: "ઘરેણાં કળા",
        craftName: "હાથબનાવટ પરંપરાગત ઘરેણાં",
        productType: "ઘરેણાં સેટ",
        material: "ટેરાકોટા માટી / પિત્તળ",
        technique: "હાથની ઘડાઈ અને મીનાકારી",
        motif: "મોર અને પરંપરાગત ફૂલ",
        colors: ["એન્ટિક ગોલ્ડ", "લાલ", "લીલો"],
        region: "પશ્ચિમ / દક્ષિણ ભારત",
        description: "કારીગરો દ્વારા હાથેથી કંડારેલા અને સુંદર મીનાકારીથી શણગારેલા પરંપરાગત ઘરેણાં.",
        culturalContext: "ભારતીય આભૂષણ શિલ્પની ભવ્ય વિરાસત.",
        visualFeatures: ["ઝીણી હાથકારીગરી", "શાહી એન્ટિક દેખાવ"]
      },
      bn: {
        craftCategory: "গহনা শিল্প",
        craftName: "হাতে তৈরি ঐতিহ্যবাহী গহনা",
        productType: "গহনার সেট",
        material: "পোড়ামাটি (টেরাকোটা) / পিতল ও পুঁতি",
        technique: "হাতে গড়া ও ফিলগ্রি নকশা",
        motif: "ময়ূর ও পদ্ম",
        colors: ["সোনালী", "রুবি লাল", "পান্না সবুজ"],
        region: "কটক / বাংলা",
        description: "হাতে যত্ন নিয়ে গড়া এবং পোড়ানো মাটির অনবদ্য ঐতিহ্যবাহী কারুশিল্প গহনা।",
        culturalContext: "বাংলার টেরাকোটা ও কটকের তারকাশির প্রাচীন গহনা ঐতিহ্য।",
        visualFeatures: ["নিখুঁত তারকাশি কাজ", "রাজকীয় রূপ"]
      },
      or: {
        craftCategory: "ଅଳଙ୍କାର କଳା",
        craftName: "ହସ୍ତନିର୍ମିତ ତାରକସି ଓ ଟେରାକୋଟା ଗହଣା",
        productType: "ଅଳଙ୍କାର ସେଟ୍",
        material: "ଟେରାକୋଟା ମାଟି / ପିତ୍ତଳ ଓ ରୂପା ତାର",
        technique: "ତାରକସି କାମ ଓ ହସ୍ତନିର୍ମାଣ",
        motif: "ମୟୂର ଓ ପଦ୍ମ",
        colors: ["ସୁନେଲି", "ମାଣିକ ନାଲି", "ସବୁଜ"],
        region: "କଟକ (ଓଡ଼ିଶା)",
        description: "କଟକର ପ୍ରସିଦ୍ଧ ହସ୍ତନିର୍ମିତ ତାରକସି ଓ ମାଟି କାରୁକାର୍ଯ୍ୟର ଅନନ୍ୟ ଅଳଙ୍କାର।",
        culturalContext: "ଓଡ଼ିଶାର ରୂପା ତାରକସି ଓ ମନ୍ଦିର ଅଳଙ୍କାରର ସୁପ୍ରସିଦ୍ଧ ପରମ୍ପରା।",
        visualFeatures: ["ମହିନ ତାରକସି କାମ", "ପାରମ୍ପରିକ ଓଡ଼ିଶୀ ଶୈଳୀ"]
      },
      pa: {
        craftCategory: "ਗਹਿਣੇ ਦਸਤਕਾਰੀ",
        craftName: "ਹੱਥੀਂ ਬਣੇ ਰਵਾਇਤੀ ਗਹਿਣੇ",
        productType: "ਗਹਿਣਿਆਂ ਦਾ ਸੈੱਟ",
        material: "ਟੈਰਾਕੋਟਾ ਮਿੱਟੀ / ਪਿੱਤਲ",
        technique: "ਮੀਨਾਕਾਰੀ ਅਤੇ ਹੱਥੀਂ ਘੜਾਈ",
        motif: "ਮੋਰ ਅਤੇ ਫੁੱਲ",
        colors: ["ਐਂਟੀਕ ਗੋਲਡ", "ਲਾਲ", "ਹਰਾ"],
        region: "ਰਵਾਇਤੀ ਕਲਾ ਕੇਂਦਰ",
        description: "ਕਾਰੀਗਰਾਂ ਦੁਆਰਾ ਹੱਥੀਂ ਘੜੇ ਅਤੇ ਸਜਾਏ ਗਏ ਸ਼ਾਨਦਾਰ ਰਵਾਇਤੀ ਗਹਿਣੇ।",
        culturalContext: "ਭਾਰਤੀ ਸ਼ਾਹੀ ਗਹਿਣਿਆਂ ਦੀ ਅਮੀਰ ਵਿਰਾਸਤ।",
        visualFeatures: ["ਬਾਰੀਕ ਕਢਾਈ", "ਸ਼ਾਹੀ ਦਿੱਖ"]
      },
      as: {
        craftCategory: "অলংকাৰ শিল্প",
        craftName: "হাতেৰে তৈয়াৰী পৰম্পৰাগত অলংকাৰ",
        productType: "অলংকাৰৰ ছেট",
        material: "টেৰাকোটা মাটি / পিতল আৰু মণি",
        technique: "হাতেৰে গঢ়া আৰু মিনাকৰী কাম",
        motif: "ময়ূৰ আৰু পদুম ফুল",
        colors: ["সোণালী", "ৰঙা", "সেউজীয়া"],
        region: "ঐতিহ্যমণ্ডিত হস্তশিল্প কেন্দ্ৰ",
        description: "নিপুণ কাৰিকৰে হাতেৰে গঢ়ি তোলা মনোমোহা পৰম্পৰাগত অসমীয়া আৰু ভাৰতীয় গহনা।",
        culturalContext: "প্ৰাচীন ভাৰতীয় মন্দিৰ অলংকাৰ আৰু লোকশিল্পৰ নিদৰ্শন।",
        visualFeatures: ["সূক্ষ্ম হাতৰ কাম", "ঐতিহ্যবাহী ৰূপ"]
      }
    }
  }
];

/**
 * Universal term localization dictionary covering all 12 Indian languages
 * for categories, materials, techniques, motifs, colors, regions, and product types.
 */
export const LOCALIZED_TERMS: Record<string, Record<LanguageCode, string>> = {
  // Categories
  "Handloom": { en: "Handloom", hi: "हथकरघा", te: "చేనేత", ta: "கைத்தறி", kn: "ಕೈಮಗ್ಗ", ml: "കൈത്തറി", mr: "हातमाग", gu: "હાથશાળ", bn: "হস্তচালিত তাঁত", or: "ହସ୍ତତନ୍ତ", pa: "ਹੱਥ-ਖੱਡੀ", as: "তাঁতশাল" },
  "Weaving": { en: "Weaving", hi: "बुनाई", te: "నేత", ta: "நெசவு", kn: "ನೇಯ್ಗೆ", ml: "നെയ്ത്ത്", mr: "विणकाम", gu: "વણાટકામ", bn: "বয়ন", or: "ବୁଣା", pa: "ਬੁਣਾਈ", as: "বয়ন" },
  "Textile Art": { en: "Textile Art", hi: "वस्त्र कला", te: "వస్త్ర కళ", ta: "துணி ஓவியக் கலை", kn: "ವಸ್ತ್ರ ಕಲೆ", ml: "ടെക്സ്റ്റൈൽ കല", mr: "वस्त्रकला", gu: "વસ્ત્રકળા", bn: "বস্ত্রশিল্প", or: "ବସ୍ତ୍ରକଳା", pa: "ਕੱਪੜਾ ਕਲਾ", as: "বস্ত্রশিল্প" },
  "Woodcraft": { en: "Woodcraft", hi: "काष्ठ शिल्प", te: "చెక్క కళ", ta: "மரக் கைவினை", kn: "ಮರದ ಕೆತ್ತನೆ", ml: "തടിപ്പണി", mr: "लाकूडकाम", gu: "લાકડાકામ", bn: "কাষ্ঠশিল্প", or: "କାଠ କାର୍ଯ୍ୟ", pa: "ਲੱਕੜ ਦਾ ਕੰਮ", as: "কাঠশিল্প" },
  "Pottery": { en: "Pottery", hi: "मृत्तिका शिल्प", te: "మట్టి కళ", ta: "மட்பாண்டக் கலை", kn: "ಮಡಕೆ ಕಲೆ", ml: "മൺപാത്ര നിർമ്മാണം", mr: "कुंभारकाम", gu: "માટીકામ", bn: "মৃৎশিল্প", or: "ମାଟିପାତ୍ର କଳା", pa: "ਮਿੱਟੀ ਦੇ ਭਾਂਡੇ", as: "মৃৎশিল্প" },
  "Bamboo Craft": { en: "Bamboo Craft", hi: "बांस शिल्प", te: "వెదురు కళ", ta: "மூங்கில் கைவினை", kn: "ಬಿದಿರು ಕರಕುಶಲ", ml: "മുള കരകൗശലം", mr: "बांबू हस्तकला", gu: "વાંસકામ", bn: "বাঁশ শিল্প", or: "ବାଉଁଶ ଶିଳ୍ପ", pa: "ਬਾਂਸ ਦਸਤਕਾਰੀ", as: "বাঁহ শিল্প" },
  "Embroidery": { en: "Embroidery", hi: "कशीदाकारी", te: "ఎంబ్రాయిడరీ", ta: "தையல் கலை", kn: "ಕಸೂತಿ ಕಲೆ", ml: "എംബ്രോയിഡറി", mr: "भरतकाम", gu: "ભરતકામ", bn: "সূচিকর্ম", or: "କସିଦାକାରୀ", pa: "ਕਢਾਈ", as: "সূচিশিল্প" },
  "Metalcraft": { en: "Metalcraft", hi: "धातु शिल्प", te: "లోహ కళ", ta: "உலோகக் கலை", kn: "ಲೋಹದ ಕಲೆ", ml: "ലോഹപ്പണി", mr: "धातुकाम", gu: "ધાતુકામ", bn: "ধাতুশিল্প", or: "ଧାତୁ କଳା", pa: "ਧਾਤ ਦਾ ਕੰਮ", as: "ধাতুশিল্প" },
  "Toy & Doll Craft": { en: "Toy & Doll Craft", hi: "खिलौना एवं गुड़िया शिल्प", te: "బొమ్మల కళ", ta: "பொம்மை கலை", kn: "ಗೊಂಬೆ ಕಲೆ", ml: "പാവ നിർമ്മാണം", mr: "खेळणी हस्तकला", gu: "રમકડાં કળા", bn: "পুতুল শিল্প", or: "କଣ୍ଢେଇ ଶିଳ୍ପ", pa: "ਗੁੱਡੀ ਦਸਤਕਾਰੀ", as: "পুতলা শিল্প" },
  "Jewelry": { en: "Jewelry", hi: "आभूषण", te: "ఆభరణాలు", ta: "நகைகள்", kn: "ಆಭರಣ", ml: "ആഭരണങ്ങൾ", mr: "दागिने", gu: "ઘરેણાં", bn: "গহনা", or: "ଅଳଙ୍କାର", pa: "ਗਹਿਣੇ", as: "অলংকাৰ" },

  // Materials
  "Silk": { en: "Pure Silk", hi: "शुद्ध रेशम", te: "స్వచ్ఛమైన పట్టు", ta: "தூய பட்டு", kn: "ಶುದ್ಧ ರೇಷ್ಮೆ", ml: "ശുദ്ധമായ പട്ട്", mr: "शुद्ध रेशीम", gu: "શુદ્ધ રેશમ", bn: "খাঁটি রেশম", or: "ବିଶୁଦ୍ଧ ରେଶମ", pa: "ਸ਼ੁੱਧ ਰੇਸ਼ਮ", as: "বিশুদ্ধ ৰেচম" },
  "Pure Mulberry Silk": { en: "Pure Mulberry Silk", hi: "शुद्ध शहतूत रेशम", te: "స్వచ్ఛమైన మల్బరీ పట్టు", ta: "தூய மல்பெரி பட்டு", kn: "ಶುದ್ಧ ರೇಷ್ಮೆ", ml: "ശുദ്ധമായ പട്ട്", mr: "शुद्ध रेशीम", gu: "શુદ્ધ રેશમ", bn: "খাঁটি তুঁত রেশম", or: "ବିଶୁଦ୍ଧ ପାଟ", pa: "ਸ਼ੁੱਧ ਰੇਸ਼ਮ", as: "বিশুদ্ধ পাট ৰেচম" },
  "Cotton": { en: "Cotton", hi: "सूती", te: "పత్తి", ta: "பருத்தி", kn: "ಹತ್ತಿ", ml: "പരുത്തി", mr: "सुती", gu: "સુતરાઉ", bn: "সুতি", or: "କପା", pa: "ਸੂਤੀ", as: "কপাহী" },
  "Pure Handloom Cotton": { en: "Pure Handloom Cotton", hi: "शुद्ध हथकरघा सूती", te: "చేనేత పత్తి", ta: "கைத்தறி பருத்தி", kn: "ಕೈಮಗ್ಗದ ಹತ್ತಿ", ml: "കൈത്തറി കോട്ടൺ", mr: "हातमाग सुती", gu: "હાથશાળ સુતરાઉ", bn: "খাঁটি তাঁতের সুতি", or: "ହସ୍ତତନ୍ତ ସୂତା", pa: "ਹੱਥ-ਖੱਡੀ ਸੂਤੀ", as: "হাতে বোৱা কপাহী" },
  "Clay": { en: "Terracotta Clay", hi: "मिट्टी", te: "బంకమట్టి", ta: "களிமண்", kn: "ಜೇಡಿಮಣ್ಣು", ml: "കളിമണ്ണ്", mr: "माती", gu: "માટી", bn: "মাটি", or: "ମାଟି", pa: "ਮਿੱਟੀ", as: "মাটি" },
  "Natural Terracotta Clay": { en: "Natural Terracotta Clay", hi: "प्राकृतिक मिट्टी", te: "సహజ బంకమట్టి / టెర్రకోట", ta: "இயற்கை சுடுமண்", kn: "ನೈಸರ್ಗಿಕ ಮಣ್ಣು", ml: "പ്രകൃതിദത്ത കളിമണ്ണ്", mr: "नैसर्गिक माती", gu: "કુદરતી માટી", bn: "প্রাকৃতিক পোড়ামাটি", or: "ପ୍ରାକୃତିକ ମାଟି", pa: "ਕੁਦਰਤੀ ਮਿੱਟੀ", as: "প্ৰাকৃতিক মাটি" },
  "Wood": { en: "Seasoned Wood", hi: "लकड़ी", te: "చెక్క", ta: "மரம்", kn: "ಮರ", ml: "തടി", mr: "लाकूड", gu: "લાકડું", bn: "কাঠ", or: "କାଠ", pa: "ਲੱਕੜ", as: "কাঠ" },
  "Brass": { en: "Brass & Bell Metal", hi: "पीतल एवं कांसा", te: "ఇత్తడి & కంచు", ta: "பித்தளை மற்றும் வெண்கலம்", kn: "ಹಿತ್ತಾಳೆ ಮತ್ತು ಕಂಚು", ml: "പിച്ചളയും വെങ്കലവും", mr: "पितळ आणि कासे", gu: "પિત્તળ અને કાંસું", bn: "পিতল ও কাঁসা", or: "ପିତ୍ତଳ ଏବଂ କଂସା", pa: "ਪਿੱਤਲ ਅਤੇ ਕਾਂਸੀ", as: "পিতল আৰু কাঁহ" },
  "Bamboo": { en: "Bamboo & Cane", hi: "बांस एवं बेंत", te: "వెదురు & బెత్తం", ta: "மூங்கில் மற்றும் பிரம்பு", kn: "ಬಿದಿರು ಮತ್ತು ಬೆತ್ತ", ml: "മുളയും ചൂരലും", mr: "बांबू आणि वेत", gu: "વાંસ અને નેતર", bn: "বাঁশ ও বেত", or: "ବାଉଁଶ ଓ ବେତ", pa: "ਬਾਂਸ ਅਤੇ ਬੈਂਤ", as: "বাঁহ আৰু বেত" },

  // Products
  "Saree": { en: "Saree", hi: "साड़ी", te: "చీర", ta: "புடவை", kn: "ಸೀರೆ", ml: "സാരി", mr: "साडी", gu: "સાડી", bn: "শাড়ি", or: "ଶାଢ଼ୀ", pa: "ਸਾੜ੍ਹੀ", as: "শাড়ী" },
  "Lacquered Wooden Toy": { en: "Wooden Toy", hi: "लकड़ी का खिलौना", te: "చెక్క బొమ్మ", ta: "மரப் பொம்மை", kn: "ಮರದ ಆಟಿಕೆ", ml: "തടി കളിപ്പാട്ടം", mr: "लाकडी खेळणे", gu: "લાકડાનું રમકડું", bn: "কাঠের খেলনা", or: "କାଠ ଖେଳଣା", pa: "ਲੱਕੜ ਦਾ ਖਿਡੌਣਾ", as: "কাঠৰ খেলনা" },
  "Decorative Ceramic Vase": { en: "Ceramic Vase", hi: "सिरेमिक फूलदान", te: "పింగాణీ పూలకుండీ", ta: "பீங்கான் மலர்க்குவளை", kn: "ಹೂದಾನಿ", ml: "സെറാമിക് പാത്രം", mr: "सिरेमिक फुलदाणी", gu: "સિરામિક કૂંજો", bn: "সিরামিক ফুলদানি", or: "ଫୁଲଦାନୀ", pa: "ਸਜਾਵਟੀ ਫੁੱਲਦਾਨ", as: "সিৰামিক ফুলদানী" },
  "Storage Basket": { en: "Storage Basket", hi: "टोकरी", te: "బుట్ట", ta: "கூடை", kn: "ಬುಟ್ಟಿ", ml: "കൊട്ട", mr: "टोपली", gu: "ટોપલી", bn: "ঝুড়ি", or: "ଟୋକେଇ", pa: "ਟੋਕਰੀ", as: "পাচি" },
  "Bell Metal Sculpture": { en: "Metal Sculpture", hi: "धातु मूर्ति", te: "లోహ విగ్రహం", ta: "உலோகச் சிற்பம்", kn: "ಲೋಹದ ಮೂರ್ತಿ", ml: "വെങ്കല ശിൽപം", mr: "धातूमूर्ती", gu: "ધાતુ શિલ્પ", bn: "ধাতব ভাস্কর্য", or: "ଧାତୁ ମୂର୍ତ୍ତି", pa: "ਧਾਤੂ ਮੂਰਤੀ", as: "ধাতুৰ ভাস্কৰ্য" },
  "Artisan Handicraft Doll": { en: "Handmade Doll", hi: "हस्तशिल्प गुड़िया", te: "చేతితో చేసిన బొమ్మ", ta: "கைவினைப் பொம்மை", kn: "ಕರಕುಶಲ ಗೊಂಬೆ", ml: "കരകൗശല പാവ", mr: "हस्तकला बाहुली", gu: "હસ્તકલા ઢીંગલી", bn: "হস্তশিল্প পুতুল", or: "ହସ୍ତଶିଳ୍ପ କଣ୍ଢେଇ", pa: "ਦਸਤਕਾਰੀ ਗੁੱਡੀ", as: "হস্তশিল্প পুতলা" },
  "Jewelry Set": { en: "Jewelry Set", hi: "आभूषण सेट", te: "నగల సెట్", ta: "நகைத் தொகுப்பு", kn: "ಆಭರಣ ಸೆಟ್", ml: "ആഭരണ സെറ്റ്", mr: "दागिने संच", gu: "ઘરેણાં સેટ", bn: "গহনার সেট", or: "ଅଳଙ୍କାର ସେଟ୍", pa: "ਗਹਿਣਿਆਂ ਦਾ ਸੈੱਟ", as: "অলংকাৰৰ ছেট" },

  // Techniques
  "Ikat weaving": { en: "Ikat Weaving", hi: "इकत बुनाई", te: "ఇక్కత్ నేత", ta: "இக்கத் நெசவு", kn: "ಇಕ್ಕತ್ ನೇಕಾರಿಕೆ", ml: "ഇക്കത്ത് നെയ്ത്ത്", mr: "इकत विणकाम", gu: "ઇકત વણાટ", bn: "ইকত বয়ন", or: "ଇକତ ବୁଣା", pa: "ਇਕਤ ਬੁਣਾਈ", as: "ইকৎ বয়ন" },
  "Hand-Block Printing": { en: "Block Printing", hi: "ब्लॉक छपाई", te: "బ్లాక్ ప్రింటింగ్", ta: "அச்சுப் பதித்தல்", kn: "ಬ್ಲಾಕ್ ಪ್ರಿಂಟಿಂಗ್", ml: "ബ്ലോക്ക് പ്രിന്റിംഗ്", mr: "ठसा छपाई", gu: "બ્લોક પ્રિન્ટિંગ", bn: "ব্লক প্রিন্ট", or: "ବ୍ଲକ ଛାପା", pa: "ਬਲਾਕ ਛਪਾਈ", as: "ব্লক ছপা" },
  "Hand Embroidery": { en: "Hand Embroidery", hi: "हाथ की कढ़ाई", te: "చేతి కుట్టుపని", ta: "கைத்தையல்", kn: "ಕೈಕಸೂತಿ", ml: "കൈത്തയ്യൽ", mr: "हात भरतकाम", gu: "હાથ ભરતકામ", bn: "হাতের কাজ", or: "ହସ୍ତ କସିଦା", pa: "ਹੱਥ ਦੀ ਕਢਾਈ", as: "হাতেৰে কঢাই" },
  "Lost-Wax Casting": { en: "Lost-Wax Casting", hi: "मोम ढलाई", te: "మైనపు అచ్చు పోత", ta: "மெழுகு வார்ப்பு", kn: "ಮೇಣದ ಎರಕ", ml: "മെഴുക് വാർപ്പ്", mr: "मेण ओतकाम", gu: "મીણ ઢાળવું", bn: "মোম ঢালাই", or: "ମହମ ଢଳେଇ", pa: "ਮੋਮ ਢਲਾਈ", as: "মম গলাই ছাঁচ" },

  // Common Colors
  "Red": { en: "Red", hi: "लाल", te: "ఎరుపు", ta: "சிவப்பு", kn: "ಕೆಂಪು", ml: "ചുവപ്പ്", mr: "लाल", gu: "લાલ", bn: "লাল", or: "ନାଲି", pa: "ਲਾਲ", as: "ৰঙা" },
  "Blue": { en: "Blue", hi: "नीला", te: "నీలం", ta: "நீலம்", kn: "ನೀಲಿ", ml: "നീല", mr: "निळा", gu: "વાદળી", bn: "নীল", or: "ନୀଳ", pa: "ਨੀਲਾ", as: "নীলা" },
  "Yellow": { en: "Yellow", hi: "पीला", te: "పసుపు", ta: "மஞ்சள்", kn: "ಹಳದಿ", ml: "മഞ്ഞ", mr: "पिवळा", gu: "પીળો", bn: "হলুদ", or: "ହଳଦିଆ", pa: "ਪੀਲਾ", as: "হালধীয়া" },
  "Green": { en: "Green", hi: "हरा", te: "ఆకుపచ్చ", ta: "பச்சை", kn: "ಹಸಿರು", ml: "പച്ച", mr: "हिरवा", gu: "લીલો", bn: "সবুজ", or: "ସବୁଜ", pa: "ਹਰਾ", as: "সেউজীয়া" },
  "White": { en: "White", hi: "सफेद", te: "తెలుపు", ta: "வெள்ளை", kn: "ಬಿಳಿ", ml: "വെള്ള", mr: "पांढरा", gu: "સફેદ", bn: "সাদা", or: "ଧଳା", pa: "ਚਿੱਟਾ", as: "বগা" },
  "Black": { en: "Black", hi: "काला", te: "నలుపు", ta: "கருப்பு", kn: "ಕಪ್ಪು", ml: "കറുപ്പ്", mr: "काळा", gu: "કાળો", bn: "কালো", or: "କଳା", pa: "ਕਾਲਾ", as: "কলা" },
  "Gold": { en: "Gold", hi: "सुनहरा", te: "బంగారు రంగు", ta: "தங்க நிறம்", kn: "ಚಿನ್ನದ ಬಣ್ಣ", ml: "സ്വർണ്ണ നിറം", mr: "सोनेरी", gu: "સોનેરી", bn: "সোনালী", or: "ସୁନେଲି", pa: "ਸੁਨਹਿਰੀ", as: "সোণালী" }
};
