import React, { useState, useEffect } from 'react';
import { FileText, Search, ShieldCheck, Eye, Download, Printer, CheckCircle, Calendar, DollarSign, X } from 'lucide-react';
import { useAdminAuth } from '../AdminAuthContext';
import { formatINR } from '../../lib/billingService';
import { Bill } from '../../types';

export function AdminBills() {
  const { fetchAdmin } = useAdminAuth();
  const [bills, setBills] = useState<Bill[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedBill, setSelectedBill] = useState<Bill | null>(null);

  const loadBills = async () => {
    setLoading(true);
    try {
      const res = await fetchAdmin('/api/admin/bills');
      if (res.ok) {
        const data = await res.json();
        setBills(Array.isArray(data) ? data : []);
      }
    } catch (e) {
      console.error('Failed to load bills:', e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadBills();
  }, []);

  const filteredBills = bills.filter((b) => {
    const q = searchTerm.toLowerCase();
    return (
      (b.billNumber || '').toLowerCase().includes(q) ||
      (b.sellerName || '').toLowerCase().includes(q) ||
      (b.productName || '').toLowerCase().includes(q) ||
      (b.productCategory || '').toLowerCase().includes(q)
    );
  });

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-slate-900 border border-slate-800 p-6 rounded-3xl">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-amber-950 text-amber-400 border border-amber-800/60">
              Financial Audit & Provenance
            </span>
            <span className="text-xs text-slate-400">Total Finalized Invoices: {bills.length}</span>
          </div>
          <h1 className="text-2xl font-black text-white font-['Rozha_One',serif]">
            Seller Bills & Invoice Ledger
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Inspect finalized handicraft bills generated by rural artisans, verify cost breakdowns, and audit fair-trade profit margins.
          </p>
        </div>
      </div>

      {/* Search */}
      <div className="relative">
        <Search className="w-4 h-4 absolute left-3.5 top-3 text-slate-500" />
        <input
          type="text"
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
          placeholder="Search by invoice number, artisan name, product name..."
          className="w-full pl-10 pr-4 py-2.5 bg-slate-900 border border-slate-800 rounded-xl text-white text-xs placeholder:text-slate-500 focus:outline-none focus:border-amber-500"
        />
      </div>

      {/* Table */}
      <div className="bg-slate-900 border border-slate-800 rounded-3xl overflow-hidden shadow-xl">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs text-slate-300">
            <thead className="bg-slate-950/80 text-slate-400 font-bold uppercase tracking-wider text-[10px] border-b border-slate-800">
              <tr>
                <th className="py-3.5 px-4">Invoice No. & Date</th>
                <th className="py-3.5 px-4">Artisan / Seller</th>
                <th className="py-3.5 px-4">Craft Piece & Qty</th>
                <th className="py-3.5 px-4">Production Cost</th>
                <th className="py-3.5 px-4">Final Selling Price</th>
                <th className="py-3.5 px-4">Artisan Profit</th>
                <th className="py-3.5 px-4">Status</th>
                <th className="py-3.5 px-4 text-right">Audit</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60">
              {loading ? (
                <tr>
                  <td colSpan={8} className="py-8 text-center text-slate-500">
                    Loading financial invoice ledger...
                  </td>
                </tr>
              ) : filteredBills.length === 0 ? (
                <tr>
                  <td colSpan={8} className="py-8 text-center text-slate-500">
                    No matching finalized bills found.
                  </td>
                </tr>
              ) : (
                filteredBills.map((b) => (
                  <tr key={b.id} className="hover:bg-slate-800/40 transition-colors">
                    <td className="py-3.5 px-4">
                      <div>
                        <p className="font-mono font-bold text-amber-300 text-xs">{b.billNumber}</p>
                        <p className="text-[11px] text-slate-500 flex items-center gap-1">
                          <Calendar className="w-3 h-3" />
                          {b.createdAt ? new Date(b.createdAt).toLocaleDateString() : 'Recent'}
                        </p>
                      </div>
                    </td>

                    <td className="py-3.5 px-4">
                      <div>
                        <p className="font-bold text-white text-xs">{b.sellerName}</p>
                        <p className="text-[11px] text-slate-500">{b.sellerLocation || 'Cluster Master'}</p>
                      </div>
                    </td>

                    <td className="py-3.5 px-4">
                      <div>
                        <p className="font-bold text-slate-200 text-xs">{b.productName}</p>
                        <p className="text-[11px] text-slate-400">
                          Qty: <span className="text-white font-bold">{b.quantity}</span> • {b.productCategory}
                        </p>
                      </div>
                    </td>

                    <td className="py-3.5 px-4">
                      <span className="text-slate-300 font-semibold">{formatINR(b.totalCost)}</span>
                    </td>

                    <td className="py-3.5 px-4">
                      <span className="font-black text-amber-400 text-xs">
                        {formatINR(b.finalPrice)}
                      </span>
                    </td>

                    <td className="py-3.5 px-4">
                      <div>
                        <p className="font-bold text-emerald-400 text-xs">+{formatINR(b.profit)}</p>
                        <span className="text-[10px] text-emerald-500 font-extrabold">
                          {b.profitPercentage}% margin
                        </span>
                      </div>
                    </td>

                    <td className="py-3.5 px-4">
                      <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-bold bg-emerald-950 text-emerald-400 border border-emerald-800/60 uppercase">
                        <CheckCircle className="w-3 h-3" />
                        {b.status}
                      </span>
                    </td>

                    <td className="py-3.5 px-4 text-right">
                      <button
                        onClick={() => setSelectedBill(b)}
                        className="p-1.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg transition-colors inline-flex items-center gap-1 text-xs font-semibold"
                        title="Audit Breakdown Sheet"
                      >
                        <Eye className="w-3.5 h-3.5" />
                        <span>Inspect</span>
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Bill Audit Modal */}
      {selectedBill && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-xs">
          <div className="bg-slate-900 border border-slate-800 rounded-3xl max-w-2xl w-full p-6 space-y-4 shadow-2xl max-h-[92vh] overflow-y-auto">
            <div className="flex items-center justify-between pb-3 border-b border-slate-800">
              <div>
                <span className="text-[10px] font-bold uppercase text-amber-400">Official Financial Invoice Audit</span>
                <h3 className="font-bold text-white text-lg font-mono">{selectedBill.billNumber}</h3>
              </div>
              <button
                onClick={() => setSelectedBill(null)}
                className="text-slate-400 hover:text-white"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="grid grid-cols-2 gap-4 p-4 bg-slate-950/60 rounded-2xl border border-slate-800 text-xs">
              <div>
                <p className="text-slate-500 text-[10px] uppercase font-bold">Seller / Artisan</p>
                <p className="font-bold text-white text-sm mt-0.5">{selectedBill.sellerName}</p>
                <p className="text-slate-400 text-xs">{selectedBill.sellerPhone}</p>
                <p className="text-slate-500 text-xs">{selectedBill.sellerLocation}</p>
              </div>
              <div>
                <p className="text-slate-500 text-[10px] uppercase font-bold">Handcrafted Product</p>
                <p className="font-bold text-white text-sm mt-0.5">{selectedBill.productName}</p>
                <p className="text-slate-400 text-xs">Category: {selectedBill.productCategory}</p>
                <p className="text-slate-400 text-xs">Quantity: {selectedBill.quantity} Units</p>
              </div>
            </div>

            {/* Cost Breakdown Sheet */}
            <div className="p-4 bg-slate-950/40 rounded-2xl border border-slate-800 space-y-2 text-xs">
              <h4 className="font-bold text-slate-300 text-xs uppercase tracking-wider mb-2">Cost Breakdown:</h4>
              <div className="flex justify-between py-1 border-b border-slate-800/80 text-slate-400">
                <span>Raw Material Cost:</span>
                <span className="text-white font-mono">{formatINR(selectedBill.materialCost)}</span>
              </div>
              <div className="flex justify-between py-1 border-b border-slate-800/80 text-slate-400">
                <span>Handcraft Labor & Artistry:</span>
                <span className="text-white font-mono">{formatINR(selectedBill.labourCost)}</span>
              </div>
              <div className="flex justify-between py-1 border-b border-slate-800/80 text-slate-400">
                <span>Packaging & Transport:</span>
                <span className="text-white font-mono">{formatINR(selectedBill.transportationCost || 0)}</span>
              </div>
              <div className="flex justify-between py-1 border-b border-slate-800/80 text-slate-400">
                <span>Other Cluster Expenses:</span>
                <span className="text-white font-mono">{formatINR(selectedBill.otherCost || 0)}</span>
              </div>
              <div className="flex justify-between py-2 text-sm font-bold text-slate-200">
                <span>Total Production Cost:</span>
                <span className="font-mono text-amber-400">{formatINR(selectedBill.totalCost)}</span>
              </div>
            </div>

            {/* Market Comparison Sheet */}
            <div className="p-4 bg-slate-950/40 rounded-2xl border border-slate-800 space-y-2 text-xs">
              <h4 className="font-bold text-slate-300 text-xs uppercase tracking-wider mb-2">Pricing Intelligence & Margin:</h4>
              <div className="grid grid-cols-3 gap-2 text-center p-2 bg-slate-900 rounded-xl border border-slate-800">
                <div>
                  <span className="text-[10px] text-slate-500 block">Market Min</span>
                  <span className="font-mono text-slate-300">{formatINR(selectedBill.marketMinPrice)}</span>
                </div>
                <div>
                  <span className="text-[10px] text-slate-500 block">Market Avg</span>
                  <span className="font-mono text-slate-200 font-bold">{formatINR(selectedBill.marketAveragePrice)}</span>
                </div>
                <div>
                  <span className="text-[10px] text-slate-500 block">Market Max</span>
                  <span className="font-mono text-slate-300">{formatINR(selectedBill.marketMaxPrice)}</span>
                </div>
              </div>

              <div className="flex justify-between py-1 text-slate-300">
                <span>AI Recommended Benchmark Price:</span>
                <span className="font-bold text-indigo-300">{formatINR(selectedBill.recommendedPrice)}</span>
              </div>
              <div className="flex justify-between py-1 text-slate-300">
                <span>Artisan Proposed Price:</span>
                <span className="font-semibold text-slate-200">{formatINR(selectedBill.proposedPrice)}</span>
              </div>
              <div className="flex justify-between py-2 border-t border-slate-800 text-sm font-bold">
                <span className="text-white">Final Agreed Selling Price:</span>
                <span className="font-mono text-amber-400 text-base">{formatINR(selectedBill.finalPrice)}</span>
              </div>
              <div className="flex justify-between py-2 bg-emerald-950/40 border border-emerald-800/40 px-3 rounded-xl text-emerald-400 font-bold">
                <span>Direct Artisan Profit Retained:</span>
                <span>+{formatINR(selectedBill.profit)} ({selectedBill.profitPercentage}% Net)</span>
              </div>
            </div>

            <div className="flex justify-end gap-2 pt-2">
              <button
                onClick={() => setSelectedBill(null)}
                className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-white rounded-xl text-xs font-bold"
              >
                Close Audit View
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
